/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 45
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 170 "/usr/include/libio.h"
struct _IO_FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 341 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;
#line 460
extern int _IO_getc(_IO_FILE *__fp ) ;
#line 145 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin ;
#line 147
extern struct _IO_FILE *stderr ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 520
extern int getchar(void) ;
#line 562
extern int putchar(int __c ) ;
#line 184 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) long ( __attribute__((__nonnull__(1))) strtol)(char const   * __restrict  __nptr ,
                                                                                    char ** __restrict  __endptr ,
                                                                                    int __base ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 43 "/usr/include/bits/errno.h"
extern  __attribute__((__nothrow__)) int *__errno_location(void)  __attribute__((__const__)) ;
#line 14 "/home/wslee/benchmarks/textformat/buthead-1.0/buthead.c"
int main(int argc , char **argv ) 
{ 
  long lines_to_skip ;
  long i ;
  int c ;
  char *p ;
  int *tmp ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;

  {
#line 20
  if (argc != 2) {
    {
    {
#line 21
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Usage: %s count\n",
            *(argv + 0));
    }
    {
#line 22
    exit(2);
    }
    }
  }
  {
  {
#line 25
  lines_to_skip = strtol((char const   */* __restrict  */)*(argv + 1), (char **/* __restrict  */)(& p),
                         10);
  }
  {
#line 27
  tmp = __errno_location();
  }
  }
#line 27
  if (*tmp) {
    {
    {
#line 28
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"buthead error: invalid line count \'%s\'\n",
            *(argv + 1));
    }
    {
#line 29
    exit(2);
    }
    }
  } else
#line 27
  if (lines_to_skip < 0L) {
    {
    {
#line 28
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"buthead error: invalid line count \'%s\'\n",
            *(argv + 1));
    }
    {
#line 29
    exit(2);
    }
    }
  } else
#line 27
  if ((int )*(*(argv + 1) + 0) == 0) {
    {
    {
#line 28
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"buthead error: invalid line count \'%s\'\n",
            *(argv + 1));
    }
    {
#line 29
    exit(2);
    }
    }
  } else
#line 27
  if ((int )*p != 0) {
    {
    {
#line 28
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"buthead error: invalid line count \'%s\'\n",
            *(argv + 1));
    }
    {
#line 29
    exit(2);
    }
    }
  }
#line 32
  i = 0L;
  {
  {
#line 32
  while (1) {
    while_continue___1: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 32
    if (! (i < lines_to_skip)) {
#line 32
      goto while_break;
    }
    {
    {
#line 33
    c = _IO_getc(stdin);
    }
    }
#line 33
    if (c == -1) {
      {
      {
#line 34
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"buthead error: EOF on line %ld while skipping %ld\n",
              i + 1L, lines_to_skip);
      }
      {
#line 36
      exit(1);
      }
      }
    }
#line 39
    if (c == 10) {
#line 39
      i ++;
    }
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 42
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue___0: /* CIL Label */ ;
    {
    {
#line 42
    c = getchar();
    }
    }
#line 42
    if (! (c != -1)) {
#line 42
      goto while_break___0;
    }
    {
    {
#line 43
    putchar(c);
    }
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break___0: /* CIL Label */ ;
  }
#line 45
  return (0);
}
}
