/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 45
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 170 "/usr/include/libio.h"
struct _IO_FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 199 "/usr/include/pcre.h"
struct real_pcre;
#line 199
struct real_pcre;
#line 200 "/usr/include/pcre.h"
typedef struct real_pcre pcre;
#line 214 "/usr/include/pcre.h"
struct pcre_extra {
   unsigned long flags ;
   void *study_data ;
   unsigned long match_limit ;
   void *callout_data ;
   unsigned char const   *tables ;
   unsigned long match_limit_recursion ;
};
#line 214 "/usr/include/pcre.h"
typedef struct pcre_extra pcre_extra;
#line 40 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
struct __anonstruct_confget_backend_31 {
   char const   *name ;
   int (*openfile)(void) ;
   int (*readfile)(void) ;
   int (*closefile)(void) ;
};
#line 40 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
typedef struct __anonstruct_confget_backend_31 confget_backend;
#line 41 "/usr/include/err.h"
extern void ( /* format attribute */  warnx)(char const   *__format  , ...) ;
#line 51
extern  __attribute__((__noreturn__)) void ( /* format attribute */  errx)(int __status ,
                                                                           char const   *__format 
                                                                           , ...) ;
#line 65 "/usr/include/fnmatch.h"
extern int fnmatch(char const   *__pattern , char const   *__name , int __flags ) ;
#line 147 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 339
extern int printf(char const   * __restrict  __format  , ...) ;
#line 562
extern int putchar(int __c ) ;
#line 662
extern int fputs(char const   * __restrict  __s , FILE * __restrict  __stream ) ;
#line 668
extern int puts(char const   *__s ) ;
#line 471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 142 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) strcmp)(char const   *__s1 ,
                                                                                     char const   *__s2 )  __attribute__((__pure__)) ;
#line 145
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) strncmp)(char const   *__s1 ,
                                                                                      char const   *__s2 ,
                                                                                      size_t __n )  __attribute__((__pure__)) ;
#line 397
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1))) strlen)(char const   *__s )  __attribute__((__pure__)) ;
#line 59 "/usr/include/getopt.h"
extern char *optarg ;
#line 73
extern int optind ;
#line 152
extern  __attribute__((__nothrow__)) int getopt(int ___argc , char * const  *___argv ,
                                                char const   *__shortopts ) ;
#line 268 "/usr/include/pcre.h"
extern pcre *pcre_compile(char const   * , int  , char const   ** , int * , unsigned char const   * ) ;
#line 279
extern int pcre_exec(pcre const   * , pcre_extra const   * , char const   * , int  ,
                     int  , int  , int * , int  ) ;
#line 297
extern pcre_extra *pcre_study(pcre const   * , int  , char const   ** ) ;
#line 48 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
FILE *conffile  ;
#line 51 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
char const   *filename  ;
#line 53 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
char const   *section  ;
#line 56 "/home/wslee/benchmarks/textformat/confget-1.02/confget.h"
int morevars  ;
#line 58
int foundvar(char const   *sec  __attribute__((__unused__)) , char const   *name ,
             char const   *value ) ;
#line 32 "/home/wslee/benchmarks/textformat/confget-1.02/confget_http_get.h"
extern confget_backend confget_http_get_backend ;
#line 32 "/home/wslee/benchmarks/textformat/confget-1.02/confget_ini.h"
extern confget_backend confget_ini_backend ;
#line 52 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int margc  ;
#line 54 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static char * const  *margv  ;
#line 56 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int showvarname  ;
#line 58 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int manyvars  ;
#line 60 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static char const   *matchvalue  ;
#line 62 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static char const   *output_prefix  ;
#line 64 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static char const   *output_postfix  ;
#line 69 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static confget_backend *backends[2]  = {      & confget_http_get_backend,      & confget_ini_backend};
#line 75
static int find_backend(char const   *name ) ;
#line 76
static int init(int argc , char * const  *argv ) ;
#line 77
static void usage(int error ) ;
#line 78
static void version(void) ;
#line 81 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
confget_backend *backend  ;
#line 87 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
int cflag  ;
#line 89 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
int cfound  ;
#line 91 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int lflag  ;
#line 93 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int Lflag  ;
#line 95 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int Sflag  ;
#line 98 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int xflag  ;
#line 100 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static pcre *x_matchvalue  ;
#line 100 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static pcre **x_margv  ;
#line 101 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static pcre_extra *x_matchvalue_extra  ;
#line 101 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static pcre_extra **x_margv_extra  ;
#line 115 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static void usage(int error ) 
{ 
  char const   *s1 ;
  char const   *s2 ;
  char const   *s3 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;

  {
#line 118
  s1 = "Usage:\nconfget [-cSx] [-N | -n] [-f filename] [-m pattern] [-P postfix] [-p prefix]\n        [-s section] [-t type] var...\n\nconfget [-Sx] [-N | -n] [-f filename] [-m pattern] [-P postfix] [-p prefix]\n        [-s section] [-t type] -L pattern...\n\nconfget [-Sx] [-N | -n] [-f filename] [-m pattern] [-P postfix] [-p prefix]\n        [-s section] [-t type] -l\n\nconfget [-hTV]\n\n";
#line 129
  s2 = "\t-c\tcheck if the variable is defined in the file;\n\t-f\tspecify the configuration file to read from,\n\t\tor \"-\" for standard input;\n\t-h\tdisplay usage information and exit;\n\t-L\tspecify which variables to display;\n\t-l\tlist all variables in the specified section;\n\t-m\tonly display values that match the specified pattern;\n\t-N\talways display the variable name;\n\t-n\tnever display the variable name;\n";
#line 139
  s3 = "\t-P\tdisplay this string after the variable name;\n\t-p\tdisplay this string before the variable name;\n\t-S\tquote the values suitably for the Bourne shell;\n\t-s\tspecify the configuration section to read;\n\t-T\tlist the available configuration file types;\n\t-t\tspecify the configuration file type;\n\t-x\ttreat the match patterns as regular expressions;\n\t-V\tdisplay program version information and exit.";
#line 149
  if (error) {
    {
    {
#line 150
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s%s%s\n",
            s1, s2, s3);
    }
    {
#line 151
    exit(1);
    }
    }
  }
  {
  {
#line 153
  printf((char const   */* __restrict  */)"%s%s%s\n", s1, s2, s3);
  }
  }
#line 154
  return;
}
}
#line 166 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static void version(void) 
{ 
  char *__cil_tmp1 ;

  {
  {
  {
#line 169
  printf((char const   */* __restrict  */)"confget 1.02\n");
  }
  }
#line 170
  return;
}
}
#line 183 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int init(int argc , char * const  *argv ) 
{ 
  int bidx ;
  int ch ;
  int do_help ;
  int do_list ;
  int do_version ;
  int show_name ;
  int hide_name ;
  size_t i ;
  char const   *pcre_err ;
  int pcre_ofs ;
  size_t t ;
  void *tmp ;
  void *tmp___0 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;
  char *__cil_tmp28 ;
  char *__cil_tmp29 ;
  char *__cil_tmp30 ;
  char *__cil_tmp31 ;
  char *__cil_tmp32 ;
  char *__cil_tmp33 ;
  char *__cil_tmp34 ;

  {
  {
#line 194
  conffile = (FILE *)((void *)0);
#line 196
  manyvars = 0;
#line 196
  showvarname = manyvars;
#line 196
  Sflag = showvarname;
#line 196
  lflag = Sflag;
#line 196
  Lflag = lflag;
#line 196
  cflag = Lflag;
#line 197
  hide_name = 0;
#line 197
  show_name = hide_name;
#line 197
  do_version = show_name;
#line 197
  do_list = do_version;
#line 197
  do_help = do_list;
#line 198
  matchvalue = (char const   *)((void *)0);
#line 199
  output_postfix = "";
#line 199
  output_prefix = output_postfix;
  {
#line 200
  bidx = find_backend("ini");
  }
  }
#line 201
  if (bidx == -1) {
    {
    {
#line 202
    fputs((char const   */* __restrict  */)"INTERNAL ERROR: no \'ini\' backend\n",
          (FILE */* __restrict  */)stderr);
    }
    }
#line 203
    return (-1);
  }
  {
  {
#line 205
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 205
    ch = getopt(argc, argv, "cf:hLlm:NnP:p:Ss:Tt:xV");
    }
    }
#line 205
    if (! (ch != -1)) {
#line 205
      goto while_break;
    }
    {
#line 207
    if (ch == 99) {
#line 207
      goto case_99;
    }
#line 212
    if (ch == 102) {
#line 212
      goto case_102;
    }
#line 216
    if (ch == 104) {
#line 216
      goto case_104;
    }
#line 220
    if (ch == 76) {
#line 220
      goto case_76;
    }
#line 226
    if (ch == 108) {
#line 226
      goto case_108;
    }
#line 232
    if (ch == 109) {
#line 232
      goto case_109;
    }
#line 236
    if (ch == 78) {
#line 236
      goto case_78;
    }
#line 240
    if (ch == 110) {
#line 240
      goto case_110;
    }
#line 244
    if (ch == 80) {
#line 244
      goto case_80;
    }
#line 248
    if (ch == 112) {
#line 248
      goto case_112;
    }
#line 252
    if (ch == 83) {
#line 252
      goto case_83;
    }
#line 256
    if (ch == 115) {
#line 256
      goto case_115;
    }
#line 260
    if (ch == 84) {
#line 260
      goto case_84;
    }
#line 264
    if (ch == 116) {
#line 264
      goto case_116;
    }
#line 273
    if (ch == 120) {
#line 273
      goto case_120;
    }
#line 281
    if (ch == 86) {
#line 281
      goto case_86;
    }
#line 286
    goto switch_default;
    case_99: /* CIL Label */ 
#line 208
    cflag = 1;
#line 209
    manyvars = 0;
#line 210
    goto switch_break;
    case_102: /* CIL Label */ 
#line 213
    filename = (char const   *)optarg;
#line 214
    goto switch_break;
    case_104: /* CIL Label */ 
#line 217
    do_help = 1;
#line 218
    goto switch_break;
    case_76: /* CIL Label */ 
#line 221
    Lflag = 1;
#line 222
    showvarname = 1;
#line 223
    manyvars = 1;
#line 224
    goto switch_break;
    case_108: /* CIL Label */ 
#line 227
    lflag = 1;
#line 228
    showvarname = 1;
#line 229
    manyvars = 1;
#line 230
    goto switch_break;
    case_109: /* CIL Label */ 
#line 233
    matchvalue = (char const   *)optarg;
#line 234
    goto switch_break;
    case_78: /* CIL Label */ 
#line 237
    show_name = 1;
#line 238
    goto switch_break;
    case_110: /* CIL Label */ 
#line 241
    hide_name = 1;
#line 242
    goto switch_break;
    case_80: /* CIL Label */ 
#line 245
    output_postfix = (char const   *)optarg;
#line 246
    goto switch_break;
    case_112: /* CIL Label */ 
#line 249
    output_prefix = (char const   *)optarg;
#line 250
    goto switch_break;
    case_83: /* CIL Label */ 
#line 253
    Sflag = 1;
#line 254
    goto switch_break;
    case_115: /* CIL Label */ 
#line 257
    section = (char const   *)optarg;
#line 258
    goto switch_break;
    case_84: /* CIL Label */ 
#line 261
    do_list = 1;
#line 262
    goto switch_break;
    case_116: /* CIL Label */ 
    {
    {
#line 265
    bidx = find_backend((char const   *)optarg);
    }
    }
#line 266
    if (bidx == -1) {
      {
      {
#line 267
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"No backend \'%s\'\n",
              optarg);
      }
      }
#line 269
      return (-1);
    }
#line 271
    goto switch_break;
    case_120: /* CIL Label */ 
#line 275
    xflag = 1;
#line 276
    goto switch_break;
    case_86: /* CIL Label */ 
#line 282
    do_version = 1;
#line 283
    goto switch_break;
    switch_default: /* CIL Label */ 
    {
    {
#line 287
    usage(1);
    }
    }
#line 288
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 292
  if (do_help) {
    {
    {
#line 293
    usage(0);
    }
    }
  }
#line 294
  if (do_version) {
    {
    {
#line 295
    version();
    }
    }
  }
#line 296
  if (do_list) {
    {
    {
#line 297
    printf((char const   */* __restrict  */)"Supported backends:");
    }
#line 298
    i = (size_t )0;
    }
    {
    {
#line 298
    while (1) {
      while_continue___3: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
#line 298
      if (! ((unsigned long )i < sizeof(backends) / sizeof(backends[0]))) {
#line 298
        goto while_break___0;
      }
      {
      {
#line 299
      printf((char const   */* __restrict  */)" %s", (backends[i])->name);
      }
#line 298
      i ++;
      }
    }
    while_break___3: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
    {
    {
#line 300
    puts("");
    }
    }
  }
#line 302
  if (do_help) {
    {
    {
#line 303
    exit(0);
    }
    }
  } else
#line 302
  if (do_list) {
    {
    {
#line 303
    exit(0);
    }
    }
  } else
#line 302
  if (do_version) {
    {
    {
#line 303
    exit(0);
    }
    }
  }
#line 305
  argc -= optind;
#line 306
  argv += optind;
#line 307
  if (cflag) {
#line 307
    if (lflag) {
      {
      {
#line 308
      warnx("The -c flag may not be used with -l or -L");
      }
      }
#line 309
      return (-1);
    } else
#line 307
    if (Lflag) {
      {
      {
#line 308
      warnx("The -c flag may not be used with -l or -L");
      }
      }
#line 309
      return (-1);
    }
  }
#line 311
  if (argc == 0) {
#line 311
    if (! lflag) {
      {
      {
#line 312
      warnx("No matching criteria specified");
      }
      }
#line 313
      return (-1);
    } else {
#line 311
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
#line 314
  if (argc > 0) {
#line 314
    if (lflag) {
      {
      {
#line 315
      warnx("Too many matching criteria specified");
      }
      }
#line 316
      return (-1);
    }
  }
#line 318
  if (argc > 1) {
#line 318
    if (! lflag) {
#line 319
      showvarname = 1;
#line 320
      manyvars = 1;
    }
  }
#line 322
  if (show_name) {
#line 323
    if (hide_name) {
      {
      {
#line 324
      warnx("The -N and -n flags may not be used together");
      }
      }
#line 325
      return (-1);
    }
#line 327
    showvarname = 1;
  } else
#line 328
  if (hide_name) {
#line 329
    showvarname = 0;
  }
#line 331
  margc = argc;
#line 332
  margv = argv;
#line 335
  if (xflag) {
#line 336
    if (matchvalue) {
      {
      {
#line 337
      x_matchvalue = pcre_compile(matchvalue, 0, & pcre_err, & pcre_ofs, (unsigned char const   *)((void *)0));
      }
      }
#line 339
      if ((unsigned long )pcre_err != (unsigned long )((void *)0)) {
        {
        {
#line 340
        errx(1, "Invalid match value: %s", pcre_err);
        }
        }
      }
      {
      {
#line 341
      x_matchvalue_extra = pcre_study((pcre const   *)x_matchvalue, 0, & pcre_err);
      }
      }
#line 343
      if ((unsigned long )pcre_err != (unsigned long )((void *)0)) {
        {
        {
#line 344
        errx(1, "Invalid match value: %s", pcre_err);
        }
        }
      }
    } else {
#line 346
      x_matchvalue = (pcre *)((void *)0);
    }
    {
    {
#line 348
    tmp = malloc((size_t )((unsigned long )margc * sizeof(*x_margv)));
    }
#line 348
    x_margv = (pcre **)tmp;
    }
#line 349
    if ((unsigned long )x_margv == (unsigned long )((void *)0)) {
      {
      {
#line 350
      errx(1, "Could not allocate memory");
      }
      }
    }
    {
    {
#line 351
    tmp___0 = malloc((size_t )((unsigned long )margc * sizeof(*x_margv_extra)));
    }
#line 351
    x_margv_extra = (pcre_extra **)tmp___0;
    }
#line 352
    if ((unsigned long )x_margv_extra == (unsigned long )((void *)0)) {
      {
      {
#line 353
      errx(1, "Could not allocate memory");
      }
      }
    }
#line 354
    t = (size_t )0;
    {
    {
#line 354
    while (1) {
      while_continue___4: /* CIL Label */ ;
      while_continue___1: /* CIL Label */ ;
#line 354
      if (! (t < (size_t )margc)) {
#line 354
        goto while_break___1;
      }
      {
      {
#line 355
      *(x_margv + t) = pcre_compile((char const   *)*(margv + t), 0, & pcre_err, & pcre_ofs,
                                    (unsigned char const   *)((void *)0));
      }
      }
#line 357
      if ((unsigned long )pcre_err != (unsigned long )((void *)0)) {
        {
        {
#line 358
        errx(1, "Invalid match pattern: %s", pcre_err);
        }
        }
      }
      {
      {
#line 359
      *(x_margv_extra + t) = pcre_study((pcre const   *)*(x_margv + t), 0, & pcre_err);
      }
      }
#line 361
      if ((unsigned long )pcre_err != (unsigned long )((void *)0)) {
        {
        {
#line 362
        errx(1, "Invalid match pattern: %s", pcre_err);
        }
        }
      }
#line 354
      t ++;
    }
    while_break___4: /* CIL Label */ ;
    }
    while_break___1: /* CIL Label */ ;
    }
  }
#line 367
  backend = backends[bidx];
#line 368
  return (0);
}
}
#line 381 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int find_backend(char const   *name ) 
{ 
  size_t i ;
  size_t len ;
  int tentative ;
  int tmp ;

  {
  {
  {
#line 387
  len = strlen(name);
  }
#line 388
  i = (size_t )0;
#line 388
  tentative = -1;
  }
  {
  {
#line 388
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 388
    if (! ((unsigned long )i < sizeof(backends) / sizeof(backends[0]))) {
#line 388
      goto while_break;
    }
    {
    {
#line 389
    tmp = strncmp(name, (backends[i])->name, len);
    }
    }
#line 389
    if (tmp) {
#line 390
      goto __Cont;
    }
#line 391
    if ((int const   )*((backends[i])->name + len) == 0) {
#line 392
      return ((int )i);
    }
#line 393
    if (tentative >= 0) {
#line 394
      return (-1);
    }
#line 395
    tentative = (int )i;
    __Cont: /* CIL Label */ 
#line 388
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 397
  return (tentative);
}
}
#line 410 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int openfile(void) 
{ 
  int tmp ;
  char *__cil_tmp2 ;

  {
#line 413
  if ((unsigned long )backend->openfile == (unsigned long )((void *)0)) {
    {
    {
#line 414
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"INTERNAL ERROR: backend \'%s\' does not define a openfile routine\n",
            backend->name);
    }
    }
#line 417
    return (-1);
  }
  {
  {
#line 419
  tmp = (*(backend->openfile))();
  }
  }
#line 419
  return (tmp);
}
}
#line 432 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int readfile(void) 
{ 
  int tmp ;
  char *__cil_tmp2 ;

  {
#line 436
  if ((unsigned long )backend->readfile == (unsigned long )((void *)0)) {
    {
    {
#line 437
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"INTERNAL ERROR: backend \'%s\' does not define a readfile routine\n",
            backend->name);
    }
    }
#line 440
    return (-1);
  }
  {
  {
#line 442
  tmp = (*(backend->readfile))();
  }
  }
#line 442
  return (tmp);
}
}
#line 455 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
static int closefile(void) 
{ 
  int tmp ;
  char *__cil_tmp2 ;

  {
#line 459
  if ((unsigned long )backend->closefile == (unsigned long )((void *)0)) {
    {
    {
#line 460
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"INTERNAL ERROR: backend \'%s\' does not define a closefile routine\n",
            backend->name);
    }
    }
#line 463
    return (-1);
  }
  {
  {
#line 465
  tmp = (*(backend->closefile))();
  }
  }
#line 465
  return (tmp);
}
}
#line 481 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
int foundvar(char const   *sec  __attribute__((__unused__)) , char const   *name ,
             char const   *value ) 
{ 
  int i ;
  int r ;
  size_t tmp ;
  int tmp___0 ;
  int tmp___1 ;
  size_t tmp___2 ;
  int tmp___3 ;
  char const   *p ;
  char const   *tmp___4 ;
  char const   *tmp___5 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;

  {
#line 490
  if (! lflag) {
#line 491
    i = 0;
    {
    {
#line 491
    while (1) {
      while_continue___3: /* CIL Label */ ;
      while_continue: /* CIL Label */ ;
#line 491
      if (! (i < margc)) {
#line 491
        goto while_break;
      }
#line 492
      if (Lflag) {
#line 494
        if (xflag) {
          {
          {
#line 495
          tmp = strlen(name);
          }
          {
#line 495
          r = pcre_exec((pcre const   *)*(x_margv + i), (pcre_extra const   *)*(x_margv_extra + i),
                        name, (int )tmp, 0, 0, (int *)((void *)0), 0);
          }
          }
#line 498
          if (r == 0) {
#line 499
            goto while_break;
          }
#line 500
          if (r != -1) {
            {
            {
#line 501
            errx(1, "Could not match \'%s\' against the \'%s\' pattern", name, *(margv + i));
            }
            }
          }
        } else {
          {
          {
#line 504
          tmp___0 = fnmatch((char const   *)*(margv + i), name, 0);
          }
          }
#line 504
          if (tmp___0 == 0) {
#line 505
            goto while_break;
          }
        }
      } else {
        {
        {
#line 507
        tmp___1 = strcmp(name, (char const   *)*(margv + i));
        }
        }
#line 507
        if (! tmp___1) {
#line 508
          goto while_break;
        }
      }
#line 491
      i ++;
    }
    while_break___3: /* CIL Label */ ;
    }
    while_break: /* CIL Label */ ;
    }
#line 510
    if (i == margc) {
#line 511
      morevars = 1;
#line 512
      return (0);
    }
  }
#line 516
  if ((unsigned long )matchvalue != (unsigned long )((void *)0)) {
#line 517
    i = 1;
#line 519
    if (xflag) {
      {
      {
#line 520
      tmp___2 = strlen(value);
      }
      {
#line 520
      r = pcre_exec((pcre const   *)x_matchvalue, (pcre_extra const   *)x_matchvalue_extra,
                    value, (int )tmp___2, 0, 0, (int *)((void *)0), 0);
      }
      }
#line 522
      if (r == -1) {
#line 523
        i = 0;
      } else
#line 524
      if (r != 0) {
        {
        {
#line 525
        errx(1, "Could not match \'%s\' against the \'%s\' pattern", value, *(margv + i));
        }
        }
      }
    } else {
      {
      {
#line 528
      tmp___3 = fnmatch(matchvalue, value, 0);
      }
      }
#line 528
      if (tmp___3 == 1) {
#line 529
        i = 0;
      }
    }
#line 531
    if (i == 0) {
#line 532
      morevars = 1;
#line 533
      return (0);
    }
  }
#line 536
  if (cflag) {
#line 537
    cfound = 1;
#line 538
    morevars = 0;
  } else {
#line 540
    if (showvarname) {
      {
      {
#line 541
      printf((char const   */* __restrict  */)"%s%s%s=", output_prefix, name, output_postfix);
      }
      }
    }
#line 542
    if (! Sflag) {
      {
      {
#line 543
      printf((char const   */* __restrict  */)"%s\n", value);
      }
      }
    } else {
      {
      {
#line 547
      printf((char const   */* __restrict  */)"\'");
      }
#line 548
      p = value;
      }
      {
      {
#line 549
      while (1) {
        while_continue___4: /* CIL Label */ ;
        while_continue___0: /* CIL Label */ ;
#line 549
        if (! *p) {
#line 549
          goto while_break___0;
        }
        {
        {
#line 550
        while (1) {
          while_continue___5: /* CIL Label */ ;
          while_continue___1: /* CIL Label */ ;
#line 550
          if (*p) {
#line 550
            if (! ((int const   )*p != 39)) {
#line 550
              goto while_break___1;
            }
          } else {
#line 550
            goto while_break___1;
          }
          {
#line 551
          tmp___4 = p;
#line 551
          p ++;
          {
#line 551
          putchar((int )*tmp___4);
          }
          }
        }
        while_break___5: /* CIL Label */ ;
        }
        while_break___1: /* CIL Label */ ;
        }
#line 552
        if ((int const   )*p == 0) {
#line 553
          goto while_break___0;
        }
        {
        {
#line 554
        printf((char const   */* __restrict  */)"\'\"");
        }
        }
        {
        {
#line 555
        while (1) {
          while_continue___6: /* CIL Label */ ;
          while_continue___2: /* CIL Label */ ;
#line 555
          if (! ((int const   )*p == 39)) {
#line 555
            goto while_break___2;
          }
          {
#line 556
          tmp___5 = p;
#line 556
          p ++;
          {
#line 556
          putchar((int )*tmp___5);
          }
          }
        }
        while_break___6: /* CIL Label */ ;
        }
        while_break___2: /* CIL Label */ ;
        }
        {
        {
#line 557
        printf((char const   */* __restrict  */)"\"\'");
        }
        }
      }
      while_break___4: /* CIL Label */ ;
      }
      while_break___0: /* CIL Label */ ;
      }
      {
      {
#line 559
      printf((char const   */* __restrict  */)"\'\n");
      }
      }
    }
#line 561
    morevars = manyvars;
  }
#line 563
  return (0);
}
}
#line 569 "/home/wslee/benchmarks/textformat/confget-1.02/confget.c"
int main(int argc , char * const  *argv ) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  {
  {
#line 573
  tmp = init(argc, argv);
  }
  }
#line 573
  if (tmp == -1) {
#line 574
    return (1);
  }
  {
#line 576
  cfound = 0;
  {
#line 577
  tmp___0 = openfile();
  }
  }
#line 577
  if (tmp___0 == -1) {
#line 578
    return (1);
  }
  {
  {
#line 579
  tmp___1 = readfile();
  }
  }
#line 579
  if (tmp___1 == -1) {
    {
    {
#line 580
    closefile();
    }
    }
#line 581
    return (1);
  }
  {
  {
#line 583
  tmp___2 = closefile();
  }
  }
#line 583
  if (tmp___2 == -1) {
#line 584
    return (1);
  }
#line 586
  if (cflag) {
#line 587
    return (! cfound);
  }
#line 588
  return (0);
}
}
