/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 64 "/usr/include/bits/mathcalls.h"
extern  __attribute__((__nothrow__)) double cos(double __x ) ;
#line 147 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 819
extern void perror(char const   *__s ) ;
#line 73 "/usr/include/fcntl.h"
extern int ( __attribute__((__nonnull__(1))) open)(char const   *__file , int __oflag 
                                                   , ...) ;
#line 51 "/usr/include/malloc.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 17 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void gen_costab(void) ;
#line 18
void dial_digit(int c ) ;
#line 19
void silent(int msec ) ;
#line 20
void dial(int f1 , int f2 , int msec ) ;
#line 22 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
char *output  =    (char *)"/dev/dsp";
#line 23 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int bits  =    8;
#line 24 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int speed  =    8000;
#line 25 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int tone_time  =    100;
#line 26 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int silent_time  =    50;
#line 27 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int sleep_time  =    500;
#line 28 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int volume  =    100;
#line 29 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int format  =    8;
#line 30 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int use_audio  =    1;
#line 34 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
unsigned char *buf  ;
#line 35 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int bufsize  =    4096;
#line 36 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int bufidx  ;
#line 40 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
short *costab  ;
#line 41 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int tabsize  =    256;
#line 43 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int dialed  =    0;
#line 45 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int right  =    0;
#line 46 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int left  =    0;
#line 48 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
int fd  ;
#line 71
extern int ( /* missing proto */  exit)() ;
#line 50 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void Usage(void) 
{ 
  char *__cil_tmp1 ;

  {
  {
  {
#line 52
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"usage: dial [options] number ...\n Valid options with their default values are:\n   Duration options:\n     --tone-time   100\n     --silent-time 50\n     --sleep-time  500\n   Audio output  options:\n     --output-dev  /dev/dsp\n     --use-audio   1\n     --bufsize     4096\n     --speed       8000\n     --bits        8\n   Audio generation options:\n     --table-size  256\n     --volume      100\n     --left        0\n     --right       0\n");
  }
  {
#line 71
  exit(1);
  }
  }
}
}
#line 86
extern int ( /* missing proto */  ioctl)() ;
#line 74 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void initialize_audiodev(void) 
{ 
  int speed_local ;
  int channels ;
  int diff ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;

  {
#line 76
  speed_local = speed;
#line 77
  channels = 1;
#line 80
  if (! use_audio) {
#line 81
    return;
  }
#line 83
  if (right) {
#line 84
    channels = 2;
  } else
#line 83
  if (left) {
#line 84
    channels = 2;
  }
  {
  {
#line 86
  tmp = ioctl(fd, (unsigned long )(((3U << 30) | (unsigned int )(80 << 8)) | 6U) | (sizeof(int ) << 16),
              & channels);
  }
  }
#line 86
  if (tmp) {
    {
    {
#line 87
    perror("ioctl(SNDCTL_DSP_CHANNELS)");
    }
    {
#line 88
    exit(1);
    }
    }
  }
  {
  {
#line 91
  tmp___0 = ioctl(fd, (unsigned long )(((3U << 30) | (unsigned int )(80 << 8)) | 5U) | (sizeof(int ) << 16),
                  & format);
  }
  }
#line 91
  if (tmp___0) {
    {
    {
#line 92
    perror("ioctl(SNDCTL_DSP_SPEED)");
    }
    {
#line 93
    exit(1);
    }
    }
  }
  {
  {
#line 96
  tmp___1 = ioctl(fd, (unsigned long )(((3U << 30) | (unsigned int )(80 << 8)) | 2U) | (sizeof(int ) << 16),
                  & speed_local);
  }
  }
#line 96
  if (tmp___1) {
    {
    {
#line 97
    perror("ioctl(SNDCTL_DSP_SPEED)");
    }
    {
#line 98
    exit(1);
    }
    }
  }
#line 101
  diff = speed_local - speed;
#line 102
  if (diff < 0) {
#line 103
    diff = - diff;
  }
#line 104
  if (diff > 500) {
    {
    {
#line 105
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Your sound card does not support the requested speed\n");
    }
    {
#line 107
    exit(1);
    }
    }
  }
#line 109
  if (diff != 0) {
    {
    {
#line 110
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Setting speed to %d\n",
            speed_local);
    }
    }
  }
#line 113
  speed = speed_local;
#line 114
  return;
}
}
#line 123
extern int ( /* missing proto */  atoi)() ;
#line 116 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void getvalue(int *arg , int *index , int argc , char **argv , int min , int max ) 
{ 
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;

  {
#line 120
  if (*index >= argc - 1) {
    {
    {
#line 121
    Usage();
    }
    }
  }
  {
  {
#line 123
  *arg = atoi(*(argv + (1 + *index)));
  }
  }
#line 125
  if (*arg < min) {
    {
    {
#line 126
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Value for %s should be in the range %d..%d\n",
            *(argv + *index) + 2, min, max);
    }
    {
#line 128
    exit(1);
    }
    }
  } else
#line 125
  if (*arg > max) {
    {
    {
#line 126
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Value for %s should be in the range %d..%d\n",
            *(argv + *index) + 2, min, max);
    }
    {
#line 128
    exit(1);
    }
    }
  }
#line 130
  (*index) ++;
#line 131
  return;
}
}
#line 192
extern int ( /* missing proto */  strcmp)() ;
#line 264
extern int ( /* missing proto */  write)() ;
#line 133 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void main(int argc , char **argv ) 
{ 
  char *cp ;
  int i ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;
  int tmp___12 ;
  void *tmp___13 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;
  char *__cil_tmp28 ;
  char *__cil_tmp29 ;
  char *__cil_tmp30 ;
  char *__cil_tmp31 ;
  char *__cil_tmp32 ;
  char *__cil_tmp33 ;
  char *__cil_tmp34 ;
  char *__cil_tmp35 ;

  {
#line 139
  i = 1;
  {
  {
#line 139
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 139
    if (! (i < argc)) {
#line 139
      goto while_break;
    }
#line 140
    if ((int )*(*(argv + i) + 0) != 45) {
#line 142
      goto while_break;
    } else
#line 140
    if ((int )*(*(argv + i) + 1) != 45) {
#line 142
      goto while_break;
    }
    {
    {
#line 144
    tmp___11 = strcmp(*(argv + i), "--table-size");
    }
    }
#line 144
    if (tmp___11) {
      {
      {
#line 148
      tmp___10 = strcmp(*(argv + i), "--tone-time");
      }
      }
#line 148
      if (tmp___10) {
        {
        {
#line 152
        tmp___9 = strcmp(*(argv + i), "--sleep-time");
        }
        }
#line 152
        if (tmp___9) {
          {
          {
#line 156
          tmp___8 = strcmp(*(argv + i), "--silent-time");
          }
          }
#line 156
          if (tmp___8) {
            {
            {
#line 160
            tmp___7 = strcmp(*(argv + i), "--sleep-time");
            }
            }
#line 160
            if (tmp___7) {
              {
              {
#line 164
              tmp___6 = strcmp(*(argv + i), "--volume");
              }
              }
#line 164
              if (tmp___6) {
                {
                {
#line 168
                tmp___5 = strcmp(*(argv + i), "--speed");
                }
                }
#line 168
                if (tmp___5) {
                  {
                  {
#line 172
                  tmp___4 = strcmp(*(argv + i), "--bits");
                  }
                  }
#line 172
                  if (tmp___4) {
                    {
                    {
#line 176
                    tmp___3 = strcmp(*(argv + i), "--bufsize");
                    }
                    }
#line 176
                    if (tmp___3) {
                      {
                      {
#line 180
                      tmp___2 = strcmp(*(argv + i), "--use-audio");
                      }
                      }
#line 180
                      if (tmp___2) {
                        {
                        {
#line 184
                        tmp___1 = strcmp(*(argv + i), "--right");
                        }
                        }
#line 184
                        if (tmp___1) {
                          {
                          {
#line 188
                          tmp___0 = strcmp(*(argv + i), "--left");
                          }
                          }
#line 188
                          if (tmp___0) {
                            {
                            {
#line 192
                            tmp = strcmp(*(argv + i), "--output-dev");
                            }
                            }
#line 192
                            if (tmp) {
                              {
                              {
#line 199
                              Usage();
                              }
                              }
                            } else {
#line 193
                              i ++;
#line 194
                              if (i >= argc) {
                                {
                                {
#line 195
                                Usage();
                                }
                                }
                              }
#line 196
                              output = *(argv + i);
                            }
                          } else {
                            {
                            {
#line 189
                            getvalue(& left, & i, argc, argv, 0, 1);
                            }
                            }
                          }
                        } else {
                          {
                          {
#line 185
                          getvalue(& right, & i, argc, argv, 0, 1);
                          }
                          }
                        }
                      } else {
                        {
                        {
#line 181
                        getvalue(& use_audio, & i, argc, argv, 0, 1);
                        }
                        }
                      }
                    } else {
                      {
                      {
#line 177
                      getvalue(& bufsize, & i, argc, argv, 4, 65536);
                      }
                      }
                    }
                  } else {
                    {
                    {
#line 173
                    getvalue(& bits, & i, argc, argv, 8, 16);
                    }
                    }
                  }
                } else {
                  {
                  {
#line 169
                  getvalue(& speed, & i, argc, argv, 5000, 48000);
                  }
                  }
                }
              } else {
                {
                {
#line 165
                getvalue(& volume, & i, argc, argv, 0, 100);
                }
                }
              }
            } else {
              {
              {
#line 161
              getvalue(& sleep_time, & i, argc, argv, 10, 100000);
              }
              }
            }
          } else {
            {
            {
#line 157
            getvalue(& silent_time, & i, argc, argv, 10, 10000);
            }
            }
          }
        } else {
          {
          {
#line 153
          getvalue(& sleep_time, & i, argc, argv, 10, 10000);
          }
          }
        }
      } else {
        {
        {
#line 149
        getvalue(& tone_time, & i, argc, argv, 10, 10000);
        }
        }
      }
    } else {
      {
      {
#line 145
      getvalue(& tabsize, & i, argc, argv, 2, 65536);
      }
      }
    }
#line 139
    i ++;
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 202
  if (i >= argc) {
    {
    {
#line 203
    Usage();
    }
    }
  }
  {
  {
#line 205
  tmp___12 = strcmp(output, "-");
  }
  }
#line 205
  if (tmp___12) {
    {
    {
#line 208
    fd = open((char const   *)output, 577, 420);
    }
    }
#line 209
    if (fd < 0) {
      {
      {
#line 210
      perror((char const   *)output);
      }
      {
#line 211
      exit(1);
      }
      }
    }
  } else {
#line 206
    fd = 1;
  }
  {
#line 216
  if (bits == 8) {
#line 216
    goto case_8;
  }
#line 219
  if (bits == 16) {
#line 219
    goto case_16;
  }
#line 222
  goto switch_default;
  case_8: /* CIL Label */ 
#line 217
  format = 8;
#line 218
  goto switch_break;
  case_16: /* CIL Label */ 
#line 220
  format = 16;
#line 221
  goto switch_break;
  switch_default: /* CIL Label */ 
  {
  {
#line 223
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Value for bits should be 8 or 16\n");
  }
  {
#line 224
  exit(1);
  }
  }
  switch_break: /* CIL Label */ ;
  }
  {
  {
#line 227
  initialize_audiodev();
  }
  {
#line 229
  gen_costab();
  }
  {
#line 230
  tmp___13 = malloc((size_t )bufsize);
  }
#line 230
  buf = (unsigned char *)tmp___13;
  }
#line 231
  if ((unsigned long )buf == (unsigned long )((void *)0)) {
    {
    {
#line 232
    perror("malloc buf");
    }
    {
#line 233
    exit(1);
    }
    }
  }
#line 236
  bufidx = 0;
  {
  {
#line 237
  while (1) {
    while_continue___3: /* CIL Label */ ;
    while_continue___0: /* CIL Label */ ;
#line 237
    if (! (i < argc)) {
#line 237
      goto while_break___0;
    }
#line 238
    cp = *(argv + i);
#line 239
    if (dialed) {
      {
      {
#line 240
      silent(sleep_time);
      }
      }
    }
    {
    {
#line 241
    while (1) {
      while_continue___4: /* CIL Label */ ;
      while_continue___1: /* CIL Label */ ;
#line 241
      if (cp) {
#line 241
        if (! *cp) {
#line 241
          goto while_break___1;
        }
      } else {
#line 241
        goto while_break___1;
      }
#line 242
      if ((int )*cp == 44) {
        {
        {
#line 243
        silent(sleep_time);
        }
        }
      } else
#line 242
      if ((int )*cp == 32) {
        {
        {
#line 243
        silent(sleep_time);
        }
        }
      } else {
#line 245
        if (dialed) {
          {
          {
#line 246
          silent(silent_time);
          }
          }
        }
        {
        {
#line 247
        dial_digit((int )*cp);
        }
        }
      }
#line 249
      cp ++;
    }
    while_break___4: /* CIL Label */ ;
    }
    while_break___1: /* CIL Label */ ;
    }
#line 237
    i ++;
  }
  while_break___3: /* CIL Label */ ;
  }
  while_break___0: /* CIL Label */ ;
  }
#line 252
  if (bufidx > 0) {
    {
    {
#line 264
    write(fd, buf, bufidx);
    }
    }
  }
  {
  {
#line 266
  exit(0);
  }
  }
}
}
#line 269 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void dial_digit(int c ) 
{ 


  {
  {
#line 273
  if (c == 48) {
#line 273
    goto case_48;
  }
#line 276
  if (c == 49) {
#line 276
    goto case_49;
  }
#line 279
  if (c == 50) {
#line 279
    goto case_50;
  }
#line 282
  if (c == 51) {
#line 282
    goto case_51;
  }
#line 285
  if (c == 52) {
#line 285
    goto case_52;
  }
#line 288
  if (c == 53) {
#line 288
    goto case_53;
  }
#line 291
  if (c == 54) {
#line 291
    goto case_54;
  }
#line 294
  if (c == 55) {
#line 294
    goto case_55;
  }
#line 297
  if (c == 56) {
#line 297
    goto case_56;
  }
#line 300
  if (c == 57) {
#line 300
    goto case_57;
  }
#line 303
  if (c == 42) {
#line 303
    goto case_42;
  }
#line 306
  if (c == 35) {
#line 306
    goto case_35;
  }
#line 309
  if (c == 65) {
#line 309
    goto case_65;
  }
#line 312
  if (c == 66) {
#line 312
    goto case_66;
  }
#line 315
  if (c == 67) {
#line 315
    goto case_67;
  }
#line 318
  if (c == 68) {
#line 318
    goto case_68;
  }
#line 272
  goto switch_break;
  case_48: /* CIL Label */ 
  {
  {
#line 274
  dial(941, 1336, tone_time);
  }
  }
#line 275
  goto switch_break;
  case_49: /* CIL Label */ 
  {
  {
#line 277
  dial(697, 1209, tone_time);
  }
  }
#line 278
  goto switch_break;
  case_50: /* CIL Label */ 
  {
  {
#line 280
  dial(697, 1336, tone_time);
  }
  }
#line 281
  goto switch_break;
  case_51: /* CIL Label */ 
  {
  {
#line 283
  dial(697, 1477, tone_time);
  }
  }
#line 284
  goto switch_break;
  case_52: /* CIL Label */ 
  {
  {
#line 286
  dial(770, 1209, tone_time);
  }
  }
#line 287
  goto switch_break;
  case_53: /* CIL Label */ 
  {
  {
#line 289
  dial(770, 1336, tone_time);
  }
  }
#line 290
  goto switch_break;
  case_54: /* CIL Label */ 
  {
  {
#line 292
  dial(770, 1477, tone_time);
  }
  }
#line 293
  goto switch_break;
  case_55: /* CIL Label */ 
  {
  {
#line 295
  dial(852, 1209, tone_time);
  }
  }
#line 296
  goto switch_break;
  case_56: /* CIL Label */ 
  {
  {
#line 298
  dial(852, 1336, tone_time);
  }
  }
#line 299
  goto switch_break;
  case_57: /* CIL Label */ 
  {
  {
#line 301
  dial(852, 1477, tone_time);
  }
  }
#line 302
  goto switch_break;
  case_42: /* CIL Label */ 
  {
  {
#line 304
  dial(941, 1209, tone_time);
  }
  }
#line 305
  goto switch_break;
  case_35: /* CIL Label */ 
  {
  {
#line 307
  dial(941, 1477, tone_time);
  }
  }
#line 308
  goto switch_break;
  case_65: /* CIL Label */ 
  {
  {
#line 310
  dial(697, 1633, tone_time);
  }
  }
#line 311
  goto switch_break;
  case_66: /* CIL Label */ 
  {
  {
#line 313
  dial(770, 1633, tone_time);
  }
  }
#line 314
  goto switch_break;
  case_67: /* CIL Label */ 
  {
  {
#line 316
  dial(852, 1633, tone_time);
  }
  }
#line 317
  goto switch_break;
  case_68: /* CIL Label */ 
  {
  {
#line 319
  dial(941, 1633, tone_time);
  }
  }
#line 320
  goto switch_break;
  switch_break: /* CIL Label */ ;
  }
#line 322
  return;
}
}
#line 324 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void silent(int msec ) 
{ 
  int time ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;

  {
#line 327
  if (msec <= 0) {
#line 328
    return;
  }
#line 332
  time = (msec * speed) / 1000;
  {
  {
#line 333
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 333
    time --;
#line 333
    if (! (time >= 0)) {
#line 333
      goto while_break;
    }
#line 334
    if (format == 8) {
#line 335
      tmp = bufidx;
#line 335
      bufidx ++;
#line 335
      *(buf + tmp) = (unsigned char)128;
    } else {
#line 338
      tmp___0 = bufidx;
#line 338
      bufidx ++;
#line 338
      *(buf + tmp___0) = (unsigned char)0;
#line 339
      tmp___1 = bufidx;
#line 339
      bufidx ++;
#line 339
      *(buf + tmp___1) = (unsigned char)0;
    }
#line 341
    if (right) {
#line 341
      goto _L;
    } else
#line 341
    if (left) {
      _L: /* CIL Label */ 
#line 342
      if (format == 8) {
#line 343
        tmp___2 = bufidx;
#line 343
        bufidx ++;
#line 343
        *(buf + tmp___2) = (unsigned char)128;
      } else {
#line 346
        tmp___3 = bufidx;
#line 346
        bufidx ++;
#line 346
        *(buf + tmp___3) = (unsigned char)0;
#line 347
        tmp___4 = bufidx;
#line 347
        bufidx ++;
#line 347
        *(buf + tmp___4) = (unsigned char)0;
      }
    }
#line 350
    if (bufidx >= bufsize) {
      {
      {
#line 351
      write(fd, buf, bufsize);
      }
#line 352
      bufidx = 0;
      }
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 355
  dialed = 0;
#line 356
  return;
}
}
#line 358 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void dial(int f1 , int f2 , int msec ) 
{ 
  int i1 ;
  int i2 ;
  int d1 ;
  int d2 ;
  int e1 ;
  int e2 ;
  int g1 ;
  int g2 ;
  int time ;
  int val ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;

  {
#line 364
  if (msec <= 0) {
#line 365
    return;
  }
#line 369
  f1 *= tabsize;
#line 370
  f2 *= tabsize;
#line 371
  d1 = f1 / speed;
#line 372
  d2 = f2 / speed;
#line 373
  g1 = f1 - d1 * speed;
#line 374
  g2 = f2 - d2 * speed;
#line 375
  e1 = speed / 2;
#line 376
  e2 = speed / 2;
#line 378
  i2 = 0;
#line 378
  i1 = i2;
#line 380
  time = (msec * speed) / 1000;
  {
  {
#line 381
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 381
    time --;
#line 381
    if (! (time >= 0)) {
#line 381
      goto while_break;
    }
#line 382
    val = (int )*(costab + i1) + (int )*(costab + i2);
#line 384
    if (left) {
#line 384
      goto _L;
    } else
#line 384
    if (! right) {
      _L: /* CIL Label */ 
#line 385
      if (format == 8) {
#line 386
        tmp = bufidx;
#line 386
        bufidx ++;
#line 386
        *(buf + tmp) = (unsigned char )(128 + (val >> 8));
      } else {
#line 389
        tmp___0 = bufidx;
#line 389
        bufidx ++;
#line 389
        *(buf + tmp___0) = (unsigned char )(val & 255);
#line 390
        tmp___1 = bufidx;
#line 390
        bufidx ++;
#line 390
        *(buf + tmp___1) = (unsigned char )((val >> 8) & 255);
      }
    }
#line 393
    if (left != right) {
#line 394
      if (format == 8) {
#line 395
        tmp___2 = bufidx;
#line 395
        bufidx ++;
#line 395
        *(buf + tmp___2) = (unsigned char)128;
      } else {
#line 398
        tmp___3 = bufidx;
#line 398
        bufidx ++;
#line 398
        *(buf + tmp___3) = (unsigned char)0;
#line 399
        tmp___4 = bufidx;
#line 399
        bufidx ++;
#line 399
        *(buf + tmp___4) = (unsigned char)0;
      }
    }
#line 402
    if (right) {
#line 403
      if (format == 8) {
#line 404
        tmp___5 = bufidx;
#line 404
        bufidx ++;
#line 404
        *(buf + tmp___5) = (unsigned char )(128 + (val >> 8));
      } else {
#line 407
        tmp___6 = bufidx;
#line 407
        bufidx ++;
#line 407
        *(buf + tmp___6) = (unsigned char )(val & 255);
#line 408
        tmp___7 = bufidx;
#line 408
        bufidx ++;
#line 408
        *(buf + tmp___7) = (unsigned char )((val >> 8) & 255);
      }
    }
#line 412
    i1 += d1;
#line 413
    if (e1 < 0) {
#line 414
      e1 += speed;
#line 415
      i1 ++;
    }
#line 417
    if (i1 >= tabsize) {
#line 418
      i1 -= tabsize;
    }
#line 420
    i2 += d2;
#line 421
    if (e2 < 0) {
#line 422
      e2 += speed;
#line 423
      i2 ++;
    }
#line 425
    if (i2 >= tabsize) {
#line 426
      i2 -= tabsize;
    }
#line 428
    if (bufidx >= bufsize) {
      {
      {
#line 429
      write(fd, buf, bufsize);
      }
#line 430
      bufidx = 0;
      }
    }
#line 432
    e1 -= g1;
#line 433
    e2 -= g2;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 435
  dialed = 1;
#line 436
  return;
}
}
#line 438 "/home/wslee/benchmarks/sound/dtmfdial-0.2+1/dial.c"
void gen_costab(void) 
{ 
  int i ;
  double d ;
  void *tmp ;
  double tmp___0 ;
  char *__cil_tmp5 ;

  {
  {
  {
#line 443
  tmp = malloc((size_t )((unsigned long )tabsize * sizeof(short )));
  }
#line 443
  costab = (short *)tmp;
  }
#line 444
  if ((unsigned long )costab == (unsigned long )((void *)0)) {
    {
    {
#line 445
    perror("malloc costab");
    }
    {
#line 446
    exit(1);
    }
    }
  }
#line 449
  i = 0;
  {
  {
#line 449
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 449
    if (! (i < tabsize)) {
#line 449
      goto while_break;
    }
    {
#line 450
    d = ((double )2 * 3.14159265358979323846) * (double )i;
    {
#line 451
    tmp___0 = cos(d / (double )tabsize);
    }
#line 451
    *(costab + i) = (short )((int )((((double )volume / 100.) * 16383.) * tmp___0));
#line 449
    i ++;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 453
  return;
}
}
