/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 128 "/usr/include/dirent.h"
struct __dirstream;
#line 128 "/usr/include/dirent.h"
typedef struct __dirstream DIR;
#line 203 "/usr/include/sys/types.h"
typedef unsigned int u_int32_t;
#line 146 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 147
extern struct _IO_FILE *stderr ;
#line 214
extern int fclose(FILE *__stream ) ;
#line 219
extern int fflush(FILE *__stream ) ;
#line 249
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 339
extern int printf(char const   * __restrict  __format  , ...) ;
#line 341
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
#line 513
extern int fgetc(FILE *__stream ) ;
#line 520
extern int getchar(void) ;
#line 555
extern int fputc(int __c , FILE *__stream ) ;
#line 604
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream ) ;
#line 722
extern int fseek(FILE *__stream , long __off , int __whence ) ;
#line 727
extern long ftell(FILE *__stream ) ;
#line 819
extern void perror(char const   *__s ) ;
#line 471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 485
extern  __attribute__((__nothrow__)) void *( __attribute__((__warn_unused_result__)) realloc)(void *__ptr ,
                                                                                              size_t __size ) ;
#line 488
extern  __attribute__((__nothrow__)) void free(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 566
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) getenv)(char const   *__name ) ;
#line 712
extern int system(char const   *__command ) ;
#line 64 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1))) memset)(void *__s ,
                                                                                     int __c ,
                                                                                     size_t __n ) ;
#line 130
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strncpy)(char * __restrict  __dest ,
                                                                                        char const   * __restrict  __src ,
                                                                                        size_t __n ) ;
#line 138
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strncat)(char * __restrict  __dest ,
                                                                                        char const   * __restrict  __src ,
                                                                                        size_t __n ) ;
#line 340
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strstr)(char const   *__haystack ,
                                                                                       char const   *__needle )  __attribute__((__pure__)) ;
#line 397
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1))) strlen)(char const   *__s )  __attribute__((__pure__)) ;
#line 152 "/usr/include/getopt.h"
extern  __attribute__((__nothrow__)) int getopt(int ___argc , char * const  *___argv ,
                                                char const   *__shortopts ) ;
#line 135 "/usr/include/dirent.h"
extern DIR *( __attribute__((__nonnull__(1))) opendir)(char const   *__name ) ;
#line 33 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.h"
unsigned char charat(char *s , int pos ) ;
#line 35
unsigned long flength(FILE *in ) ;
#line 37
int getid3v1(FILE *file_input ) ;
#line 39
int cindexsize(int files , char **argv , short optoffset ) ;
#line 41
char *buildindex(char *wrapindex , int indexsize , int files , char **argv , short optoffset ,
                 unsigned long *splitpoints , short addoption , int oldfiles ) ;
#line 43
unsigned long getid3v2(FILE *in , unsigned long start ) ;
#line 45
unsigned long getword(FILE *in , unsigned long offset , int mode ) ;
#line 47
char **exchange(char **argv , int offset , int tot ) ;
#line 28 "/home/wslee/benchmarks/sound/mp3wrap-0.5/crc.h"
unsigned long c_crc(FILE *in , unsigned long begin , unsigned long end ) ;
#line 36 "/home/wslee/benchmarks/sound/mp3wrap-0.5/mp3wrap.c"
unsigned char id3[460]  = 
#line 36 "/home/wslee/benchmarks/sound/mp3wrap-0.5/mp3wrap.c"
  {      (unsigned char)73,      (unsigned char)68,      (unsigned char)51,      (unsigned char)3, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)3,      (unsigned char)66,      (unsigned char)84,      (unsigned char)82, 
        (unsigned char)67,      (unsigned char)75,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)3,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)48,      (unsigned char)48,      (unsigned char)84, 
        (unsigned char)69,      (unsigned char)78,      (unsigned char)67,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)17,      (unsigned char)64, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)77,      (unsigned char)112, 
        (unsigned char)51,      (unsigned char)87,      (unsigned char)114,      (unsigned char)97, 
        (unsigned char)112,      (unsigned char)32,      (unsigned char)32,      (unsigned char)118, 
        (unsigned char)46,      (unsigned char)32,      (unsigned char)32,      (unsigned char)48, 
        (unsigned char )'.',      (unsigned char)48,      (unsigned char)87,      (unsigned char)88, 
        (unsigned char)88,      (unsigned char)88,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)32,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)104,      (unsigned char)116, 
        (unsigned char)116,      (unsigned char)112,      (unsigned char)58,      (unsigned char)47, 
        (unsigned char)47,      (unsigned char)109,      (unsigned char)112,      (unsigned char)51, 
        (unsigned char)119,      (unsigned char)114,      (unsigned char)97,      (unsigned char)112, 
        (unsigned char)46,      (unsigned char)115,      (unsigned char)111,      (unsigned char)117, 
        (unsigned char)114,      (unsigned char)99,      (unsigned char)101,      (unsigned char)102, 
        (unsigned char)111,      (unsigned char)114,      (unsigned char)103,      (unsigned char)101, 
        (unsigned char)46,      (unsigned char)110,      (unsigned char)101,      (unsigned char)116, 
        (unsigned char)84,      (unsigned char)67,      (unsigned char)79,      (unsigned char)80, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)1, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)84, 
        (unsigned char)79,      (unsigned char)80,      (unsigned char)69,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)1,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)84,      (unsigned char)67, 
        (unsigned char)79,      (unsigned char)77,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)1,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)67,      (unsigned char)79,      (unsigned char)77, 
        (unsigned char)77,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)160,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)101,      (unsigned char)32,      (unsigned char)0, 
        (unsigned char)84,      (unsigned char)104,      (unsigned char)105,      (unsigned char)115, 
        (unsigned char)32,      (unsigned char)102,      (unsigned char)105,      (unsigned char)108, 
        (unsigned char)101,      (unsigned char)32,      (unsigned char)105,      (unsigned char)115, 
        (unsigned char)32,      (unsigned char)119,      (unsigned char)114,      (unsigned char)97, 
        (unsigned char)112,      (unsigned char)112,      (unsigned char)101,      (unsigned char)100, 
        (unsigned char)32,      (unsigned char)119,      (unsigned char)105,      (unsigned char)116, 
        (unsigned char)104,      (unsigned char)32,      (unsigned char)77,      (unsigned char)112, 
        (unsigned char)51,      (unsigned char)87,      (unsigned char)114,      (unsigned char)97, 
        (unsigned char)112,      (unsigned char)46,      (unsigned char)32,      (unsigned char)71, 
        (unsigned char)101,      (unsigned char)116,      (unsigned char)32,      (unsigned char)109, 
        (unsigned char)112,      (unsigned char)51,      (unsigned char)115,      (unsigned char)112, 
        (unsigned char)108,      (unsigned char)116,      (unsigned char)44,      (unsigned char)32, 
        (unsigned char)116,      (unsigned char)104,      (unsigned char)101,      (unsigned char)32, 
        (unsigned char)102,      (unsigned char)114,      (unsigned char)101,      (unsigned char)101, 
        (unsigned char)32,      (unsigned char)116,      (unsigned char)111,      (unsigned char)111, 
        (unsigned char)108,      (unsigned char)32,      (unsigned char)116,      (unsigned char)111, 
        (unsigned char)32,      (unsigned char)115,      (unsigned char)112,      (unsigned char)108, 
        (unsigned char)105,      (unsigned char)116,      (unsigned char)32,      (unsigned char)111, 
        (unsigned char)114,      (unsigned char)105,      (unsigned char)103,      (unsigned char)105, 
        (unsigned char)110,      (unsigned char)97,      (unsigned char)108,      (unsigned char)32, 
        (unsigned char)102,      (unsigned char)105,      (unsigned char)108,      (unsigned char)101, 
        (unsigned char)115,      (unsigned char)32,      (unsigned char)97,      (unsigned char)116, 
        (unsigned char)32,      (unsigned char)104,      (unsigned char)116,      (unsigned char)116, 
        (unsigned char)112,      (unsigned char)58,      (unsigned char)47,      (unsigned char)47, 
        (unsigned char)109,      (unsigned char)112,      (unsigned char)51,      (unsigned char)115, 
        (unsigned char)112,      (unsigned char)108,      (unsigned char)116,      (unsigned char)46, 
        (unsigned char)115,      (unsigned char)111,      (unsigned char)117,      (unsigned char)114, 
        (unsigned char)99,      (unsigned char)101,      (unsigned char)102,      (unsigned char)111, 
        (unsigned char)114,      (unsigned char)103,      (unsigned char)101,      (unsigned char)46, 
        (unsigned char)110,      (unsigned char)101,      (unsigned char)116,      (unsigned char)46, 
        (unsigned char)32,      (unsigned char)80,      (unsigned char)108,      (unsigned char)101, 
        (unsigned char)97,      (unsigned char)115,      (unsigned char)101,      (unsigned char)32, 
        (unsigned char)100,      (unsigned char)111,      (unsigned char)32,      (unsigned char)110, 
        (unsigned char)111,      (unsigned char)116,      (unsigned char)32,      (unsigned char)114, 
        (unsigned char)101,      (unsigned char)109,      (unsigned char)111,      (unsigned char)118, 
        (unsigned char)101,      (unsigned char)32,      (unsigned char)116,      (unsigned char)104, 
        (unsigned char)105,      (unsigned char)115,      (unsigned char)32,      (unsigned char)99, 
        (unsigned char)111,      (unsigned char)109,      (unsigned char)109,      (unsigned char)101, 
        (unsigned char)110,      (unsigned char)116,      (unsigned char)46,      (unsigned char)84, 
        (unsigned char)67,      (unsigned char)79,      (unsigned char)78,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)1,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)84,      (unsigned char)89, 
        (unsigned char)69,      (unsigned char)82,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)1,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)84,      (unsigned char)65,      (unsigned char)76, 
        (unsigned char)66,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)31,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)104,      (unsigned char)116,      (unsigned char)116,      (unsigned char)112, 
        (unsigned char)58,      (unsigned char)47,      (unsigned char)47,      (unsigned char)109, 
        (unsigned char)112,      (unsigned char)51,      (unsigned char)115,      (unsigned char)112, 
        (unsigned char)108,      (unsigned char)116,      (unsigned char)46,      (unsigned char)115, 
        (unsigned char)111,      (unsigned char)117,      (unsigned char)114,      (unsigned char)99, 
        (unsigned char)101,      (unsigned char)102,      (unsigned char)111,      (unsigned char)114, 
        (unsigned char)103,      (unsigned char)101,      (unsigned char)46,      (unsigned char)110, 
        (unsigned char)101,      (unsigned char)116,      (unsigned char)84,      (unsigned char)80, 
        (unsigned char)69,      (unsigned char)49,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)26,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)70,      (unsigned char)105,      (unsigned char)108, 
        (unsigned char)101,      (unsigned char)32,      (unsigned char)119,      (unsigned char)114, 
        (unsigned char)97,      (unsigned char)112,      (unsigned char)112,      (unsigned char)101, 
        (unsigned char)100,      (unsigned char)32,      (unsigned char)119,      (unsigned char)105, 
        (unsigned char)116,      (unsigned char)104,      (unsigned char)32,      (unsigned char)77, 
        (unsigned char)112,      (unsigned char)51,      (unsigned char)87,      (unsigned char)114, 
        (unsigned char)97,      (unsigned char)112,      (unsigned char)84,      (unsigned char)73, 
        (unsigned char)84,      (unsigned char)50,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)38,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)85,      (unsigned char)115,      (unsigned char)101, 
        (unsigned char)32,      (unsigned char)77,      (unsigned char)112,      (unsigned char)51, 
        (unsigned char)83,      (unsigned char)112,      (unsigned char)108,      (unsigned char)116, 
        (unsigned char)32,      (unsigned char)116,      (unsigned char)111,      (unsigned char)32, 
        (unsigned char)111,      (unsigned char)98,      (unsigned char)116,      (unsigned char)97, 
        (unsigned char)105,      (unsigned char)110,      (unsigned char)32,      (unsigned char)111, 
        (unsigned char)114,      (unsigned char)105,      (unsigned char)103,      (unsigned char)105, 
        (unsigned char)110,      (unsigned char)97,      (unsigned char)108,      (unsigned char)32, 
        (unsigned char)116,      (unsigned char)114,      (unsigned char)97,      (unsigned char)99, 
        (unsigned char)107,      (unsigned char)115,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0, 
        (unsigned char)0,      (unsigned char)0,      (unsigned char)0,      (unsigned char)0};
#line 68 "/home/wslee/benchmarks/sound/mp3wrap-0.5/mp3wrap.c"
int main(int argc , char **argv ) 
{ 
  FILE *file_output ;
  FILE *file_input ;
  unsigned long splitpoints[256] ;
  unsigned long begin ;
  unsigned long end ;
  unsigned long len ;
  unsigned long crc ;
  unsigned long fcrc ;
  unsigned char filename[512] ;
  unsigned char *wrapindex ;
  unsigned char c ;
  unsigned char ext[512] ;
  char *ptr ;
  int option ;
  int i ;
  int j ;
  int files ;
  int oldfiles ;
  int indexsize ;
  int id3offset ;
  short optoffset ;
  short addoption ;
  short listoption ;
  short verboption ;
  short ismp3wrap ;
  size_t tmp ;
  size_t tmp___0 ;
  size_t tmp___1 ;
  size_t tmp___2 ;
  size_t tmp___3 ;
  char *tmp___4 ;
  char *tmp___5 ;
  size_t tmp___6 ;
  char *tmp___7 ;
  DIR *tmp___8 ;
  void *tmp___9 ;
  unsigned long tmp___10 ;
  long tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;
  int tmp___16 ;
  long tmp___17 ;
  int tmp___18 ;
  long tmp___19 ;
  int tmp___20 ;
  size_t tmp___21 ;
  void *tmp___22 ;
  int tmp___23 ;
  int tmp___24 ;
  int tmp___25 ;
  unsigned long tmp___26 ;
  char *tmp___27 ;
  size_t tmp___28 ;
  size_t tmp___29 ;
  size_t tmp___30 ;
  char *tmp___31 ;
  size_t tmp___32 ;
  char *tmp___33 ;
  int tmp___34 ;
  size_t tmp___35 ;
  int tmp___36 ;
  int tmp___37 ;
  unsigned long tmp___38 ;
  long tmp___39 ;
  int tmp___40 ;
  size_t tmp___41 ;
  void *__cil_tmp71 ;
  void *__cil_tmp72 ;
  void *__cil_tmp73 ;
  char *__cil_tmp74 ;
  char *__cil_tmp75 ;
  char *__cil_tmp76 ;
  char *__cil_tmp77 ;
  char *__cil_tmp78 ;
  char *__cil_tmp79 ;
  char *__cil_tmp80 ;
  char *__cil_tmp81 ;
  char *__cil_tmp82 ;
  char *__cil_tmp83 ;
  char *__cil_tmp84 ;
  char *__cil_tmp85 ;
  char *__cil_tmp86 ;
  char *__cil_tmp87 ;
  char *__cil_tmp88 ;
  char *__cil_tmp89 ;
  char *__cil_tmp90 ;
  char *__cil_tmp91 ;
  char *__cil_tmp92 ;
  char *__cil_tmp93 ;
  char *__cil_tmp94 ;
  char *__cil_tmp95 ;
  char *__cil_tmp96 ;
  char *__cil_tmp97 ;
  char *__cil_tmp98 ;
  char *__cil_tmp99 ;
  char *__cil_tmp100 ;
  char *__cil_tmp101 ;
  char *__cil_tmp102 ;
  char *__cil_tmp103 ;
  char *__cil_tmp104 ;
  char *__cil_tmp105 ;
  char *__cil_tmp106 ;
  char *__cil_tmp107 ;
  char *__cil_tmp108 ;
  char *__cil_tmp109 ;
  char *__cil_tmp110 ;
  char *__cil_tmp111 ;
  char *__cil_tmp112 ;
  char *__cil_tmp113 ;
  char *__cil_tmp114 ;
  char *__cil_tmp115 ;
  char *__cil_tmp116 ;
  char *__cil_tmp117 ;
  char *__cil_tmp118 ;
  char *__cil_tmp119 ;
  char *__cil_tmp120 ;
  char *__cil_tmp121 ;
  char *__cil_tmp122 ;
  char *__cil_tmp123 ;
  char *__cil_tmp124 ;
  char *__cil_tmp125 ;
  char *__cil_tmp126 ;
  char *__cil_tmp127 ;
  char *__cil_tmp128 ;
  char *__cil_tmp129 ;
  char *__cil_tmp130 ;
  char *__cil_tmp131 ;
  char *__cil_tmp132 ;
  char *__cil_tmp133 ;
  char *__cil_tmp134 ;
  char *__cil_tmp135 ;
  char *__cil_tmp136 ;
  char *__cil_tmp137 ;
  char *__cil_tmp138 ;
  char *__cil_tmp139 ;
  char *__cil_tmp140 ;
  char *__cil_tmp141 ;
  char *__cil_tmp142 ;
  char *__cil_tmp143 ;
  char *__cil_tmp144 ;
  char *__cil_tmp145 ;
  char *__cil_tmp146 ;
  char *__cil_tmp147 ;
  char *__cil_tmp148 ;
  char *__cil_tmp149 ;
  char *__cil_tmp150 ;
  char *__cil_tmp151 ;
  char *__cil_tmp152 ;
  char *__cil_tmp153 ;
  char *__cil_tmp154 ;
  char *__cil_tmp155 ;
  char *__cil_tmp156 ;
  char *__cil_tmp157 ;
  char *__cil_tmp158 ;
  char *__cil_tmp159 ;
  char *__cil_tmp160 ;
  char *__cil_tmp161 ;

  {
  {
#line 71
  begin = 0UL;
#line 71
  len = 0UL;
#line 74
  i = 0;
#line 74
  j = 0;
#line 74
  oldfiles = 0;
#line 74
  indexsize = 0;
#line 74
  id3offset = 0;
#line 75
  optoffset = (short)0;
#line 75
  addoption = (short)0;
#line 75
  listoption = (short)0;
#line 75
  verboption = (short)0;
#line 75
  ismp3wrap = (short)0;
  {
#line 77
  printf((char const   */* __restrict  */)"Mp3Wrap Version 0.5 (2003/Jan/16). See README and COPYING for more!\n");
  }
  {
#line 78
  printf((char const   */* __restrict  */)"Written and copyrights by Matteo Trotta - <matteo.trotta@lib.unimib.it>\n");
  }
  {
#line 79
  printf((char const   */* __restrict  */)"THIS SOFTWARE COMES WITH ABSOLUTELY NO WARRANTY! USE AT YOUR OWN RISK!\n");
  }
  }
  {
  {
#line 81
  while (1) {
    while_continue___12: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 81
    option = getopt(argc, (char * const  *)argv, "lav");
    }
    }
#line 81
    if (! (option != -1)) {
#line 81
      goto while_break;
    }
    {
#line 84
    if (option == 108) {
#line 84
      goto case_108;
    }
#line 89
    if (option == 97) {
#line 89
      goto case_97;
    }
#line 94
    if (option == 118) {
#line 94
      goto case_118;
    }
#line 98
    goto switch_default;
    case_108: /* CIL Label */ 
#line 84
    if ((int )optoffset == 0) {
#line 84
      optoffset = (short)1;
    }
#line 85
    listoption = (short)1;
#line 86
    addoption = (short)0;
#line 87
    goto switch_break;
    case_97: /* CIL Label */ 
#line 89
    if ((int )optoffset == 0) {
#line 89
      optoffset = (short)1;
    }
#line 90
    addoption = (short)1;
#line 91
    listoption = (short)0;
#line 92
    goto switch_break;
    case_118: /* CIL Label */ 
#line 94
    if ((int )optoffset == 0) {
#line 94
      optoffset = (short)1;
    }
#line 95
    verboption = (short)1;
#line 96
    goto switch_break;
    switch_default: /* CIL Label */ 
    {
    {
#line 98
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Run without arguments to see HELP. Read man page for complete documentation.\n");
    }
    {
#line 99
    exit(-1);
    }
    }
#line 100
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
  }
  while_break___12: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 104
  if (! listoption) {
#line 104
    if (argc < 4) {
#line 104
      goto _L;
    } else {
#line 104
      goto _L___0;
    }
  } else
  _L___0: /* CIL Label */ 
#line 104
  if (listoption) {
#line 104
    if (argc < 3) {
      _L: /* CIL Label */ 
      {
      {
#line 105
      printf((char const   */* __restrict  */)"HELP INFORMATION - type \"man mp3wrap\" to see complete documentation\n");
      }
      {
#line 106
      printf((char const   */* __restrict  */)"USAGE\n");
      }
      {
#line 107
      printf((char const   */* __restrict  */)"\tmp3wrap [options] OUTPUTFILE MP3FILE1 MP3FILE2 [MP3FILE3]...\n");
      }
      {
#line 108
      printf((char const   */* __restrict  */)"\nDESCRIPTION\n");
      }
      {
#line 109
      printf((char const   */* __restrict  */)"\tMp3Wrap joins two or more mp3 files in one large playable mp3\n");
      }
      {
#line 110
      printf((char const   */* __restrict  */)"\twithout losing filename and ID3 informations. You will obtain\n");
      }
      {
#line 111
      printf((char const   */* __restrict  */)"\ta file named OUTPUTFILE_MP3WRAP.mp3. Do not remove the MP3WRAP\n");
      }
      {
#line 112
      printf((char const   */* __restrict  */)"\tstring because it\'s useful to let split program to detect that\n");
      }
      {
#line 113
      printf((char const   */* __restrict  */)"\tfile is wrapped with this utility.\n");
      }
      {
#line 114
      printf((char const   */* __restrict  */)"\tTO SPLIT FILE USE Mp3Splt: http://mp3splt.sourceforge.net\n");
      }
      {
#line 115
      printf((char const   */* __restrict  */)"\nOPTIONS\n");
      }
      {
#line 116
      printf((char const   */* __restrict  */)"\t-a  Add the specified files to an existing wrap file\n");
      }
      {
#line 117
      printf((char const   */* __restrict  */)"\t-l  List files wrapped in OUTPUTFILE. (-lv for complete infos)\n");
      }
      {
#line 118
      printf((char const   */* __restrict  */)"\t-v  Verbose mode. Will display additional informations.\n");
      }
      {
#line 119
      printf((char const   */* __restrict  */)"\nEXAMPLES\n");
      }
      {
#line 120
      printf((char const   */* __restrict  */)"\tmp3wrap album.mp3 01.mp3 02.mp3 03.mp3 04.mp3\n");
      }
      {
#line 121
      printf((char const   */* __restrict  */)"\tmp3wrap -a album_MP3WRAP.mp3 ACDC*.mp3\n");
      }
      {
#line 122
      exit(-1);
      }
      }
    }
  }
  {
  {
#line 125
  memset((void *)(filename), '\000', (size_t )512);
  }
  {
#line 127
  ptr = getenv("HOME");
  }
  }
#line 127
  if ((unsigned long )ptr != (unsigned long )((void *)0)) {
    {
    {
#line 127
    sprintf((char */* __restrict  */)(filename), (char const   */* __restrict  */)"%s/.mp3wrap",
            ptr);
    }
    }
  } else {
    {
    {
#line 128
    tmp = strlen(".mp3wrap");
    }
    {
#line 128
    strncpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)".mp3wrap",
            tmp);
    }
    }
  }
  {
  {
#line 130
  strncpy((char */* __restrict  */)(ext), (char const   */* __restrict  */)"_MP3WRAP.mp3",
          (size_t )511);
  }
  {
#line 132
  file_input = fopen((char const   */* __restrict  */)".mp3wrap", (char const   */* __restrict  */)"r");
  }
  }
#line 132
  if (file_input) {
#line 132
    goto _L___1;
  } else {
    {
    {
#line 132
    file_input = fopen((char const   */* __restrict  */)(filename), (char const   */* __restrict  */)"r");
    }
    }
#line 132
    if (file_input) {
      _L___1: /* CIL Label */ 
#line 133
      if (verboption) {
        {
        {
#line 133
        printf((char const   */* __restrict  */)"Reading configuration file...\n");
        }
        }
      }
      {
      {
#line 134
      while (1) {
        while_continue___13: /* CIL Label */ ;
        while_continue___0: /* CIL Label */ ;
        {
        {
#line 134
        tmp___7 = fgets((char */* __restrict  */)(filename), 511, (FILE */* __restrict  */)file_input);
        }
        }
#line 134
        if (! ((unsigned long )tmp___7 != (unsigned long )((void *)0))) {
#line 134
          goto while_break___0;
        }
        {
        {
#line 135
        ptr = strstr((char const   *)(filename), "EXT=");
        }
        }
#line 135
        if ((unsigned long )ptr != (unsigned long )((void *)0)) {
          {
          {
#line 136
          tmp___6 = strlen((char const   *)(filename));
          }
          }
#line 136
          if (tmp___6 > 1U) {
            {
            {
#line 137
            tmp___1 = strlen((char const   *)(filename));
            }
            }
#line 137
            if ((int )filename[tmp___1 - 1U] == 10) {
              {
              {
#line 137
              tmp___0 = strlen((char const   *)(filename));
              }
#line 137
              filename[tmp___0 - 1U] = (unsigned char )'\000';
              }
            }
            {
            {
#line 138
            tmp___3 = strlen((char const   *)(filename));
            }
            }
#line 138
            if ((int )filename[tmp___3 - 1U] == 13) {
              {
              {
#line 138
              tmp___2 = strlen((char const   *)(filename));
              }
#line 138
              filename[tmp___2 - 1U] = (unsigned char )'\000';
              }
            }
            {
#line 139
            ptr += 4;
            {
#line 140
            tmp___4 = strstr((char const   *)ptr, "MP3WRAP");
            }
            }
#line 140
            if ((unsigned long )tmp___4 == (unsigned long )((void *)0)) {
              {
              {
#line 140
              tmp___5 = strstr((char const   *)ptr, "mp3wrap");
              }
              }
#line 140
              if ((unsigned long )tmp___5 == (unsigned long )((void *)0)) {
#line 141
                if (verboption) {
                  {
                  {
#line 141
                  printf((char const   */* __restrict  */)"Warning: your extension does not contain MP3WRAP string!\n");
                  }
                  }
                }
                {
                {
#line 142
                sprintf((char */* __restrict  */)(ext), (char const   */* __restrict  */)"_MP3WRAP_%s",
                        ptr);
                }
                }
              } else {
                {
                {
#line 144
                strncpy((char */* __restrict  */)(ext), (char const   */* __restrict  */)ptr,
                        (size_t )511);
                }
                }
              }
            } else {
              {
              {
#line 144
              strncpy((char */* __restrict  */)(ext), (char const   */* __restrict  */)ptr,
                      (size_t )511);
              }
              }
            }
#line 145
            if (verboption) {
              {
              {
#line 145
              printf((char const   */* __restrict  */)"Using \"%s\" as extension.\n",
                     ext);
              }
              }
            }
#line 146
            goto while_break___0;
          }
        }
      }
      while_break___13: /* CIL Label */ ;
      }
      while_break___0: /* CIL Label */ ;
      }
      {
      {
#line 150
      fclose(file_input);
      }
      }
    }
  }
#line 153
  files = (argc - 2) - (int )optoffset;
#line 155
  i = 0;
  {
  {
#line 155
  while (1) {
    while_continue___14: /* CIL Label */ ;
    while_continue___1: /* CIL Label */ ;
#line 155
    if (! (i < files)) {
#line 155
      goto while_break___1;
    }
    {
    {
#line 156
    tmp___8 = opendir((char const   *)*(argv + ((i + 2) + (int )optoffset)));
    }
    }
#line 156
    if (tmp___8) {
      {
      {
#line 157
      printf((char const   */* __restrict  */)"mp3wrap: omitting %s directory\n",
             *(argv + ((i + 2) + (int )optoffset)));
      }
      {
#line 158
      exchange(argv, (i + 2) + (int )optoffset, (files + 2) + (int )optoffset);
      }
#line 159
      files --;
#line 160
      i --;
      }
    }
#line 155
    i ++;
  }
  while_break___14: /* CIL Label */ ;
  }
  while_break___1: /* CIL Label */ ;
  }
#line 164
  if (files > 255) {
    {
    {
#line 165
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: too many files to wrap!\n");
    }
    {
#line 166
    exit(-1);
    }
    }
  }
  {
  {
#line 169
  indexsize = cindexsize(files, argv, optoffset);
  }
  {
#line 170
  tmp___9 = malloc((size_t )indexsize);
  }
#line 170
  wrapindex = (unsigned char *)tmp___9;
  }
#line 170
  if ((unsigned long )wrapindex == (unsigned long )((void *)0)) {
    {
    {
#line 171
    perror("malloc");
    }
    {
#line 172
    exit(-1);
    }
    }
  }
  {
  {
#line 174
  memset((void *)wrapindex, 0, (size_t )indexsize);
  }
  {
#line 175
  memset((void *)(filename), 0, (size_t )512);
  }
  }
#line 177
  if (addoption) {
#line 177
    goto _L___3;
  } else
#line 177
  if (listoption) {
    _L___3: /* CIL Label */ 
    {
    {
#line 178
    file_input = fopen((char const   */* __restrict  */)*(argv + 2), (char const   */* __restrict  */)"r");
    }
    }
#line 178
    if (! file_input) {
      {
      {
#line 179
      perror((char const   *)*(argv + 2));
      }
      {
#line 180
      exit(-1);
      }
      }
    }
    {
    {
#line 182
    len = flength(file_input);
    }
    }
#line 183
    if (len == 0UL) {
      {
      {
#line 184
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: file is empty!\n");
      }
      {
#line 185
      fclose(file_input);
      }
      {
#line 186
      exit(-1);
      }
      }
    }
    {
    {
#line 188
    tmp___10 = getid3v2(file_input, 0UL);
    }
#line 188
    id3offset = (int )tmp___10;
    {
#line 189
    fseek(file_input, (long )id3offset, 0);
    }
#line 190
    i = 0;
    }
    {
    {
#line 190
    while (1) {
      while_continue___15: /* CIL Label */ ;
      while_continue___2: /* CIL Label */ ;
#line 190
      if (! (i < 16384)) {
#line 190
        goto while_break___2;
      }
      {
      {
#line 191
      tmp___11 = ftell(file_input);
      }
#line 191
      id3offset = (int )tmp___11;
      {
#line 192
      tmp___15 = fgetc(file_input);
      }
      }
#line 192
      if (tmp___15 == 87) {
        {
        {
#line 193
        tmp___14 = fgetc(file_input);
        }
        }
#line 193
        if (tmp___14 == 82) {
          {
          {
#line 194
          tmp___13 = fgetc(file_input);
          }
          }
#line 194
          if (tmp___13 == 65) {
            {
            {
#line 195
            tmp___12 = fgetc(file_input);
            }
            }
#line 195
            if (tmp___12 == 80) {
#line 196
              ismp3wrap = (short)1;
#line 197
              goto while_break___2;
            }
          }
        }
      }
#line 190
      i ++;
    }
    while_break___15: /* CIL Label */ ;
    }
    while_break___2: /* CIL Label */ ;
    }
#line 200
    if (ismp3wrap) {
      {
      {
#line 201
      fseek(file_input, 2L, 1);
      }
      {
#line 202
      tmp___16 = fgetc(file_input);
      }
#line 202
      c = (unsigned char )tmp___16;
      }
#line 202
      if ((int )c < 1) {
#line 202
        if (addoption) {
          {
          {
#line 203
          fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Warning: old index version. Updating to new version...\n");
          }
          }
        } else {
#line 202
          goto _L___2;
        }
      } else
      _L___2: /* CIL Label */ 
#line 205
      if ((int )c > 1) {
        {
        {
#line 206
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: This version of mp3wrap is too old for this file.\nGet the latest version at http://mp3wrap.sourceforge.net!\n");
        }
        {
#line 207
        fclose(file_input);
        }
        {
#line 208
        exit(-1);
        }
        }
      }
      {
      {
#line 210
      oldfiles = fgetc(file_input);
      }
      }
#line 211
      if ((int )c > 0) {
        {
        {
#line 212
        fcrc = getword(file_input, 0UL, 1);
        }
        {
#line 213
        tmp___17 = ftell(file_input);
        }
#line 213
        begin = (unsigned long )tmp___17;
        {
#line 214
        tmp___18 = getid3v1(file_input);
        }
        {
#line 214
        fseek(file_input, (long )tmp___18, 2);
        }
        {
#line 215
        tmp___19 = ftell(file_input);
        }
#line 215
        end = (unsigned long )tmp___19;
        {
#line 216
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Check for file integrity: calculating CRC, please wait... ");
        }
        {
#line 217
        crc = c_crc(file_input, begin, end);
        }
        }
#line 218
        if (crc != fcrc) {
          {
          {
#line 219
          fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\nWARNING: Bad CRC. File might be damaged. Continue anyway? (y/n) ");
          }
          {
#line 220
          tmp___20 = getchar();
          }
          }
#line 220
          if (tmp___20 != 121) {
            {
            {
#line 221
            exit(1);
            }
            }
          }
        } else {
          {
          {
#line 223
          fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"OK\n");
          }
          }
        }
        {
        {
#line 224
        fseek(file_input, (long )begin, 0);
        }
        }
      }
      {
      {
#line 226
      begin = getword(file_input, 0UL, 1);
      }
#line 227
      splitpoints[0] = begin;
      }
#line 228
      if (addoption) {
#line 229
        if (files + oldfiles > 255) {
          {
          {
#line 230
          fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: too many file to wrap in this file!\n");
          }
          {
#line 231
          exit(-1);
          }
          }
        }
        {
        {
#line 233
        tmp___21 = strlen("WRAP");
        }
#line 233
        indexsize = (int )((((unsigned long )indexsize + begin) - 4UL) - (unsigned long )(tmp___21 + 8U));
        }
#line 234
        if ((int )c > 0) {
#line 234
          indexsize -= 4;
        }
        {
        {
#line 235
        tmp___22 = realloc((void *)wrapindex, (size_t )indexsize);
        }
#line 235
        wrapindex = (unsigned char *)tmp___22;
        {
#line 236
        memset((void *)wrapindex, 0, (size_t )indexsize);
        }
#line 237
        j = 12;
        }
      } else {
        {
        {
#line 240
        printf((char const   */* __restrict  */)"List of wrapped files in %s:\n",
               *(argv + 2));
        }
        }
#line 241
        if (verboption) {
          {
          {
#line 242
          printf((char const   */* __restrict  */)"  #    Size\t  Name\n");
          }
          {
#line 243
          printf((char const   */* __restrict  */)" --- --------\t--------\n");
          }
          }
        } else {
          {
          {
#line 245
          printf((char const   */* __restrict  */)"\n");
          }
          }
        }
      }
#line 247
      i = 1;
      {
      {
#line 247
      while (1) {
        while_continue___16: /* CIL Label */ ;
        while_continue___3: /* CIL Label */ ;
#line 247
        if (! (i <= oldfiles)) {
#line 247
          goto while_break___3;
        }
#line 248
        if (addoption) {
#line 249
          j += 4;
        } else {
#line 251
          j = 0;
#line 252
          if (verboption) {
#line 253
            if (i < 100) {
              {
              {
#line 253
              printf((char const   */* __restrict  */)" ");
              }
              }
            }
#line 254
            if (i < 10) {
              {
              {
#line 254
              printf((char const   */* __restrict  */)" ");
              }
              }
            }
          }
        }
        {
        {
#line 257
        while (1) {
          while_continue___17: /* CIL Label */ ;
          while_continue___4: /* CIL Label */ ;
          {
          {
#line 258
          tmp___23 = fgetc(file_input);
          }
#line 258
          c = (unsigned char )tmp___23;
          }
#line 259
          if (addoption) {
#line 260
            tmp___24 = j;
#line 260
            j ++;
#line 260
            *(wrapindex + tmp___24) = c;
          } else {
#line 261
            tmp___25 = j;
#line 261
            j ++;
#line 261
            filename[tmp___25] = c;
          }
#line 257
          if (! ((int )c != 0)) {
#line 257
            goto while_break___4;
          }
        }
        while_break___17: /* CIL Label */ ;
        }
        while_break___4: /* CIL Label */ ;
        }
        {
        {
#line 265
        splitpoints[i] = getword(file_input, 0UL, 1);
        }
        }
#line 267
        if (listoption) {
#line 268
          if (verboption) {
            {
            {
#line 268
            printf((char const   */* __restrict  */)"%d) %lu\t", i, splitpoints[i] - splitpoints[i - 1]);
            }
            }
          }
          {
          {
#line 269
          printf((char const   */* __restrict  */)"%s\n", filename);
          }
          }
        }
#line 247
        i ++;
      }
      while_break___16: /* CIL Label */ ;
      }
      while_break___3: /* CIL Label */ ;
      }
      {
      {
#line 272
      fclose(file_input);
      }
      }
#line 273
      if (listoption) {
#line 275
        if (verboption) {
          {
          {
#line 276
          printf((char const   */* __restrict  */)" --- --------\t--------\n");
          }
          {
#line 277
          printf((char const   */* __restrict  */)"     %lu\t%d files\n", splitpoints[i - 1],
                 oldfiles);
          }
          }
        } else {
          {
          {
#line 279
          printf((char const   */* __restrict  */)"\n");
          }
          }
        }
        {
        {
#line 280
        exit(0);
        }
        }
      }
    } else {
      {
      {
#line 284
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: this is not a valid mp3wrap file!\n");
      }
      {
#line 285
      exit(-1);
      }
      }
    }
  }
#line 289
  if (addoption) {
#line 290
    end = (unsigned long )indexsize - splitpoints[0];
#line 291
    i = 0;
    {
    {
#line 291
    while (1) {
      while_continue___18: /* CIL Label */ ;
      while_continue___5: /* CIL Label */ ;
#line 291
      if (! (i <= oldfiles)) {
#line 291
        goto while_break___5;
      }
#line 292
      splitpoints[i] += end;
#line 291
      i ++;
    }
    while_break___18: /* CIL Label */ ;
    }
    while_break___5: /* CIL Label */ ;
    }
  }
#line 295
  i = 0;
  {
  {
#line 295
  while (1) {
    while_continue___19: /* CIL Label */ ;
    while_continue___6: /* CIL Label */ ;
#line 295
    if (! (i < files)) {
#line 295
      goto while_break___6;
    }
    {
    {
#line 296
    file_input = fopen((char const   */* __restrict  */)*(argv + ((i + 2) + (int )optoffset)),
                       (char const   */* __restrict  */)"r");
    }
    }
#line 296
    if (! file_input) {
      {
      {
#line 297
      perror((char const   *)*(argv + ((i + 2) + (int )optoffset)));
      }
      {
#line 298
      exit(-1);
      }
      }
    }
#line 300
    if (! addoption) {
#line 300
      if (i == 0) {
#line 300
        splitpoints[i] = (unsigned long )indexsize;
      }
    }
    {
    {
#line 302
    tmp___26 = flength(file_input);
    }
#line 302
    splitpoints[(i + 1) + oldfiles] = tmp___26 + splitpoints[i + oldfiles];
    {
#line 304
    fclose(file_input);
    }
#line 295
    i ++;
    }
  }
  while_break___19: /* CIL Label */ ;
  }
  while_break___6: /* CIL Label */ ;
  }
  {
  {
#line 307
  tmp___27 = buildindex((char *)wrapindex, indexsize, files, argv, optoffset, splitpoints,
                        addoption, oldfiles);
  }
#line 307
  wrapindex = (unsigned char *)tmp___27;
  }
#line 309
  if (! addoption) {
    {
    {
#line 310
    tmp___28 = strlen((char const   *)*(argv + (1 + (int )optoffset)));
    }
    {
#line 310
    strncpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)*(argv + (1 + (int )optoffset)),
            tmp___28);
    }
    {
#line 311
    tmp___33 = strstr((char const   *)(filename), (char const   *)(ext));
    }
    }
#line 311
    if ((unsigned long )tmp___33 == (unsigned long )((void *)0)) {
      {
      {
#line 312
      tmp___30 = strlen((char const   *)(filename));
      }
      }
#line 312
      if (tmp___30 > 4U) {
        {
        {
#line 312
        tmp___31 = strstr((char const   *)(filename), ".mp3");
        }
        }
#line 312
        if ((unsigned long )tmp___31 != (unsigned long )((void *)0)) {
          {
          {
#line 313
          tmp___29 = strlen((char const   *)(filename));
          }
#line 313
          filename[tmp___29 - 4U] = (unsigned char )'\000';
          }
        }
      }
      {
      {
#line 314
      tmp___32 = strlen((char const   *)(ext));
      }
      {
#line 314
      strncat((char */* __restrict  */)(filename), (char const   */* __restrict  */)(ext),
              tmp___32);
      }
      }
    }
    {
    {
#line 316
    file_input = fopen((char const   */* __restrict  */)(filename), (char const   */* __restrict  */)"r");
    }
    }
#line 316
    if (file_input) {
      {
      {
#line 317
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Warning: %s exists, overwrite ? (y/n) ",
              filename);
      }
      {
#line 318
      fclose(file_input);
      }
      {
#line 319
      tmp___34 = getchar();
      }
      }
#line 319
      if (tmp___34 != 121) {
        {
        {
#line 320
        exit(-1);
        }
        }
      }
    }
  } else {
    {
    {
#line 325
    tmp___35 = strlen("temp_MP3WRAP.mp3");
    }
    {
#line 325
    strncpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)"temp_MP3WRAP.mp3",
            tmp___35);
    }
    }
  }
  {
  {
#line 327
  file_output = fopen((char const   */* __restrict  */)(filename), (char const   */* __restrict  */)"w+");
  }
  }
#line 327
  if (! file_output) {
    {
    {
#line 328
    perror((char const   *)*(argv + (1 + (int )optoffset)));
    }
    {
#line 329
    exit(-1);
    }
    }
  }
#line 332
  if (files + oldfiles > 9) {
#line 332
    id3[21] = (unsigned char )(((files + oldfiles) / 10) % 10 | 48);
  }
  {
#line 333
  id3[22] = (unsigned char )((files + oldfiles) % 10 | 48);
  {
#line 334
  id3[47] = charat((char *)"0.5", 0);
  }
  {
#line 335
  id3[49] = charat((char *)"0.5", 2);
  }
#line 337
  i = 0;
  }
  {
  {
#line 337
  while (1) {
    while_continue___20: /* CIL Label */ ;
    while_continue___7: /* CIL Label */ ;
#line 337
    if (! (i < 460)) {
#line 337
      goto while_break___7;
    }
    {
    {
#line 338
    fputc((int )id3[i], file_output);
    }
#line 337
    i ++;
    }
  }
  while_break___20: /* CIL Label */ ;
  }
  while_break___7: /* CIL Label */ ;
  }
#line 340
  i = 0;
  {
  {
#line 340
  while (1) {
    while_continue___21: /* CIL Label */ ;
    while_continue___8: /* CIL Label */ ;
#line 340
    if (! (i < indexsize)) {
#line 340
      goto while_break___8;
    }
    {
    {
#line 341
    fputc((int )*(wrapindex + i), file_output);
    }
#line 340
    i ++;
    }
  }
  while_break___21: /* CIL Label */ ;
  }
  while_break___8: /* CIL Label */ ;
  }
  {
  {
#line 343
  printf((char const   */* __restrict  */)"\n");
  }
  }
#line 345
  if (addoption) {
    {
    {
#line 346
    file_input = fopen((char const   */* __restrict  */)*(argv + 2), (char const   */* __restrict  */)"r");
    }
    }
#line 346
    if (! file_input) {
      {
      {
#line 347
      perror((char const   *)*(argv + 2));
      }
      {
#line 348
      exit(-1);
      }
      }
    }
    {
    {
#line 350
    fseek(file_input, (long )((unsigned long )id3offset + begin), 0);
    }
    {
#line 351
    printf((char const   */* __restrict  */)"Copying files from input file...  0%%");
    }
    {
#line 352
    fflush(stdout);
    }
#line 353
    begin += (unsigned long )id3offset;
    }
    {
    {
#line 353
    while (1) {
      while_continue___22: /* CIL Label */ ;
      while_continue___9: /* CIL Label */ ;
#line 353
      if (! (begin < len - 1UL)) {
#line 353
        goto while_break___9;
      }
#line 354
      if (begin % (len / 100UL) == 0UL) {
#line 355
        if (begin / (len / 100UL) > 9UL) {
          {
          {
#line 356
          printf((char const   */* __restrict  */)"\b");
          }
          }
        }
        {
        {
#line 357
        printf((char const   */* __restrict  */)"\b\b%ld%%", begin / (len / 100UL));
        }
        {
#line 358
        fflush(stdout);
        }
        }
      }
      {
      {
#line 360
      tmp___36 = fgetc(file_input);
      }
      {
#line 360
      fputc(tmp___36, file_output);
      }
#line 353
      begin ++;
      }
    }
    while_break___22: /* CIL Label */ ;
    }
    while_break___9: /* CIL Label */ ;
    }
    {
    {
#line 362
    fclose(file_input);
    }
    {
#line 363
    printf((char const   */* __restrict  */)"\n\n");
    }
    }
  }
#line 366
  i = 0;
  {
  {
#line 366
  while (1) {
    while_continue___23: /* CIL Label */ ;
    while_continue___10: /* CIL Label */ ;
#line 366
    if (! (i < files)) {
#line 366
      goto while_break___10;
    }
    {
    {
#line 368
    printf((char const   */* __restrict  */)"  %d %%\t-->", ((i + 1) * 100) / files);
    }
    }
#line 369
    if (addoption) {
      {
      {
#line 370
      printf((char const   */* __restrict  */)" Adding ");
      }
      }
    } else {
      {
      {
#line 372
      printf((char const   */* __restrict  */)" Wrapping ");
      }
      }
    }
    {
    {
#line 373
    printf((char const   */* __restrict  */)"%s ...", *(argv + ((i + 2) + (int )optoffset)));
    }
    {
#line 374
    fflush(stdout);
    }
    {
#line 375
    file_input = fopen((char const   */* __restrict  */)*(argv + ((i + 2) + (int )optoffset)),
                       (char const   */* __restrict  */)"r");
    }
    }
#line 375
    if (! file_input) {
      {
      {
#line 376
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)" FAILED\n");
      }
      {
#line 377
      perror((char const   *)*(argv + ((i + 2) + (int )optoffset)));
      }
      {
#line 378
      exit(-1);
      }
      }
    }
    {
#line 381
    begin = 0UL;
    {
#line 382
    end = flength(file_input);
    }
    {
#line 383
    fseek(file_input, 0L, 0);
    }
    }
    {
    {
#line 384
    while (1) {
      while_continue___24: /* CIL Label */ ;
      while_continue___11: /* CIL Label */ ;
#line 384
      tmp___38 = begin;
#line 384
      begin ++;
#line 384
      if (! (tmp___38 < end)) {
#line 384
        goto while_break___11;
      }
      {
      {
#line 385
      tmp___37 = fgetc(file_input);
      }
      {
#line 385
      fputc(tmp___37, file_output);
      }
      }
    }
    while_break___24: /* CIL Label */ ;
    }
    while_break___11: /* CIL Label */ ;
    }
    {
    {
#line 386
    printf((char const   */* __restrict  */)" OK\n");
    }
    {
#line 387
    fclose(file_input);
    }
#line 366
    i ++;
    }
  }
  while_break___23: /* CIL Label */ ;
  }
  while_break___10: /* CIL Label */ ;
  }
  {
  {
#line 390
  printf((char const   */* __restrict  */)"\n  Calculating CRC, please wait... ");
  }
  {
#line 391
  fflush(stdout);
  }
  {
#line 393
  fputc(0, file_output);
  }
  {
#line 395
  tmp___39 = ftell(file_output);
  }
#line 395
  len = (unsigned long )tmp___39;
  {
#line 396
  crc = c_crc(file_output, 472UL, len);
  }
  {
#line 397
  fseek(file_output, 468L, 0);
  }
  {
#line 398
  fputc((int )((crc >> 24) & 255UL), file_output);
  }
  {
#line 399
  fputc((int )((crc >> 16) & 255UL), file_output);
  }
  {
#line 400
  fputc((int )((crc >> 8) & 255UL), file_output);
  }
  {
#line 401
  fputc((int )(crc & 255UL), file_output);
  }
  {
#line 403
  fclose(file_output);
  }
  {
#line 405
  printf((char const   */* __restrict  */)"OK\n");
  }
  }
#line 407
  if (addoption) {
    {
    {
#line 408
    memset((void *)wrapindex, 0, (size_t )indexsize);
    }
    {
#line 409
    sprintf((char */* __restrict  */)wrapindex, (char const   */* __restrict  */)"mv -f temp_MP3WRAP.mp3 %s",
            *(argv + 2));
    }
    {
#line 410
    tmp___40 = system((char const   *)wrapindex);
    }
    }
#line 410
    if (tmp___40 == -1) {
      {
      {
#line 411
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: could not rename temp_MP3WRAP.mp3! Do it manually.\n");
      }
      }
    }
    {
    {
#line 412
    tmp___41 = strlen((char const   *)*(argv + 2));
    }
    {
#line 412
    strncpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)*(argv + 2),
            tmp___41 + 1U);
    }
    }
  }
  {
  {
#line 415
  printf((char const   */* __restrict  */)"\n%s has been created successfully!\nUse mp3splt to dewrap file; download at http://mp3splt.sourceforge.net!\n",
         filename);
  }
  {
#line 416
  free((void *)wrapindex);
  }
  }
#line 417
  return (0);
}
}
#line 34 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
unsigned char charat(char *s , int pos ) 
{ 
  int tmp ;

  {
  {
  {
#line 36
  tmp = (int )strlen(s);
  }
  }
#line 36
  if (pos < tmp) {
#line 37
    return ((unsigned char )*(s + pos));
  } else {
#line 38
    return ((unsigned char)255);
  }
}
}
#line 41 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
int getid3v1(FILE *file_input ) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  {
  {
#line 42
  fseek(file_input, -128L, 2);
  }
  {
#line 43
  tmp___1 = fgetc(file_input);
  }
  }
#line 43
  if (tmp___1 == 84) {
    {
    {
#line 44
    tmp___0 = fgetc(file_input);
    }
    }
#line 44
    if (tmp___0 == 65) {
      {
      {
#line 45
      tmp = fgetc(file_input);
      }
      }
#line 45
      if (tmp == 71) {
#line 46
        return (-128);
      }
    }
  }
#line 47
  return (0);
}
}
#line 50 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
unsigned long flength(FILE *in ) 
{ 
  long tmp ;

  {
  {
  {
#line 52
  fseek(in, 0L, 2);
  }
  {
#line 53
  tmp = ftell(in);
  }
  }
#line 53
  return ((unsigned long )tmp);
}
}
#line 56 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
int cindexsize(int files , char **argv , short optoffset ) 
{ 
  int i ;
  int size ;
  int tmp ;
  int tmp___0 ;
  char *__cil_tmp8 ;

  {
#line 58
  size = 0;
#line 59
  i = 0;
  {
  {
#line 59
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 59
    if (! (i < files)) {
#line 59
      goto while_break;
    }
    {
    {
#line 60
    tmp = (int )strlen(*(argv + ((i + 2) + (int )optoffset)));
    }
#line 60
    size += tmp + 1;
#line 59
    i ++;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 61
  tmp___0 = (int )strlen("WRAP");
  }
  }
#line 61
  return ((((size + tmp___0) + (files + 2) * 4) + 4) + 4);
}
}
#line 64 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
char *buildindex(char *wrapindex , int indexsize , int files , char **argv , short optoffset ,
                 unsigned long *splitpoints , short addoption , int oldfiles ) 
{ 
  int i ;
  int j ;
  int k ;
  char c ;
  int tmp ;
  unsigned char tmp___0 ;
  unsigned char tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;

  {
  {
#line 68
  j = 12;
  {
#line 70
  tmp = (int )strlen("WRAP");
  }
  {
#line 70
  strncpy(wrapindex, "WRAP", tmp);
  }
  {
#line 71
  tmp___0 = charat((char *)"0.5", 0);
  }
#line 71
  *(wrapindex + 4) = (char )tmp___0;
  {
#line 72
  tmp___1 = charat((char *)"0.5", 2);
  }
#line 72
  *(wrapindex + 5) = (char )tmp___1;
#line 73
  *(wrapindex + 6) = (char)1;
#line 74
  *(wrapindex + 7) = (char )(files + oldfiles);
#line 75
  files += oldfiles;
#line 76
  i = 0;
  }
  {
  {
#line 76
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 76
    if (! (i <= files)) {
#line 76
      goto while_break;
    }
#line 77
    tmp___2 = j;
#line 77
    j ++;
#line 77
    *(wrapindex + tmp___2) = (char )((*(splitpoints + i) >> 24) & 255UL);
#line 78
    tmp___3 = j;
#line 78
    j ++;
#line 78
    *(wrapindex + tmp___3) = (char )((*(splitpoints + i) >> 16) & 255UL);
#line 79
    tmp___4 = j;
#line 79
    j ++;
#line 79
    *(wrapindex + tmp___4) = (char )((*(splitpoints + i) >> 8) & 255UL);
#line 80
    tmp___5 = j;
#line 80
    j ++;
#line 80
    *(wrapindex + tmp___5) = (char )(*(splitpoints + i) & 255UL);
#line 81
    if (i < files) {
#line 82
      k = 0;
#line 83
      if (addoption) {
#line 83
        if (i < oldfiles) {
          {
          {
#line 84
          while (1) {
            while_continue___3: /* CIL Label */ ;
            while_continue___0: /* CIL Label */ ;
#line 84
            tmp___6 = j;
#line 84
            j ++;
#line 84
            if (! ((int )*(wrapindex + tmp___6) != 0)) {
#line 84
              goto while_break___0;
            }
          }
          while_break___3: /* CIL Label */ ;
          }
          while_break___0: /* CIL Label */ ;
          }
        } else {
#line 83
          goto _L;
        }
      } else {
        _L: /* CIL Label */ 
        {
        {
#line 86
        while (1) {
          while_continue___4: /* CIL Label */ ;
          while_continue___1: /* CIL Label */ ;
#line 87
          tmp___7 = k;
#line 87
          k ++;
#line 87
          c = *(*(argv + (((i + 2) + (int )optoffset) - oldfiles)) + tmp___7);
#line 88
          tmp___8 = j;
#line 88
          j ++;
#line 88
          *(wrapindex + tmp___8) = c;
#line 86
          if (! ((int )c != 0)) {
#line 86
            goto while_break___1;
          }
        }
        while_break___4: /* CIL Label */ ;
        }
        while_break___1: /* CIL Label */ ;
        }
      }
    }
#line 76
    i ++;
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 95
  if (j != indexsize - 4) {
    {
    {
#line 96
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Error: index build error!\n");
    }
    {
#line 97
    exit(-1);
    }
    }
  }
#line 100
  return (wrapindex);
}
}
#line 103 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
unsigned long getid3v2(FILE *in , unsigned long start ) 
{ 
  char c1 ;
  char c2 ;
  char c3 ;
  char c4 ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;

  {
  {
  {
#line 106
  fseek(in, (long )start, 0);
  }
  {
#line 107
  tmp___5 = fgetc(in);
  }
  }
#line 107
  if (tmp___5 == 73) {
    {
    {
#line 108
    tmp___4 = fgetc(in);
    }
    }
#line 108
    if (tmp___4 == 68) {
      {
      {
#line 109
      tmp___3 = fgetc(in);
      }
      }
#line 109
      if (tmp___3 == 51) {
        {
        {
#line 110
        fseek(in, 3L, 1);
        }
        {
#line 111
        tmp = fgetc(in);
        }
#line 111
        c1 = (char )tmp;
        {
#line 112
        tmp___0 = fgetc(in);
        }
#line 112
        c2 = (char )tmp___0;
        {
#line 113
        tmp___1 = fgetc(in);
        }
#line 113
        c3 = (char )tmp___1;
        {
#line 114
        tmp___2 = fgetc(in);
        }
#line 114
        c4 = (char )tmp___2;
        }
#line 115
        return ((unsigned long )((((int )c1 * 2097151 + (int )c2 * 16384) + (int )c3 * 128) + (int )c4));
      }
    }
  }
#line 118
  return (0UL);
}
}
#line 121 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
unsigned long getword(FILE *in , unsigned long offset , int mode ) 
{ 
  int i ;
  unsigned long head ;
  int tmp ;

  {
  {
#line 123
  head = 0UL;
  {
#line 124
  fseek(in, (long )offset, mode);
  }
#line 125
  i = 0;
  }
  {
  {
#line 125
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 125
    if (! (i < 4)) {
#line 125
      goto while_break;
    }
    {
#line 126
    head <<= 8;
    {
#line 127
    tmp = fgetc(in);
    }
#line 127
    head |= (unsigned long )tmp;
#line 125
    i ++;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 129
  return (head);
}
}
#line 132 "/home/wslee/benchmarks/sound/mp3wrap-0.5/wrap.c"
char **exchange(char **argv , int offset , int tot ) 
{ 
  char **first ;

  {
#line 134
  first = argv + offset;
  {
  {
#line 135
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 135
    if (! (offset < tot)) {
#line 135
      goto while_break;
    }
#line 136
    *first = *(argv + (offset + 1));
#line 137
    first ++;
#line 138
    offset ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 141
  return (argv);
}
}
#line 31 "/home/wslee/benchmarks/sound/mp3wrap-0.5/crc.c"
static u_int32_t const   crctab[256]  = 
#line 31 "/home/wslee/benchmarks/sound/mp3wrap-0.5/crc.c"
  {      (u_int32_t const   )0,      (u_int32_t const   )1996959894,      (u_int32_t const   )3993919788U,      (u_int32_t const   )2567524794U, 
        (u_int32_t const   )124634137,      (u_int32_t const   )1886057615,      (u_int32_t const   )3915621685U,      (u_int32_t const   )2657392035U, 
        (u_int32_t const   )249268274,      (u_int32_t const   )2044508324,      (u_int32_t const   )3772115230U,      (u_int32_t const   )2547177864U, 
        (u_int32_t const   )162941995,      (u_int32_t const   )2125561021,      (u_int32_t const   )3887607047U,      (u_int32_t const   )2428444049U, 
        (u_int32_t const   )498536548,      (u_int32_t const   )1789927666,      (u_int32_t const   )4089016648U,      (u_int32_t const   )2227061214U, 
        (u_int32_t const   )450548861,      (u_int32_t const   )1843258603,      (u_int32_t const   )4107580753U,      (u_int32_t const   )2211677639U, 
        (u_int32_t const   )325883990,      (u_int32_t const   )1684777152,      (u_int32_t const   )4251122042U,      (u_int32_t const   )2321926636U, 
        (u_int32_t const   )335633487,      (u_int32_t const   )1661365465,      (u_int32_t const   )4195302755U,      (u_int32_t const   )2366115317U, 
        (u_int32_t const   )997073096,      (u_int32_t const   )1281953886,      (u_int32_t const   )3579855332U,      (u_int32_t const   )2724688242U, 
        (u_int32_t const   )1006888145,      (u_int32_t const   )1258607687,      (u_int32_t const   )3524101629U,      (u_int32_t const   )2768942443U, 
        (u_int32_t const   )901097722,      (u_int32_t const   )1119000684,      (u_int32_t const   )3686517206U,      (u_int32_t const   )2898065728U, 
        (u_int32_t const   )853044451,      (u_int32_t const   )1172266101,      (u_int32_t const   )3705015759U,      (u_int32_t const   )2882616665U, 
        (u_int32_t const   )651767980,      (u_int32_t const   )1373503546,      (u_int32_t const   )3369554304U,      (u_int32_t const   )3218104598U, 
        (u_int32_t const   )565507253,      (u_int32_t const   )1454621731,      (u_int32_t const   )3485111705U,      (u_int32_t const   )3099436303U, 
        (u_int32_t const   )671266974,      (u_int32_t const   )1594198024,      (u_int32_t const   )3322730930U,      (u_int32_t const   )2970347812U, 
        (u_int32_t const   )795835527,      (u_int32_t const   )1483230225,      (u_int32_t const   )3244367275U,      (u_int32_t const   )3060149565U, 
        (u_int32_t const   )1994146192,      (u_int32_t const   )31158534,      (u_int32_t const   )2563907772U,      (u_int32_t const   )4023717930U, 
        (u_int32_t const   )1907459465,      (u_int32_t const   )112637215,      (u_int32_t const   )2680153253U,      (u_int32_t const   )3904427059U, 
        (u_int32_t const   )2013776290,      (u_int32_t const   )251722036,      (u_int32_t const   )2517215374U,      (u_int32_t const   )3775830040U, 
        (u_int32_t const   )2137656763,      (u_int32_t const   )141376813,      (u_int32_t const   )2439277719U,      (u_int32_t const   )3865271297U, 
        (u_int32_t const   )1802195444,      (u_int32_t const   )476864866,      (u_int32_t const   )2238001368U,      (u_int32_t const   )4066508878U, 
        (u_int32_t const   )1812370925,      (u_int32_t const   )453092731,      (u_int32_t const   )2181625025U,      (u_int32_t const   )4111451223U, 
        (u_int32_t const   )1706088902,      (u_int32_t const   )314042704,      (u_int32_t const   )2344532202U,      (u_int32_t const   )4240017532U, 
        (u_int32_t const   )1658658271,      (u_int32_t const   )366619977,      (u_int32_t const   )2362670323U,      (u_int32_t const   )4224994405U, 
        (u_int32_t const   )1303535960,      (u_int32_t const   )984961486,      (u_int32_t const   )2747007092U,      (u_int32_t const   )3569037538U, 
        (u_int32_t const   )1256170817,      (u_int32_t const   )1037604311,      (u_int32_t const   )2765210733U,      (u_int32_t const   )3554079995U, 
        (u_int32_t const   )1131014506,      (u_int32_t const   )879679996,      (u_int32_t const   )2909243462U,      (u_int32_t const   )3663771856U, 
        (u_int32_t const   )1141124467,      (u_int32_t const   )855842277,      (u_int32_t const   )2852801631U,      (u_int32_t const   )3708648649U, 
        (u_int32_t const   )1342533948,      (u_int32_t const   )654459306,      (u_int32_t const   )3188396048U,      (u_int32_t const   )3373015174U, 
        (u_int32_t const   )1466479909,      (u_int32_t const   )544179635,      (u_int32_t const   )3110523913U,      (u_int32_t const   )3462522015U, 
        (u_int32_t const   )1591671054,      (u_int32_t const   )702138776,      (u_int32_t const   )2966460450U,      (u_int32_t const   )3352799412U, 
        (u_int32_t const   )1504918807,      (u_int32_t const   )783551873,      (u_int32_t const   )3082640443U,      (u_int32_t const   )3233442989U, 
        (u_int32_t const   )3988292384U,      (u_int32_t const   )2596254646U,      (u_int32_t const   )62317068,      (u_int32_t const   )1957810842, 
        (u_int32_t const   )3939845945U,      (u_int32_t const   )2647816111U,      (u_int32_t const   )81470997,      (u_int32_t const   )1943803523, 
        (u_int32_t const   )3814918930U,      (u_int32_t const   )2489596804U,      (u_int32_t const   )225274430,      (u_int32_t const   )2053790376, 
        (u_int32_t const   )3826175755U,      (u_int32_t const   )2466906013U,      (u_int32_t const   )167816743,      (u_int32_t const   )2097651377, 
        (u_int32_t const   )4027552580U,      (u_int32_t const   )2265490386U,      (u_int32_t const   )503444072,      (u_int32_t const   )1762050814, 
        (u_int32_t const   )4150417245U,      (u_int32_t const   )2154129355U,      (u_int32_t const   )426522225,      (u_int32_t const   )1852507879, 
        (u_int32_t const   )4275313526U,      (u_int32_t const   )2312317920U,      (u_int32_t const   )282753626,      (u_int32_t const   )1742555852, 
        (u_int32_t const   )4189708143U,      (u_int32_t const   )2394877945U,      (u_int32_t const   )397917763,      (u_int32_t const   )1622183637, 
        (u_int32_t const   )3604390888U,      (u_int32_t const   )2714866558U,      (u_int32_t const   )953729732,      (u_int32_t const   )1340076626, 
        (u_int32_t const   )3518719985U,      (u_int32_t const   )2797360999U,      (u_int32_t const   )1068828381,      (u_int32_t const   )1219638859, 
        (u_int32_t const   )3624741850U,      (u_int32_t const   )2936675148U,      (u_int32_t const   )906185462,      (u_int32_t const   )1090812512, 
        (u_int32_t const   )3747672003U,      (u_int32_t const   )2825379669U,      (u_int32_t const   )829329135,      (u_int32_t const   )1181335161, 
        (u_int32_t const   )3412177804U,      (u_int32_t const   )3160834842U,      (u_int32_t const   )628085408,      (u_int32_t const   )1382605366, 
        (u_int32_t const   )3423369109U,      (u_int32_t const   )3138078467U,      (u_int32_t const   )570562233,      (u_int32_t const   )1426400815, 
        (u_int32_t const   )3317316542U,      (u_int32_t const   )2998733608U,      (u_int32_t const   )733239954,      (u_int32_t const   )1555261956, 
        (u_int32_t const   )3268935591U,      (u_int32_t const   )3050360625U,      (u_int32_t const   )752459403,      (u_int32_t const   )1541320221, 
        (u_int32_t const   )2607071920U,      (u_int32_t const   )3965973030U,      (u_int32_t const   )1969922972,      (u_int32_t const   )40735498, 
        (u_int32_t const   )2617837225U,      (u_int32_t const   )3943577151U,      (u_int32_t const   )1913087877,      (u_int32_t const   )83908371, 
        (u_int32_t const   )2512341634U,      (u_int32_t const   )3803740692U,      (u_int32_t const   )2075208622,      (u_int32_t const   )213261112, 
        (u_int32_t const   )2463272603U,      (u_int32_t const   )3855990285U,      (u_int32_t const   )2094854071,      (u_int32_t const   )198958881, 
        (u_int32_t const   )2262029012U,      (u_int32_t const   )4057260610U,      (u_int32_t const   )1759359992,      (u_int32_t const   )534414190, 
        (u_int32_t const   )2176718541U,      (u_int32_t const   )4139329115U,      (u_int32_t const   )1873836001,      (u_int32_t const   )414664567, 
        (u_int32_t const   )2282248934U,      (u_int32_t const   )4279200368U,      (u_int32_t const   )1711684554,      (u_int32_t const   )285281116, 
        (u_int32_t const   )2405801727U,      (u_int32_t const   )4167216745U,      (u_int32_t const   )1634467795,      (u_int32_t const   )376229701, 
        (u_int32_t const   )2685067896U,      (u_int32_t const   )3608007406U,      (u_int32_t const   )1308918612,      (u_int32_t const   )956543938, 
        (u_int32_t const   )2808555105U,      (u_int32_t const   )3495958263U,      (u_int32_t const   )1231636301,      (u_int32_t const   )1047427035, 
        (u_int32_t const   )2932959818U,      (u_int32_t const   )3654703836U,      (u_int32_t const   )1088359270,      (u_int32_t const   )936918000, 
        (u_int32_t const   )2847714899U,      (u_int32_t const   )3736837829U,      (u_int32_t const   )1202900863,      (u_int32_t const   )817233897, 
        (u_int32_t const   )3183342108U,      (u_int32_t const   )3401237130U,      (u_int32_t const   )1404277552,      (u_int32_t const   )615818150, 
        (u_int32_t const   )3134207493U,      (u_int32_t const   )3453421203U,      (u_int32_t const   )1423857449,      (u_int32_t const   )601450431, 
        (u_int32_t const   )3009837614U,      (u_int32_t const   )3294710456U,      (u_int32_t const   )1567103746,      (u_int32_t const   )711928724, 
        (u_int32_t const   )3020668471U,      (u_int32_t const   )3272380065U,      (u_int32_t const   )1510334235,      (u_int32_t const   )755167117};
#line 98 "/home/wslee/benchmarks/sound/mp3wrap-0.5/crc.c"
unsigned long c_crc(FILE *in , unsigned long begin , unsigned long end ) 
{ 
  register unsigned long crc ;
  int c ;
  int tmp ;
  unsigned long tmp___0 ;
  char *__cil_tmp8 ;

  {
  {
#line 103
  crc = 4294967295UL;
  {
#line 105
  tmp = fseek(in, (long )begin, 0);
  }
  }
#line 105
  if (tmp == -1) {
    {
    {
#line 106
    perror("fseek");
    }
    {
#line 107
    exit(0);
    }
    }
  }
  {
  {
#line 110
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 110
    tmp___0 = begin;
#line 110
    begin ++;
#line 110
    if (! (tmp___0 < end)) {
#line 110
      goto while_break;
    }
    {
    {
#line 111
    c = fgetc(in);
    }
#line 112
    crc = ((crc >> 8) & 16777215UL) ^ (unsigned long )crctab[(crc ^ (unsigned long )c) & 255UL];
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 115
  return (crc ^ 4294967295UL);
}
}
#line 31 "/home/wslee/benchmarks/sound/mp3wrap-0.5/crc.c"
static u_int32_t const   crctab___0[256]  = 
#line 31
  {      (u_int32_t const   )0,      (u_int32_t const   )1996959894,      (u_int32_t const   )3993919788U,      (u_int32_t const   )2567524794U, 
        (u_int32_t const   )124634137,      (u_int32_t const   )1886057615,      (u_int32_t const   )3915621685U,      (u_int32_t const   )2657392035U, 
        (u_int32_t const   )249268274,      (u_int32_t const   )2044508324,      (u_int32_t const   )3772115230U,      (u_int32_t const   )2547177864U, 
        (u_int32_t const   )162941995,      (u_int32_t const   )2125561021,      (u_int32_t const   )3887607047U,      (u_int32_t const   )2428444049U, 
        (u_int32_t const   )498536548,      (u_int32_t const   )1789927666,      (u_int32_t const   )4089016648U,      (u_int32_t const   )2227061214U, 
        (u_int32_t const   )450548861,      (u_int32_t const   )1843258603,      (u_int32_t const   )4107580753U,      (u_int32_t const   )2211677639U, 
        (u_int32_t const   )325883990,      (u_int32_t const   )1684777152,      (u_int32_t const   )4251122042U,      (u_int32_t const   )2321926636U, 
        (u_int32_t const   )335633487,      (u_int32_t const   )1661365465,      (u_int32_t const   )4195302755U,      (u_int32_t const   )2366115317U, 
        (u_int32_t const   )997073096,      (u_int32_t const   )1281953886,      (u_int32_t const   )3579855332U,      (u_int32_t const   )2724688242U, 
        (u_int32_t const   )1006888145,      (u_int32_t const   )1258607687,      (u_int32_t const   )3524101629U,      (u_int32_t const   )2768942443U, 
        (u_int32_t const   )901097722,      (u_int32_t const   )1119000684,      (u_int32_t const   )3686517206U,      (u_int32_t const   )2898065728U, 
        (u_int32_t const   )853044451,      (u_int32_t const   )1172266101,      (u_int32_t const   )3705015759U,      (u_int32_t const   )2882616665U, 
        (u_int32_t const   )651767980,      (u_int32_t const   )1373503546,      (u_int32_t const   )3369554304U,      (u_int32_t const   )3218104598U, 
        (u_int32_t const   )565507253,      (u_int32_t const   )1454621731,      (u_int32_t const   )3485111705U,      (u_int32_t const   )3099436303U, 
        (u_int32_t const   )671266974,      (u_int32_t const   )1594198024,      (u_int32_t const   )3322730930U,      (u_int32_t const   )2970347812U, 
        (u_int32_t const   )795835527,      (u_int32_t const   )1483230225,      (u_int32_t const   )3244367275U,      (u_int32_t const   )3060149565U, 
        (u_int32_t const   )1994146192,      (u_int32_t const   )31158534,      (u_int32_t const   )2563907772U,      (u_int32_t const   )4023717930U, 
        (u_int32_t const   )1907459465,      (u_int32_t const   )112637215,      (u_int32_t const   )2680153253U,      (u_int32_t const   )3904427059U, 
        (u_int32_t const   )2013776290,      (u_int32_t const   )251722036,      (u_int32_t const   )2517215374U,      (u_int32_t const   )3775830040U, 
        (u_int32_t const   )2137656763,      (u_int32_t const   )141376813,      (u_int32_t const   )2439277719U,      (u_int32_t const   )3865271297U, 
        (u_int32_t const   )1802195444,      (u_int32_t const   )476864866,      (u_int32_t const   )2238001368U,      (u_int32_t const   )4066508878U, 
        (u_int32_t const   )1812370925,      (u_int32_t const   )453092731,      (u_int32_t const   )2181625025U,      (u_int32_t const   )4111451223U, 
        (u_int32_t const   )1706088902,      (u_int32_t const   )314042704,      (u_int32_t const   )2344532202U,      (u_int32_t const   )4240017532U, 
        (u_int32_t const   )1658658271,      (u_int32_t const   )366619977,      (u_int32_t const   )2362670323U,      (u_int32_t const   )4224994405U, 
        (u_int32_t const   )1303535960,      (u_int32_t const   )984961486,      (u_int32_t const   )2747007092U,      (u_int32_t const   )3569037538U, 
        (u_int32_t const   )1256170817,      (u_int32_t const   )1037604311,      (u_int32_t const   )2765210733U,      (u_int32_t const   )3554079995U, 
        (u_int32_t const   )1131014506,      (u_int32_t const   )879679996,      (u_int32_t const   )2909243462U,      (u_int32_t const   )3663771856U, 
        (u_int32_t const   )1141124467,      (u_int32_t const   )855842277,      (u_int32_t const   )2852801631U,      (u_int32_t const   )3708648649U, 
        (u_int32_t const   )1342533948,      (u_int32_t const   )654459306,      (u_int32_t const   )3188396048U,      (u_int32_t const   )3373015174U, 
        (u_int32_t const   )1466479909,      (u_int32_t const   )544179635,      (u_int32_t const   )3110523913U,      (u_int32_t const   )3462522015U, 
        (u_int32_t const   )1591671054,      (u_int32_t const   )702138776,      (u_int32_t const   )2966460450U,      (u_int32_t const   )3352799412U, 
        (u_int32_t const   )1504918807,      (u_int32_t const   )783551873,      (u_int32_t const   )3082640443U,      (u_int32_t const   )3233442989U, 
        (u_int32_t const   )3988292384U,      (u_int32_t const   )2596254646U,      (u_int32_t const   )62317068,      (u_int32_t const   )1957810842, 
        (u_int32_t const   )3939845945U,      (u_int32_t const   )2647816111U,      (u_int32_t const   )81470997,      (u_int32_t const   )1943803523, 
        (u_int32_t const   )3814918930U,      (u_int32_t const   )2489596804U,      (u_int32_t const   )225274430,      (u_int32_t const   )2053790376, 
        (u_int32_t const   )3826175755U,      (u_int32_t const   )2466906013U,      (u_int32_t const   )167816743,      (u_int32_t const   )2097651377, 
        (u_int32_t const   )4027552580U,      (u_int32_t const   )2265490386U,      (u_int32_t const   )503444072,      (u_int32_t const   )1762050814, 
        (u_int32_t const   )4150417245U,      (u_int32_t const   )2154129355U,      (u_int32_t const   )426522225,      (u_int32_t const   )1852507879, 
        (u_int32_t const   )4275313526U,      (u_int32_t const   )2312317920U,      (u_int32_t const   )282753626,      (u_int32_t const   )1742555852, 
        (u_int32_t const   )4189708143U,      (u_int32_t const   )2394877945U,      (u_int32_t const   )397917763,      (u_int32_t const   )1622183637, 
        (u_int32_t const   )3604390888U,      (u_int32_t const   )2714866558U,      (u_int32_t const   )953729732,      (u_int32_t const   )1340076626, 
        (u_int32_t const   )3518719985U,      (u_int32_t const   )2797360999U,      (u_int32_t const   )1068828381,      (u_int32_t const   )1219638859, 
        (u_int32_t const   )3624741850U,      (u_int32_t const   )2936675148U,      (u_int32_t const   )906185462,      (u_int32_t const   )1090812512, 
        (u_int32_t const   )3747672003U,      (u_int32_t const   )2825379669U,      (u_int32_t const   )829329135,      (u_int32_t const   )1181335161, 
        (u_int32_t const   )3412177804U,      (u_int32_t const   )3160834842U,      (u_int32_t const   )628085408,      (u_int32_t const   )1382605366, 
        (u_int32_t const   )3423369109U,      (u_int32_t const   )3138078467U,      (u_int32_t const   )570562233,      (u_int32_t const   )1426400815, 
        (u_int32_t const   )3317316542U,      (u_int32_t const   )2998733608U,      (u_int32_t const   )733239954,      (u_int32_t const   )1555261956, 
        (u_int32_t const   )3268935591U,      (u_int32_t const   )3050360625U,      (u_int32_t const   )752459403,      (u_int32_t const   )1541320221, 
        (u_int32_t const   )2607071920U,      (u_int32_t const   )3965973030U,      (u_int32_t const   )1969922972,      (u_int32_t const   )40735498, 
        (u_int32_t const   )2617837225U,      (u_int32_t const   )3943577151U,      (u_int32_t const   )1913087877,      (u_int32_t const   )83908371, 
        (u_int32_t const   )2512341634U,      (u_int32_t const   )3803740692U,      (u_int32_t const   )2075208622,      (u_int32_t const   )213261112, 
        (u_int32_t const   )2463272603U,      (u_int32_t const   )3855990285U,      (u_int32_t const   )2094854071,      (u_int32_t const   )198958881, 
        (u_int32_t const   )2262029012U,      (u_int32_t const   )4057260610U,      (u_int32_t const   )1759359992,      (u_int32_t const   )534414190, 
        (u_int32_t const   )2176718541U,      (u_int32_t const   )4139329115U,      (u_int32_t const   )1873836001,      (u_int32_t const   )414664567, 
        (u_int32_t const   )2282248934U,      (u_int32_t const   )4279200368U,      (u_int32_t const   )1711684554,      (u_int32_t const   )285281116, 
        (u_int32_t const   )2405801727U,      (u_int32_t const   )4167216745U,      (u_int32_t const   )1634467795,      (u_int32_t const   )376229701, 
        (u_int32_t const   )2685067896U,      (u_int32_t const   )3608007406U,      (u_int32_t const   )1308918612,      (u_int32_t const   )956543938, 
        (u_int32_t const   )2808555105U,      (u_int32_t const   )3495958263U,      (u_int32_t const   )1231636301,      (u_int32_t const   )1047427035, 
        (u_int32_t const   )2932959818U,      (u_int32_t const   )3654703836U,      (u_int32_t const   )1088359270,      (u_int32_t const   )936918000, 
        (u_int32_t const   )2847714899U,      (u_int32_t const   )3736837829U,      (u_int32_t const   )1202900863,      (u_int32_t const   )817233897, 
        (u_int32_t const   )3183342108U,      (u_int32_t const   )3401237130U,      (u_int32_t const   )1404277552,      (u_int32_t const   )615818150, 
        (u_int32_t const   )3134207493U,      (u_int32_t const   )3453421203U,      (u_int32_t const   )1423857449,      (u_int32_t const   )601450431, 
        (u_int32_t const   )3009837614U,      (u_int32_t const   )3294710456U,      (u_int32_t const   )1567103746,      (u_int32_t const   )711928724, 
        (u_int32_t const   )3020668471U,      (u_int32_t const   )3272380065U,      (u_int32_t const   )1510334235,      (u_int32_t const   )755167117};
