/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned long size_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef long __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 12 "/home/khheo/testset/polymorph-0.4.0/polymorph_types.h"
struct xtn_t;
#line 12 "/home/khheo/testset/polymorph-0.4.0/polymorph_types.h"
struct __anonstruct_xtn_t_24 {
   char x3[16] ;
   struct xtn_t *next ;
};
#line 12 "/home/khheo/testset/polymorph-0.4.0/polymorph_types.h"
typedef struct __anonstruct_xtn_t_24 xtn_t;
#line 17
struct polym_t;
#line 17 "/home/khheo/testset/polymorph-0.4.0/polymorph_types.h"
struct __anonstruct_polym_t_25 {
   char dest[2048] ;
   xtn_t *extns ;
   struct polym_t *next ;
};
#line 17 "/home/khheo/testset/polymorph-0.4.0/polymorph_types.h"
typedef struct __anonstruct_polym_t_25 polym_t;
#line 134 "/usr/include/bits/types.h"
typedef unsigned long __dev_t;
#line 135 "/usr/include/bits/types.h"
typedef unsigned int __uid_t;
#line 136 "/usr/include/bits/types.h"
typedef unsigned int __gid_t;
#line 137 "/usr/include/bits/types.h"
typedef unsigned long __ino_t;
#line 139 "/usr/include/bits/types.h"
typedef unsigned int __mode_t;
#line 140 "/usr/include/bits/types.h"
typedef unsigned long __nlink_t;
#line 149 "/usr/include/bits/types.h"
typedef long __time_t;
#line 164 "/usr/include/bits/types.h"
typedef long __blksize_t;
#line 169 "/usr/include/bits/types.h"
typedef long __blkcnt_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   long tv_nsec ;
};
#line 23 "/usr/include/bits/dirent.h"
struct dirent {
   __ino_t d_ino ;
   __off_t d_off ;
   unsigned short d_reclen ;
   unsigned char d_type ;
   char d_name[256] ;
};
#line 128 "/usr/include/dirent.h"
struct __dirstream;
#line 128 "/usr/include/dirent.h"
typedef struct __dirstream DIR;
#line 43 "/usr/include/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   long __unused[3] ;
};
#line 566 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) getenv)(char const   *__name ) ;
#line 147 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 214
extern int fclose(FILE *__stream ) ;
#line 249
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 604
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream ) ;
#line 81 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) unsigned short const   **__ctype_b_loc(void)  __attribute__((__const__)) ;
#line 64 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1))) memset)(void *__s ,
                                                                                     int __c ,
                                                                                     size_t __n ) ;
#line 127
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strcpy)(char * __restrict  __dest ,
                                                                                       char const   * __restrict  __src ) ;
#line 135
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strcat)(char * __restrict  __dest ,
                                                                                       char const   * __restrict  __src ) ;
#line 233
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) strchr)(char const   *__s ,
                                                                                     int __c )  __attribute__((__pure__)) ;
#line 397
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1))) strlen)(char const   *__s )  __attribute__((__pure__)) ;
#line 3 "/home/khheo/testset/polymorph-0.4.0/rcfile.h"
polym_t *grok_rcfile(void) ;
#line 4
polym_t *parse_rcfile(FILE *rcfile , polym_t *u_prefs ) ;
#line 5
void trim_whitespace(char *victim___0 ) ;
#line 7
polym_t *add_dir(polym_t *list , char *victim___0 ) ;
#line 8
polym_t *find_dir(polym_t *list , char *suspect ) ;
#line 9
xtn_t *find_xtn(xtn_t *list , char *suspect ) ;
#line 10
xtn_t *add_xtn(xtn_t *list , char *victim___0 ) ;
#line 17 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
char init_file[14]  = 
#line 17 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
  {      (char )'/',      (char )'p',      (char )'o',      (char )'l', 
        (char )'y',      (char )'m',      (char )'o',      (char )'r', 
        (char )'p',      (char )'h',      (char )'r',      (char )'c', 
        (char )'\000',      (char )'\000'};
#line 18 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
char hidn_file[15]  = 
#line 18
  {      (char )'/',      (char )'.',      (char )'p',      (char )'o', 
        (char )'l',      (char )'y',      (char )'m',      (char )'o', 
        (char )'r',      (char )'p',      (char )'h',      (char )'r', 
        (char )'c',      (char )'\000',      (char )'\000'};
#line 30 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
polym_t *grok_rcfile(void) 
{ 
  char where[2048] ;
  int step ;
  int found ;
  polym_t *list ;
  FILE *rcfile ;
  char *tmp ;
  char *tmp___0 ;
  void *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;

  {
#line 36
  list = (polym_t *)((void *)0);
#line 37
  step = 0;
#line 37
  found = step;
  {
  {
#line 41
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 41
    if (! (! found)) {
#line 41
      goto while_break;
    }
    {
#line 43
    if (step == 3) {
#line 43
      goto case_3;
    }
#line 48
    if (step == 2) {
#line 48
      goto case_2;
    }
#line 53
    if (step == 1) {
#line 53
      goto case_1;
    }
#line 59
    goto switch_default;
    case_3: /* CIL Label */ 
    {
    {
#line 44
    memset((void *)(where), '\000', (size_t )2048);
    }
    {
#line 45
    strcpy((char */* __restrict  */)(where), (char const   */* __restrict  */)"/etc");
    }
    {
#line 46
    strcat((char */* __restrict  */)(where), (char const   */* __restrict  */)(init_file));
    }
    }
#line 47
    goto switch_break;
    case_2: /* CIL Label */ 
    {
    {
#line 49
    memset((void *)(where), '\000', (size_t )2048);
    }
    {
#line 50
    strcpy((char */* __restrict  */)(where), (char const   */* __restrict  */)"/usr/local/etc");
    }
    {
#line 51
    strcat((char */* __restrict  */)(where), (char const   */* __restrict  */)(init_file));
    }
    }
#line 52
    goto switch_break;
    case_1: /* CIL Label */ 
    {
    {
#line 54
    memset((void *)(where), '\000', (size_t )2048);
    }
    {
#line 55
    tmp = getenv("HOME");
    }
    {
#line 55
    strcpy((char */* __restrict  */)(where), (char const   */* __restrict  */)tmp);
    }
    {
#line 56
    strcat((char */* __restrict  */)(where), (char const   */* __restrict  */)(hidn_file));
    }
    }
#line 57
    goto switch_break;
    switch_default: /* CIL Label */ 
    {
    {
#line 60
    memset((void *)(where), '\000', (size_t )2048);
    }
    {
#line 61
    tmp___0 = getenv("POLYMORPH_DIR");
    }
    {
#line 61
    strcpy((char */* __restrict  */)(where), (char const   */* __restrict  */)tmp___0);
    }
    {
#line 62
    strcat((char */* __restrict  */)(where), (char const   */* __restrict  */)(init_file));
    }
    }
#line 63
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
    {
#line 65
    step ++;
#line 66
    rcfile = (FILE *)((void *)0);
    {
#line 67
    rcfile = fopen((char const   */* __restrict  */)(where), (char const   */* __restrict  */)"r");
    }
#line 68
    found = 1;
    }
#line 69
    if ((unsigned long )rcfile == (unsigned long )((void *)0)) {
      {
      {
#line 70
      fclose(rcfile);
      }
#line 71
      found = 0;
      }
    }
#line 75
    if (step >= 3) {
#line 75
      goto while_break;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 80
  if ((unsigned long )rcfile == (unsigned long )((void *)0)) {
#line 80
    return ((polym_t *)((void *)0));
  }
  {
  {
#line 83
  list = parse_rcfile(rcfile, list);
  }
  {
#line 86
  fclose(rcfile);
  }
  }
#line 88
  if ((unsigned long )list == (unsigned long )((void *)0)) {
    {
    {
#line 88
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"list is NULL\n");
    }
    }
  }
#line 90
  return (list);
}
}
#line 102 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
polym_t *parse_rcfile(FILE *rcfile , polym_t *u_prefs ) 
{ 
  char target_dir[2048] ;
  char after_dir[2048] ;
  char newxtn[16] ;
  char buf[2048] ;
  char *colon ;
  polym_t *tmpdir ;
  polym_t *head ;
  xtn_t *tmpxtn ;
  int e ;
  int i ;
  unsigned short const   **tmp ;
  size_t tmp___0 ;
  xtn_t *tmp___1 ;
  size_t tmp___2 ;
  unsigned short const   **tmp___3 ;
  int tmp___4 ;
  unsigned short const   **tmp___5 ;
  size_t tmp___6 ;
  char *tmp___7 ;
  void *__cil_tmp23 ;
  void *__cil_tmp24 ;
  void *__cil_tmp25 ;
  void *__cil_tmp26 ;
  char *__cil_tmp27 ;

  {
#line 109
  head = (polym_t *)((void *)0);
  {
  {
#line 111
  while (1) {
    while_continue___1: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 111
    tmp___7 = fgets((char */* __restrict  */)(buf), (int )sizeof(buf), (FILE */* __restrict  */)rcfile);
    }
    }
#line 111
    if (! ((unsigned long )tmp___7 != (unsigned long )((void *)0))) {
#line 111
      goto while_break;
    }
#line 113
    if ((int )buf[0] == 35) {
#line 113
      goto while_continue;
    }
#line 114
    if ((int )buf[0] == 33) {
#line 114
      goto while_continue;
    }
#line 115
    if ((int )buf[0] == 59) {
#line 115
      goto while_continue;
    }
#line 116
    if ((int )buf[0] == 58) {
#line 116
      goto while_continue;
    }
    {
    {
#line 119
    tmp = __ctype_b_loc();
    }
    }
#line 119
    if ((int const   )*(*tmp + (int )buf[0]) & 8192) {
#line 119
      goto while_continue;
    }
    {
    {
#line 122
    tmp___0 = strlen((char const   *)(buf));
    }
    }
#line 122
    if (tmp___0 < 16UL) {
#line 122
      goto while_continue;
    }
    {
    {
#line 125
    colon = strchr((char const   *)(buf), ':');
    }
    {
#line 126
    strcpy((char */* __restrict  */)(target_dir), (char const   */* __restrict  */)(buf));
    }
    {
#line 127
    strcpy((char */* __restrict  */)(after_dir), (char const   */* __restrict  */)colon);
    }
    {
#line 130
    colon = strchr((char const   *)(target_dir), ':');
    }
#line 131
    *colon = (char )'\000';
    {
#line 132
    trim_whitespace(target_dir);
    }
#line 135
    tmpdir = (polym_t *)((void *)0);
    }
#line 136
    if ((unsigned long )u_prefs == (unsigned long )((void *)0)) {
      {
      {
#line 137
      tmpdir = add_dir(u_prefs, target_dir);
      }
      }
    } else {
      {
      {
#line 139
      tmpdir = find_dir(u_prefs, target_dir);
      }
      }
#line 140
      if ((unsigned long )tmpdir == (unsigned long )((void *)0)) {
        {
        {
#line 141
        tmpdir = add_dir(u_prefs, target_dir);
        }
        }
      }
    }
#line 146
    tmpxtn = (xtn_t *)((void *)0);
#line 147
    e = 0;
#line 149
    i = 0;
    {
    {
#line 149
    while (1) {
      while_continue___2: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
      {
      {
#line 149
      tmp___6 = strlen((char const   *)(after_dir));
      }
      }
#line 149
      if (! ((size_t )i < tmp___6)) {
#line 149
        goto while_break___0;
      }
      {
      {
#line 151
      tmp___3 = __ctype_b_loc();
      }
      }
#line 151
      if ((int const   )*(*tmp___3 + (int )after_dir[i]) & 8192) {
#line 151
        goto _L;
      } else
#line 151
      if ((int )after_dir[i] == 44) {
        _L: /* CIL Label */ 
        {
        {
#line 152
        tmp___2 = strlen((char const   *)(newxtn));
        }
        }
#line 152
        if (tmp___2 > 1UL) {
          {
          {
#line 155
          tmp___1 = find_xtn(tmpxtn, newxtn);
          }
          }
#line 155
          if ((unsigned long )tmp___1 != (unsigned long )((void *)0)) {
            {
            {
#line 156
            strcpy((char */* __restrict  */)(newxtn), (char const   */* __restrict  */)"");
            }
            }
#line 157
            goto __Cont;
          }
          {
          {
#line 160
          add_xtn(tmpxtn, newxtn);
          }
          {
#line 161
          memset((void *)(newxtn), '\000', (size_t )16);
          }
#line 162
          e = 0;
          }
        }
#line 164
        goto __Cont;
      }
      {
      {
#line 167
      tmp___5 = __ctype_b_loc();
      }
      }
#line 167
      if ((int const   )*(*tmp___5 + (int )after_dir[i]) & 16384) {
#line 167
        tmp___4 = e;
#line 167
        e ++;
#line 167
        newxtn[tmp___4] = after_dir[i];
      }
      __Cont: /* CIL Label */ 
#line 149
      i ++;
    }
    while_break___2: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
#line 169
    tmpdir->extns = tmpxtn;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 172
  return (head);
}
}
#line 181 "/home/khheo/testset/polymorph-0.4.0/rcfile.c"
void trim_whitespace(char *victim___0 ) 
{ 
  int i ;
  int j ;
  char new_str[2048] ;
  unsigned short const   **tmp ;
  int tmp___0 ;
  size_t tmp___1 ;
  void *__cil_tmp8 ;

  {
#line 185
  j = 0;
#line 187
  i = 0;
  {
  {
#line 187
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 187
    tmp___1 = strlen((char const   *)victim___0);
    }
    }
#line 187
    if (! ((size_t )i < tmp___1)) {
#line 187
      goto while_break;
    }
    {
    {
#line 188
    tmp = __ctype_b_loc();
    }
    }
#line 188
    if ((int const   )*(*tmp + (int )*(victim___0 + i)) & 8192) {
#line 188
      goto __Cont;
    }
#line 189
    tmp___0 = j;
#line 189
    j ++;
#line 189
    new_str[tmp___0] = *(victim___0 + i);
    __Cont: /* CIL Label */ 
#line 187
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
#line 192
  new_str[j] = (char )'\000';
  {
#line 193
  strcpy((char */* __restrict  */)victim___0, (char const   */* __restrict  */)(new_str));
  }
  }
#line 195
  return;
}
}
#line 471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 142 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) strcmp)(char const   *__s1 ,
                                                                                     char const   *__s2 )  __attribute__((__pure__)) ;
#line 7 "/home/khheo/testset/polymorph-0.4.0/llist.h"
xtn_t *find_last_xtn(xtn_t *target___0 ) ;
#line 8
polym_t *find_last_dir(polym_t *target___0 ) ;
#line 20 "/home/khheo/testset/polymorph-0.4.0/llist.c"
xtn_t *find_xtn(xtn_t *list , char *suspect ) 
{ 
  xtn_t *tmp ;
  int tmp___0 ;

  {
#line 23
  tmp = list;
  {
  {
#line 23
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 23
    if (! ((unsigned long )tmp != (unsigned long )((void *)0))) {
#line 23
      goto while_break;
    }
    {
    {
#line 24
    tmp___0 = strcmp((char const   *)(tmp->x3), (char const   *)suspect);
    }
    }
#line 24
    if (! tmp___0) {
#line 24
      goto while_break;
    }
#line 23
    tmp = (xtn_t *)tmp->next;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 27
  return (tmp);
}
}
#line 38 "/home/khheo/testset/polymorph-0.4.0/llist.c"
polym_t *find_dir(polym_t *list , char *suspect ) 
{ 
  polym_t *tmp ;
  int tmp___0 ;

  {
#line 41
  tmp = list;
  {
  {
#line 41
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 41
    if (! ((unsigned long )tmp != (unsigned long )((void *)0))) {
#line 41
      goto while_break;
    }
    {
    {
#line 42
    tmp___0 = strcmp((char const   *)(tmp->dest), (char const   *)suspect);
    }
    }
#line 42
    if (! tmp___0) {
#line 42
      goto while_break;
    }
#line 41
    tmp = (polym_t *)tmp->next;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 45
  return (tmp);
}
}
#line 57 "/home/khheo/testset/polymorph-0.4.0/llist.c"
polym_t *add_dir(polym_t *list , char *victim___0 ) 
{ 
  polym_t *tmp ;
  polym_t *last ;
  void *tmp___0 ;
  void *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;

  {
  {
  {
#line 61
  tmp___0 = malloc(sizeof(polym_t ));
  }
#line 61
  tmp = (polym_t *)tmp___0;
  }
#line 62
  if ((unsigned long )tmp == (unsigned long )((void *)0)) {
    {
    {
#line 63
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph ran out of memory while initializing\n");
    }
    {
#line 64
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"in the interest of saving files,\n");
    }
    {
#line 65
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
    }
    {
#line 66
    exit(3);
    }
    }
  }
  {
  {
#line 70
  strcpy((char */* __restrict  */)(tmp->dest), (char const   */* __restrict  */)victim___0);
  }
#line 71
  tmp->extns = (xtn_t *)((void *)0);
#line 72
  tmp->next = (struct polym_t *)((void *)0);
  {
#line 76
  last = find_last_dir(list);
  }
  }
#line 78
  if ((unsigned long )last == (unsigned long )((void *)0)) {
#line 79
    list = tmp;
  } else {
#line 81
    last->next = (struct polym_t *)tmp;
  }
#line 84
  return (tmp);
}
}
#line 94 "/home/khheo/testset/polymorph-0.4.0/llist.c"
xtn_t *add_xtn(xtn_t *list , char *victim___0 ) 
{ 
  xtn_t *tmp ;
  xtn_t *last ;
  void *tmp___0 ;
  void *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;

  {
  {
  {
#line 97
  tmp___0 = malloc(sizeof(xtn_t ));
  }
#line 97
  tmp = (xtn_t *)tmp___0;
  }
#line 98
  if ((unsigned long )tmp == (unsigned long )((void *)0)) {
    {
    {
#line 99
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph ran out of memory while initializing\n");
    }
    {
#line 100
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"in the interest of saving files,\n");
    }
    {
#line 101
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
    }
    {
#line 102
    exit(3);
    }
    }
  }
  {
  {
#line 105
  strcpy((char */* __restrict  */)(tmp->x3), (char const   */* __restrict  */)victim___0);
  }
#line 106
  tmp->next = (struct xtn_t *)((void *)0);
#line 108
  last = (xtn_t *)((void *)0);
  {
#line 109
  last = find_last_xtn(list);
  }
  }
#line 111
  if ((unsigned long )last == (unsigned long )((void *)0)) {
#line 112
    list = tmp;
  } else {
#line 114
    last->next = (struct xtn_t *)tmp;
  }
#line 117
  return (tmp);
}
}
#line 127 "/home/khheo/testset/polymorph-0.4.0/llist.c"
xtn_t *find_last_xtn(xtn_t *target___0 ) 
{ 
  xtn_t *run ;

  {
#line 130
  if ((unsigned long )target___0 == (unsigned long )((void *)0)) {
#line 130
    return ((xtn_t *)((void *)0));
  }
#line 132
  run = target___0;
  {
  {
#line 132
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 132
    if (! ((unsigned long )run != (unsigned long )((void *)0))) {
#line 132
      goto while_break;
    }
#line 133
    if ((unsigned long )run->next == (unsigned long )((void *)0)) {
#line 133
      return ((xtn_t *)run->next);
    }
#line 132
    run = (xtn_t *)run->next;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 136
  return ((xtn_t *)((void *)0));
}
}
#line 146 "/home/khheo/testset/polymorph-0.4.0/llist.c"
polym_t *find_last_dir(polym_t *target___0 ) 
{ 
  polym_t *run ;

  {
#line 149
  if ((unsigned long )target___0 == (unsigned long )((void *)0)) {
#line 149
    return ((polym_t *)((void *)0));
  }
#line 151
  run = target___0;
  {
  {
#line 151
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 151
    if (! ((unsigned long )run != (unsigned long )((void *)0))) {
#line 151
      goto while_break;
    }
#line 152
    if ((unsigned long )run->next == (unsigned long )((void *)0)) {
#line 152
      return ((polym_t *)run->next);
    }
#line 151
    run = (polym_t *)run->next;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 155
  return ((polym_t *)((void *)0));
}
}
#line 157 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int rename(char const   *__old , char const   *__new ) ;
#line 116 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) int tolower(int __c ) ;
#line 260 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) strrchr)(char const   *__s ,
                                                                                      int __c )  __attribute__((__pure__)) ;
#line 135 "/usr/include/dirent.h"
extern DIR *( __attribute__((__nonnull__(1))) opendir)(char const   *__name ) ;
#line 150
extern int ( __attribute__((__nonnull__(1))) closedir)(DIR *__dirp ) ;
#line 163
extern struct dirent *( __attribute__((__nonnull__(1))) readdir)(DIR *__dirp ) ;
#line 507 "/usr/include/unistd.h"
extern  __attribute__((__nothrow__)) char *getcwd(char *__buf , size_t __size ) ;
#line 59 "/usr/include/getopt.h"
extern char *optarg ;
#line 152
extern  __attribute__((__nothrow__)) int getopt(int ___argc , char * const  *___argv ,
                                                char const   *__shortopts ) ;
#line 209 "/usr/include/sys/stat.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) stat)(char const   * __restrict  __file ,
                                                                                   struct stat * __restrict  __buf ) ;
#line 263
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) lstat)(char const   * __restrict  __file ,
                                                                                    struct stat * __restrict  __buf ) ;
#line 3 "/home/khheo/testset/polymorph-0.4.0/polymorph.h"
int main(int argc , char **argv ) ;
#line 4
void grok_commandLine(int argc , char **argv ) ;
#line 5
void convert_fileName(char *original ) ;
#line 6
int does_newnameExist(char *suspect ) ;
#line 7
int does_nameHaveUppers(char *suspect ) ;
#line 8
int is_fileHidden(char *suspect ) ;
#line 23 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
char tmpbuf[2048]  ;
#line 23 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
char target[2048]  ;
#line 23 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
char wd[2048]  ;
#line 24 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
struct dirent *victim  ;
#line 25 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
struct stat status  ;
#line 26 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
DIR *curr_dir  ;
#line 27 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int hidden  =    0;
#line 28 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int track  =    0;
#line 29 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int clean  =    0;
#line 37 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int main(int argc , char **argv ) 
{ 
  char filename[2048] ;
  size_t tmp ;
  int tmp___0 ;
  int tmp___1 ;
  void *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;

  {
  {
  {
#line 40
  strcpy((char */* __restrict  */)(target), (char const   */* __restrict  */)"");
  }
  {
#line 42
  grok_commandLine(argc, argv);
  }
  {
#line 44
  tmp = strlen((char const   *)(target));
  }
  }
#line 44
  if (tmp != 0UL) {
    {
    {
#line 45
    convert_fileName(target);
    }
    }
#line 46
    return (0);
  }
  {
  {
#line 51
  strcpy((char */* __restrict  */)(wd), (char const   */* __restrict  */)"");
  }
  {
#line 52
  strcpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)"");
  }
  {
#line 54
  getcwd(wd, sizeof(wd));
  }
  {
#line 56
  curr_dir = opendir((char const   *)(wd));
  }
  }
#line 57
  if ((unsigned long )curr_dir == (unsigned long )((void *)0)) {
    {
    {
#line 58
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph could not open the current working directory\n");
    }
    {
#line 59
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"maybe you don\'t have permissions?\n");
    }
    {
#line 60
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
    }
    {
#line 61
    exit(1);
    }
    }
  }
  {
  {
#line 64
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 64
    victim = readdir(curr_dir);
    }
    }
#line 64
    if (! ((unsigned long )victim != (unsigned long )((void *)0))) {
#line 64
      goto while_break;
    }
#line 66
    if (track) {
      {
      {
#line 68
      tmp___0 = stat((char const   */* __restrict  */)(victim->d_name), (struct stat */* __restrict  */)(& status));
      }
      }
#line 68
      if (tmp___0 == -1) {
        {
        {
#line 69
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph encountered something funky\n");
        }
        {
#line 70
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
        }
        }
#line 71
        return (2);
      }
#line 73
      if ((status.st_mode & 61440U) == 32768U) {
        {
        {
#line 74
        strcpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)(victim->d_name));
        }
        {
#line 75
        convert_fileName(filename);
        }
        }
      }
    } else {
      {
      {
#line 80
      tmp___1 = lstat((char const   */* __restrict  */)(victim->d_name), (struct stat */* __restrict  */)(& status));
      }
      }
#line 80
      if (tmp___1 == -1) {
        {
        {
#line 81
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph encountered something funky\n");
        }
        {
#line 82
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
        }
        }
#line 83
        return (2);
      }
#line 85
      if ((status.st_mode & 61440U) == 32768U) {
        {
        {
#line 86
        strcpy((char */* __restrict  */)(filename), (char const   */* __restrict  */)(victim->d_name));
        }
        {
#line 87
        convert_fileName(filename);
        }
        }
      }
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 93
  closedir(curr_dir);
  }
  }
#line 95
  return (0);
}
}
#line 106 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
void grok_commandLine(int argc , char **argv ) 
{ 
  int o ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;

  {
  {
  {
#line 109
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 109
    o = getopt(argc, (char * const  *)argv, "achtvf:");
    }
    }
#line 109
    if (! (o != -1)) {
#line 109
      goto while_break;
    }
    {
#line 111
    if (o == 97) {
#line 111
      goto case_97;
    }
#line 114
    if (o == 99) {
#line 114
      goto case_99;
    }
#line 117
    if (o == 102) {
#line 117
      goto case_102;
    }
#line 120
    if (o == 104) {
#line 120
      goto case_104;
    }
#line 131
    if (o == 116) {
#line 131
      goto case_116;
    }
#line 134
    if (o == 118) {
#line 134
      goto case_118;
    }
#line 137
    goto switch_default;
    case_97: /* CIL Label */ 
#line 112
    hidden = 1;
#line 113
    goto switch_break;
    case_99: /* CIL Label */ 
#line 115
    clean = 1;
#line 116
    goto switch_break;
    case_102: /* CIL Label */ 
    {
    {
#line 118
    strcpy((char */* __restrict  */)(target), (char const   */* __restrict  */)optarg);
    }
    }
#line 119
    goto switch_break;
    case_104: /* CIL Label */ 
    {
    {
#line 121
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph v%s -- filename convertor\n",
            "0.4.0");
    }
    {
#line 122
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"written by Gerall Kahla.\n\n");
    }
    {
#line 123
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-a  all      convert hidden files\n");
    }
    {
#line 124
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-c\tclean\t\t reduce a file\'s name to just after the last backslash\n");
    }
    {
#line 125
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-f  file     convert this file to a name with all lowercase letters\n");
    }
    {
#line 126
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-h  help     print this message and exit\n");
    }
    {
#line 127
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-t  track    track down the targets of symlinks and convert them\n");
    }
    {
#line 128
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"-v  version  print the version number and exit\n");
    }
    {
#line 129
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\n");
    }
    {
#line 130
    exit(0);
    }
    }
    case_116: /* CIL Label */ 
#line 132
    track = 1;
#line 133
    goto switch_break;
    case_118: /* CIL Label */ 
    {
    {
#line 135
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph v%s\n",
            "0.4.0");
    }
    {
#line 136
    exit(0);
    }
    }
    switch_default: /* CIL Label */ 
    {
    {
#line 138
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"please run \'polymorph -h\' for commandline options\n");
    }
    {
#line 139
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
    }
    {
#line 140
    exit(0);
    }
    }
    switch_break: /* CIL Label */ ;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 144
  return;
}
}
#line 179 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
void convert_fileName(char *original ) 
{ 
  char newname[2048] ;
  char *bslash ;
  int i ;
  int error ;
  int tmp ;
  int tmp___0 ;
  unsigned short const   **tmp___1 ;
  size_t tmp___2 ;
  int tmp___3 ;
  void *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;

  {
  {
#line 184
  error = 0;
  {
#line 185
  strcpy((char */* __restrict  */)(newname), (char const   */* __restrict  */)"");
  }
  {
#line 187
  tmp = is_fileHidden(original);
  }
  }
#line 187
  if (tmp) {
#line 187
    if (! hidden) {
#line 187
      return;
    }
  }
  {
  {
#line 189
  tmp___3 = does_nameHaveUppers(original);
  }
  }
#line 189
  if (tmp___3) {
#line 191
    i = 0;
    {
    {
#line 191
    while (1) {
      while_continue___0: /* CIL Label */ ;
      while_continue: /* CIL Label */ ;
      {
      {
#line 191
      tmp___2 = strlen((char const   *)original);
      }
      }
#line 191
      if (! ((size_t )i < tmp___2)) {
#line 191
        goto while_break;
      }
      {
      {
#line 192
      tmp___1 = __ctype_b_loc();
      }
      }
#line 192
      if ((int const   )*(*tmp___1 + (int )*(original + i)) & 256) {
        {
        {
#line 193
        tmp___0 = tolower((int )*(original + i));
        }
#line 193
        newname[i] = (char )tmp___0;
        }
#line 194
        goto __Cont;
      }
#line 196
      newname[i] = *(original + i);
      __Cont: /* CIL Label */ 
#line 191
      i ++;
    }
    while_break___0: /* CIL Label */ ;
    }
    while_break: /* CIL Label */ ;
    }
#line 198
    newname[i] = (char )'\000';
  } else {
    {
    {
#line 200
    strcpy((char */* __restrict  */)(newname), (char const   */* __restrict  */)original);
    }
#line 201
    error = -1;
    }
  }
#line 206
  if (clean) {
    {
#line 207
    bslash = (char *)((void *)0);
    {
#line 208
    bslash = strrchr((char const   *)(newname), '\\');
    }
    }
#line 209
    if ((unsigned long )bslash != (unsigned long )((void *)0)) {
      {
      {
#line 209
      strcpy((char */* __restrict  */)(newname), (char const   */* __restrict  */)(bslash + 1));
      }
      }
    }
  }
#line 212
  if (error != -1) {
    {
    {
#line 213
    error = does_newnameExist(newname);
    }
    }
#line 214
    if (error) {
      {
      {
#line 215
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"target exists -- skipping %s...\n",
              original);
      }
      }
#line 216
      return;
    }
  }
  {
  {
#line 220
  error = rename((char const   *)original, (char const   *)(newname));
  }
  }
#line 221
  if (error) {
    {
    {
#line 222
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph had trouble converting %s to %s...\n",
            original, newname);
    }
    {
#line 226
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"the file is now possibly corrupt\n");
    }
    }
  }
  {
  {
#line 229
  strcpy((char */* __restrict  */)original, (char const   */* __restrict  */)(newname));
  }
  }
#line 231
  return;
}
}
#line 238 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int does_newnameExist(char *suspect ) 
{ 
  struct dirent *looking ;
  int found ;
  DIR *tmp ;
  int tmp___0 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;

  {
  {
  {
#line 243
  strcpy((char */* __restrict  */)(wd), (char const   */* __restrict  */)"");
  }
  {
#line 244
  getcwd(wd, sizeof(wd));
  }
  {
#line 246
  tmp = opendir((char const   *)(wd));
  }
  }
#line 248
  if ((unsigned long )tmp == (unsigned long )((void *)0)) {
    {
    {
#line 249
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph could not open the current working directory\n");
    }
    {
#line 250
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"maybe you don\'t have permissions?\n");
    }
    {
#line 251
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"polymorph terminated\n");
    }
    {
#line 252
    exit(1);
    }
    }
  }
#line 255
  found = 0;
  {
  {
#line 257
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 257
    looking = readdir(tmp);
    }
    }
#line 257
    if (! ((unsigned long )looking != (unsigned long )((void *)0))) {
#line 257
      goto while_break;
    }
    {
    {
#line 258
    tmp___0 = strcmp((char const   *)suspect, (char const   *)(looking->d_name));
    }
    }
#line 258
    if (! tmp___0) {
#line 258
      found = 1;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 261
  closedir(tmp);
  }
  }
#line 262
  return (found);
}
}
#line 272 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int does_nameHaveUppers(char *suspect ) 
{ 
  int i ;
  unsigned short const   **tmp ;
  size_t tmp___0 ;

  {
#line 275
  i = 0;
  {
  {
#line 275
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 275
    tmp___0 = strlen((char const   *)suspect);
    }
    }
#line 275
    if (! ((size_t )i < tmp___0)) {
#line 275
      goto while_break;
    }
    {
    {
#line 276
    tmp = __ctype_b_loc();
    }
    }
#line 276
    if ((int const   )*(*tmp + (int )*(suspect + i)) & 256) {
#line 276
      return (1);
    }
#line 275
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 279
  return (0);
}
}
#line 288 "/home/khheo/testset/polymorph-0.4.0/polymorph.c"
int is_fileHidden(char *suspect ) 
{ 


  {
#line 290
  if ((int )*(suspect + 0) == 46) {
#line 290
    return (1);
  }
#line 292
  return (0);
}
}
