/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 34 "../src/verbiste/c-api.h"
enum __anonenum_Verbiste_Mode_23 {
    VERBISTE_INVALID_MODE = 0,
    VERBISTE_INFINITIVE_MODE = 1,
    VERBISTE_INDICATIVE_MODE = 2,
    VERBISTE_CONDITIONAL_MODE = 3,
    VERBISTE_SUBJUNCTIVE_MODE = 4,
    VERBISTE_IMPERATIVE_MODE = 5,
    VERBISTE_PARTICIPLE_MODE = 6
} ;
#line 34 "../src/verbiste/c-api.h"
typedef enum __anonenum_Verbiste_Mode_23 Verbiste_Mode;
#line 46
enum __anonenum_Verbiste_Tense_24 {
    VERBISTE_INVALID_TENSE = 0,
    VERBISTE_PRESENT_TENSE = 1,
    VERBISTE_PAST_TENSE = 2,
    VERBISTE_IMPERFECT_TENSE = 3,
    VERBISTE_FUTURE_TENSE = 4
} ;
#line 46 "../src/verbiste/c-api.h"
typedef enum __anonenum_Verbiste_Tense_24 Verbiste_Tense;
#line 73 "../src/verbiste/c-api.h"
typedef char **Verbiste_InflectionArray;
#line 78 "../src/verbiste/c-api.h"
typedef Verbiste_InflectionArray *Verbiste_PersonArray;
#line 81 "../src/verbiste/c-api.h"
struct __anonstruct_Verbiste_ModeTense_26 {
   Verbiste_Mode mode ;
   Verbiste_Tense tense ;
};
#line 81 "../src/verbiste/c-api.h"
typedef struct __anonstruct_Verbiste_ModeTense_26 Verbiste_ModeTense;
#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 57 "../src/verbiste/c-api.h"
struct __anonstruct_Verbiste_ModeTensePersonNumber_25 {
   char *infinitive_verb ;
   Verbiste_Mode mode ;
   Verbiste_Tense tense ;
   int person ;
   int plural ;
   int correct ;
};
#line 57 "../src/verbiste/c-api.h"
typedef struct __anonstruct_Verbiste_ModeTensePersonNumber_25 Verbiste_ModeTensePersonNumber;
#line 339 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 363
extern  __attribute__((__nothrow__)) int ( /* format attribute */  snprintf)(char * __restrict  __s ,
                                                                             size_t __maxlen ,
                                                                             char const   * __restrict  __format 
                                                                             , ...) ;
#line 566 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) getenv)(char const   *__name ) ;
#line 88 "../src/verbiste/c-api.h"
extern Verbiste_ModeTense verbiste_valid_modes_and_tenses[] ;
#line 106
extern int verbiste_init(char const   *conjugation_filename , char const   *verbs_filename ) ;
#line 126
extern int verbiste_close(void) ;
#line 137
extern char *verbiste_tolower_latin1(char const   *latin1_string ) ;
#line 174
extern void verbiste_free_string(char *str ) ;
#line 182
extern char const   *verbiste_get_mode_name(Verbiste_Mode mode ) ;
#line 190
extern char const   *verbiste_get_tense_name(Verbiste_Tense tense ) ;
#line 228
extern Verbiste_PersonArray verbiste_conjugate(char const   *infinitive_verb , Verbiste_Mode const   mode ,
                                               Verbiste_Tense const   tense , int include_pronouns ) ;
#line 240
extern void verbiste_free_person_array(Verbiste_PersonArray array ) ;
#line 6 "/home/wslee/benchmarks/textformat/verbiste-0.1.28/examples/conjugator.c"
static int demo(char const   *latin1_infinitive ) 
{ 
  int k ;
  Verbiste_Mode mode ;
  Verbiste_Tense tense ;
  Verbiste_PersonArray person_array ;
  size_t i ;
  char *lower_latin1 ;
  char const   *tmp ;
  char const   *tmp___0 ;
  size_t j ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;

  {
#line 12
  k = 0;
  {
  {
#line 12
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 12
    if (! ((unsigned int )verbiste_valid_modes_and_tenses[k].mode != 0U)) {
#line 12
      goto while_break;
    }
    {
#line 16
    mode = verbiste_valid_modes_and_tenses[k].mode;
#line 17
    tense = verbiste_valid_modes_and_tenses[k].tense;
    {
#line 22
    lower_latin1 = verbiste_tolower_latin1(latin1_infinitive);
    }
    {
#line 23
    person_array = verbiste_conjugate((char const   *)lower_latin1, (Verbiste_Mode const   )mode,
                                      (Verbiste_Tense const   )tense, 0);
    }
    {
#line 24
    verbiste_free_string(lower_latin1);
    }
    }
#line 26
    if ((unsigned long )person_array == (unsigned long )((void *)0)) {
      {
      {
#line 28
      printf((char const   */* __restrict  */)"Unknown infinitive.\n");
      }
      }
#line 29
      return (1);
    }
    {
    {
#line 32
    tmp = verbiste_get_tense_name(tense);
    }
    {
#line 32
    tmp___0 = verbiste_get_mode_name(mode);
    }
    {
#line 32
    printf((char const   */* __restrict  */)"- %s %s:\n", tmp___0, tmp);
    }
#line 37
    i = (size_t )0;
    }
    {
    {
#line 37
    while (1) {
      while_continue___3: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
#line 37
      if (! ((unsigned long )*(person_array + i) != (unsigned long )((void *)0))) {
#line 37
        goto while_break___0;
      }
#line 41
      j = (size_t )0;
      {
      {
#line 41
      while (1) {
        while_continue___4: /* CIL Label */ ;
        while_continue___1: /* CIL Label */ ;
#line 41
        if (! ((unsigned long )*(*(person_array + i) + j) != (unsigned long )((void *)0))) {
#line 41
          goto while_break___1;
        }
#line 43
        if (j != 0U) {
          {
          {
#line 44
          printf((char const   */* __restrict  */)", ");
          }
          }
        }
        {
        {
#line 45
        printf((char const   */* __restrict  */)"%s", *(*(person_array + i) + j));
        }
#line 41
        j ++;
        }
      }
      while_break___4: /* CIL Label */ ;
      }
      while_break___1: /* CIL Label */ ;
      }
      {
      {
#line 47
      printf((char const   */* __restrict  */)"\n");
      }
#line 37
      i ++;
      }
    }
    while_break___3: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
    {
    {
#line 50
    verbiste_free_person_array(person_array);
    }
#line 12
    k ++;
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 52
  printf((char const   */* __restrict  */)"-\n");
  }
  }
#line 53
  return (0);
}
}
#line 57 "/home/wslee/benchmarks/textformat/verbiste-0.1.28/examples/conjugator.c"
int main(int argc , char **argv ) 
{ 
  char const   *libdatadir ;
  char conjFN[512] ;
  char verbsFN[512] ;
  int exit_status ;
  char *tmp ;
  void *__cil_tmp8 ;
  void *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;

  {
#line 63
  if (argc < 2) {
    {
    {
#line 65
    printf((char const   */* __restrict  */)"conjugator.c: demo of the C API of Verbiste\n");
    }
    {
#line 66
    printf((char const   */* __restrict  */)"Usage: conjugator VERB\n");
    }
    {
#line 67
    printf((char const   */* __restrict  */)"Note: this program expects Latin-1 and writes Latin-1.\n");
    }
    }
#line 68
    return (1);
  }
  {
  {
#line 71
  tmp = getenv("LIBDATADIR");
  }
#line 71
  libdatadir = (char const   *)tmp;
  }
#line 72
  if ((unsigned long )libdatadir == (unsigned long )((void *)0)) {
#line 73
    libdatadir = "/usr/local/share/verbiste-0.1";
  }
  {
  {
#line 75
  snprintf((char */* __restrict  */)(conjFN), (size_t )sizeof(conjFN), (char const   */* __restrict  */)"%s/conjugation-fr.xml",
           libdatadir);
  }
  {
#line 76
  snprintf((char */* __restrict  */)(verbsFN), (size_t )sizeof(verbsFN), (char const   */* __restrict  */)"%s/verbs-fr.xml",
           libdatadir);
  }
  {
#line 78
  verbiste_init((char const   *)(conjFN), (char const   *)(verbsFN));
  }
  {
#line 80
  exit_status = demo((char const   *)*(argv + 1));
  }
  {
#line 82
  verbiste_close();
  }
  }
#line 84
  return (exit_status);
}
}
#line 147 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 201 "../src/verbiste/c-api.h"
extern Verbiste_ModeTensePersonNumber *verbiste_deconjugate(char const   *verb ) ;
#line 210
extern void verbiste_free_mtpn_array(Verbiste_ModeTensePersonNumber *array ) ;
#line 6 "/home/wslee/benchmarks/textformat/verbiste-0.1.28/examples/conjugator.c"
static int demo___0(char const   *latin1_infinitive ) 
{ 
  int k ;
  Verbiste_Mode mode ;
  Verbiste_Tense tense ;
  Verbiste_PersonArray person_array ;
  size_t i ;
  char *lower_latin1 ;
  char const   *tmp ;
  char const   *tmp___0 ;
  size_t j ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;

  {
#line 12
  k = 0;
  {
  {
#line 12
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 12
    if (! ((unsigned int )verbiste_valid_modes_and_tenses[k].mode != 0U)) {
#line 12
      goto while_break;
    }
    {
#line 16
    mode = verbiste_valid_modes_and_tenses[k].mode;
#line 17
    tense = verbiste_valid_modes_and_tenses[k].tense;
    {
#line 22
    lower_latin1 = verbiste_tolower_latin1(latin1_infinitive);
    }
    {
#line 23
    person_array = verbiste_conjugate((char const   *)lower_latin1, (Verbiste_Mode const   )mode,
                                      (Verbiste_Tense const   )tense, 0);
    }
    {
#line 24
    verbiste_free_string(lower_latin1);
    }
    }
#line 26
    if ((unsigned long )person_array == (unsigned long )((void *)0)) {
      {
      {
#line 28
      printf((char const   */* __restrict  */)"Unknown infinitive.\n");
      }
      }
#line 29
      return (1);
    }
    {
    {
#line 32
    tmp = verbiste_get_tense_name(tense);
    }
    {
#line 32
    tmp___0 = verbiste_get_mode_name(mode);
    }
    {
#line 32
    printf((char const   */* __restrict  */)"- %s %s:\n", tmp___0, tmp);
    }
#line 37
    i = (size_t )0;
    }
    {
    {
#line 37
    while (1) {
      while_continue___3: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
#line 37
      if (! ((unsigned long )*(person_array + i) != (unsigned long )((void *)0))) {
#line 37
        goto while_break___0;
      }
#line 41
      j = (size_t )0;
      {
      {
#line 41
      while (1) {
        while_continue___4: /* CIL Label */ ;
        while_continue___1: /* CIL Label */ ;
#line 41
        if (! ((unsigned long )*(*(person_array + i) + j) != (unsigned long )((void *)0))) {
#line 41
          goto while_break___1;
        }
#line 43
        if (j != 0U) {
          {
          {
#line 44
          printf((char const   */* __restrict  */)", ");
          }
          }
        }
        {
        {
#line 45
        printf((char const   */* __restrict  */)"%s", *(*(person_array + i) + j));
        }
#line 41
        j ++;
        }
      }
      while_break___4: /* CIL Label */ ;
      }
      while_break___1: /* CIL Label */ ;
      }
      {
      {
#line 47
      printf((char const   */* __restrict  */)"\n");
      }
#line 37
      i ++;
      }
    }
    while_break___3: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
    {
    {
#line 50
    verbiste_free_person_array(person_array);
    }
#line 12
    k ++;
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 52
  printf((char const   */* __restrict  */)"-\n");
  }
  }
#line 53
  return (0);
}
}
