/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 25 "/usr/include/bits/termios.h"
typedef unsigned char cc_t;
#line 26 "/usr/include/bits/termios.h"
typedef unsigned int speed_t;
#line 27 "/usr/include/bits/termios.h"
typedef unsigned int tcflag_t;
#line 30 "/usr/include/bits/termios.h"
struct termios {
   tcflag_t c_iflag ;
   tcflag_t c_oflag ;
   tcflag_t c_cflag ;
   tcflag_t c_lflag ;
   cc_t c_line ;
   cc_t c_cc[32] ;
   speed_t c_ispeed ;
   speed_t c_ospeed ;
};
#line 57 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/termstate.h"
typedef struct termios termstate;
#line 211 "/usr/lib/gcc/i486-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned int size_t;
#line 52 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/arglist.h"
struct alist {
   int alloc ;
   int argc ;
   char **argv ;
};
#line 52 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/arglist.h"
typedef struct alist arglist;
#line 56 "/usr/include/bits/types.h"
typedef long long __quad_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/bits/types.h"
typedef __quad_t __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 84 "/usr/include/signal.h"
typedef void (*__sighandler_t)(int  );
#line 67 "/usr/include/termios.h"
extern  __attribute__((__nothrow__)) int tcgetattr(int __fd , struct termios *__termios_p ) ;
#line 71
extern  __attribute__((__nothrow__)) int tcsetattr(int __fd , int __optional_actions ,
                                                   struct termios  const  *__termios_p ) ;
#line 795 "/usr/include/unistd.h"
extern  __attribute__((__nothrow__)) int isatty(int __fd ) ;
#line 77 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/termstate.h"
int save_termstate(int fd , termstate *state ) ;
#line 94
int restore_termstate(int fd , termstate *state ) ;
#line 109
void raw_termstate(termstate *state ) ;
#line 73 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/termstate.c"
int save_termstate(int fd , termstate *state ) 
{ 
  int tmp ;
  int tmp___0 ;

  {
  {
  {
#line 75
  tmp = isatty(fd);
  }
  }
#line 75
  if (! tmp) {
#line 75
    return (25);
  }
  {
  {
#line 82
  tmp___0 = tcgetattr(fd, state);
  }
  }
#line 82
  return (tmp___0);
}
}
#line 102 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/termstate.c"
int restore_termstate(int fd , termstate *state ) 
{ 
  int tmp ;
  int tmp___0 ;

  {
  {
  {
#line 104
  tmp = isatty(fd);
  }
  }
#line 104
  if (! tmp) {
#line 104
    return (25);
  }
  {
  {
#line 111
  tmp___0 = tcsetattr(fd, 1, (struct termios  const  *)state);
  }
  }
#line 111
  return (tmp___0);
}
}
#line 129 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/termstate.c"
void raw_termstate(termstate *state ) 
{ 


  {
#line 135
  state->c_oflag |= 1U;
#line 138
  return;
}
}
#line 471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 485
extern  __attribute__((__nothrow__)) void *( __attribute__((__warn_unused_result__)) realloc)(void *__ptr ,
                                                                                              size_t __size ) ;
#line 488
extern  __attribute__((__nothrow__)) void free(void *__ptr ) ;
#line 346 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(2))) strtok)(char * __restrict  __s ,
                                                                                     char const   * __restrict  __delim ) ;
#line 78 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/arglist.h"
int string2arglist(char *string , arglist *args ) ;
#line 94
int argv2arglist(int argc , char **argv , arglist *args ) ;
#line 67 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/arglist.c"
int string2arglist(char *string , arglist *args ) 
{ 
  char *st ;
  void *tmp ;
  void *tmp___0 ;
  char *tmp___1 ;
  char *__cil_tmp7 ;

  {
#line 72
  if (args->argv) {
    {
    {
#line 72
    free((void *)args->argv);
    }
    }
  }
#line 73
  args->argc = 1;
#line 74
  args->alloc = 0;
#line 76
  st = string;
  {
  {
#line 78
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 81
    if (args->argc >= args->alloc) {
#line 83
      if (! args->argv) {
        {
        {
#line 84
        tmp = malloc((size_t )(40UL * sizeof(char *)));
        }
#line 84
        args->argv = (char **)tmp;
        }
      } else {
        {
        {
#line 86
        tmp___0 = realloc((void *)args->argv, (size_t )((unsigned long )(args->alloc + 40) * sizeof(char *)));
        }
#line 86
        args->argv = (char **)tmp___0;
        }
      }
#line 88
      if ((unsigned long )args->argv == (unsigned long )((void *)0)) {
#line 88
        return (12);
      }
#line 89
      args->alloc += 40;
    }
    {
    {
#line 93
    tmp___1 = strtok((char */* __restrict  */)st, (char const   */* __restrict  */)"\t ");
    }
#line 93
    *(args->argv + args->argc) = tmp___1;
    }
#line 93
    if (! tmp___1) {
#line 93
      goto while_break;
    }
#line 96
    st = (char *)((void *)0);
#line 98
    (args->argc) ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 100
  return (0);
}
}
#line 117 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/arglist.c"
int argv2arglist(int argc , char **argv , arglist *args ) 
{ 
  int i ;
  void *tmp ;

  {
#line 122
  if (args->argv) {
    {
    {
#line 122
    free((void *)args->argv);
    }
    }
  }
  {
  {
#line 124
  tmp = malloc((size_t )((unsigned long )(argc + 1) * sizeof(char *)));
  }
#line 124
  args->argv = (char **)tmp;
  }
#line 125
  if (! args->argv) {
#line 125
    return (12);
  }
#line 127
  args->alloc = argc;
#line 129
  i = 0;
  {
  {
#line 129
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 129
    if (! (i < argc)) {
#line 129
      goto while_break;
    }
#line 131
    *(args->argv + (i + 1)) = *(argv + (i + 1));
#line 129
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 133
  args->argc = argc;
#line 135
  return (0);
}
}
#line 81 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) unsigned short const   **__ctype_b_loc(void)  __attribute__((__const__)) ;
#line 119
extern  __attribute__((__nothrow__)) int toupper(int __c ) ;
#line 184 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) long ( __attribute__((__nonnull__(1))) strtol)(char const   * __restrict  __nptr ,
                                                                                    char ** __restrict  __endptr ,
                                                                                    int __base ) ;
#line 58 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/escape.h"
char *escape(char *source ) ;
#line 63 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/escape.c"
char *escape(char *source ) 
{ 
  char *dest ;
  char *probe ;
  long l ;
  unsigned short const   **tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 69
  if (! source) {
#line 69
    return ((char *)((void *)0));
  }
#line 70
  dest = source;
#line 72
  probe = source;
  {
  {
#line 72
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 72
    if (! *probe) {
#line 72
      goto while_break;
    }
#line 75
    if ((int )*probe == 34) {
#line 75
      goto __Cont;
    }
#line 77
    if ((int )*probe != 92) {
#line 79
      *dest = *probe;
#line 80
      dest ++;
#line 81
      goto __Cont;
    }
#line 84
    probe ++;
    {
#line 87
    if ((int )*probe == 97) {
#line 87
      goto case_97;
    }
#line 88
    if ((int )*probe == 98) {
#line 88
      goto case_98;
    }
#line 89
    if ((int )*probe == 102) {
#line 89
      goto case_102;
    }
#line 90
    if ((int )*probe == 110) {
#line 90
      goto case_110;
    }
#line 91
    if ((int )*probe == 114) {
#line 91
      goto case_114;
    }
#line 92
    if ((int )*probe == 116) {
#line 92
      goto case_116;
    }
#line 93
    if ((int )*probe == 118) {
#line 93
      goto case_118;
    }
#line 97
    if ((int )*probe == 63) {
#line 97
      goto case_63;
    }
#line 97
    if ((int )*probe == 34) {
#line 97
      goto case_63;
    }
#line 97
    if ((int )*probe == 39) {
#line 97
      goto case_63;
    }
#line 97
    if ((int )*probe == 92) {
#line 97
      goto case_63;
    }
#line 98
    if ((int )*probe == 48) {
#line 98
      goto case_48;
    }
#line 113
    if ((int )*probe == 57) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 56) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 55) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 54) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 53) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 52) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 51) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 50) {
#line 113
      goto case_57;
    }
#line 113
    if ((int )*probe == 49) {
#line 113
      goto case_57;
    }
#line 121
    if ((int )*probe == 120) {
#line 121
      goto case_120;
    }
#line 121
    if ((int )*probe == 88) {
#line 121
      goto case_120;
    }
#line 133
    goto switch_default;
    case_97: /* CIL Label */ 
#line 87
    *dest = (char )'\a';
#line 87
    dest ++;
#line 87
    goto switch_break;
    case_98: /* CIL Label */ 
#line 88
    *dest = (char )'\b';
#line 88
    dest ++;
#line 88
    goto switch_break;
    case_102: /* CIL Label */ 
#line 89
    *dest = (char )'\f';
#line 89
    dest ++;
#line 89
    goto switch_break;
    case_110: /* CIL Label */ 
#line 90
    *dest = (char )'\n';
#line 90
    dest ++;
#line 90
    goto switch_break;
    case_114: /* CIL Label */ 
#line 91
    *dest = (char )'\r';
#line 91
    dest ++;
#line 91
    goto switch_break;
    case_116: /* CIL Label */ 
#line 92
    *dest = (char )'\t';
#line 92
    dest ++;
#line 92
    goto switch_break;
    case_118: /* CIL Label */ 
#line 93
    *dest = (char )'\v';
#line 93
    dest ++;
#line 93
    goto switch_break;
    case_63: /* CIL Label */ 
    case_34: /* CIL Label */ 
    case_39: /* CIL Label */ 
    case_92: /* CIL Label */ 
#line 97
    *dest = *probe;
#line 97
    dest ++;
#line 97
    goto switch_break;
    case_48: /* CIL Label */ 
    {
    {
#line 99
    l = strtol((char const   */* __restrict  */)probe, (char **/* __restrict  */)(& probe),
               8);
    }
#line 100
    *dest = (char )l;
#line 101
    dest ++;
#line 102
    probe --;
    }
#line 103
    goto switch_break;
    case_57: /* CIL Label */ 
    case_56: /* CIL Label */ 
    case_55: /* CIL Label */ 
    case_54: /* CIL Label */ 
    case_53: /* CIL Label */ 
    case_52: /* CIL Label */ 
    case_51: /* CIL Label */ 
    case_50: /* CIL Label */ 
    case_49: /* CIL Label */ 
    {
    {
#line 114
    l = strtol((char const   */* __restrict  */)probe, (char **/* __restrict  */)(& probe),
               10);
    }
#line 115
    *dest = (char )l;
#line 116
    dest ++;
#line 117
    probe --;
    }
#line 118
    goto switch_break;
    case_120: /* CIL Label */ 
    case_88: /* CIL Label */ 
    {
    {
#line 123
    tmp = __ctype_b_loc();
    }
    }
#line 123
    if (! ((int const   )*(*tmp + (int )*(probe + 1)) & 2048)) {
      {
      {
#line 123
      tmp___0 = toupper((int )*(probe + 1));
      }
      }
#line 123
      if (tmp___0 > 70) {
#line 126
        return ((char *)((void *)0));
      } else {
        {
        {
#line 123
        tmp___1 = toupper((int )*(probe + 1));
        }
        }
#line 123
        if (tmp___1 < 65) {
#line 126
          return ((char *)((void *)0));
        }
      }
    }
    {
    {
#line 127
    l = strtol((char const   */* __restrict  */)probe, (char **/* __restrict  */)(& probe),
               16);
    }
#line 128
    *dest = (char )l;
#line 129
    dest ++;
#line 130
    probe --;
    }
#line 131
    goto switch_break;
    switch_default: /* CIL Label */ 
#line 133
    return ((char *)((void *)0));
    switch_break: /* CIL Label */ ;
    }
    __Cont: /* CIL Label */ 
#line 72
    probe ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 136
  *dest = (char )'\000';
#line 137
  return (source);
}
}
#line 145 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin ;
#line 146
extern struct _IO_FILE *stdout ;
#line 147
extern struct _IO_FILE *stderr ;
#line 214
extern int fclose(FILE *__stream ) ;
#line 219
extern int fflush(FILE *__stream ) ;
#line 249
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 333
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 513
extern int fgetc(FILE *__stream ) ;
#line 555
extern int fputc(int __c , FILE *__stream ) ;
#line 604
extern char *fgets(char * __restrict  __s , int __n , FILE * __restrict  __stream ) ;
#line 831
extern  __attribute__((__nothrow__)) int fileno(FILE *__stream ) ;
#line 513 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 566
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) getenv)(char const   *__name ) ;
#line 43 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2))) memcpy)(void * __restrict  __dest ,
                                                                                       void const   * __restrict  __src ,
                                                                                       size_t __n ) ;
#line 127
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2))) strcpy)(char * __restrict  __dest ,
                                                                                       char const   * __restrict  __src ) ;
#line 142
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) strcmp)(char const   *__s1 ,
                                                                                     char const   *__s2 )  __attribute__((__pure__)) ;
#line 233
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) strchr)(char const   *__s ,
                                                                                     int __c )  __attribute__((__pure__)) ;
#line 260
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1))) strrchr)(char const   *__s ,
                                                                                      int __c )  __attribute__((__pure__)) ;
#line 397
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1))) strlen)(char const   *__s )  __attribute__((__pure__)) ;
#line 101 "/usr/include/signal.h"
extern  __attribute__((__nothrow__)) __sighandler_t signal(int __sig , void (*__handler)(int  ) ) ;
#line 83 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
extern char *optarg ;
#line 84
extern int optind ;
#line 87 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *ptr_on  =    (char *)"\033[5i";
#line 88 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *ptr_off  =    (char *)"\033[4i";
#line 91 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *termname  =    (char *)"";
#line 92 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *libtermname  =    (char *)"/etc/vtprintcap";
#line 93 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *devname  =    (char *)"/dev/tty";
#line 94 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
char *vtbasename  =    (char *)"";
#line 97 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int quiet  =    0;
#line 98 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int binary  =    0;
#line 99 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int ffeed  =    1;
#line 100 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int device  =    0;
#line 101 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int stripcr  =    0;
#line 102 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int addcr  =    0;
#line 103 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int builtin  =    0;
#line 104 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int forcenv  =    0;
#line 105 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int dowork  =    1;
#line 108 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int state_saved  =    0;
#line 109 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
termstate oldstate  ;
#line 110 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
termstate newstate  ;
#line 113 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
FILE *outfile  ;
#line 117
void sighandler(int signum ) ;
#line 118
int process_opts(arglist *args ) ;
#line 119
void help(void) ;
#line 120
void license(void) ;
#line 121
void warranty(void) ;
#line 122
void intro(void) ;
#line 140 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
void sighandler(int signum ) 
{ 
  char *signame ;
  int tmp ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;

  {
  {
  {
#line 144
  fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)"%s",
          ptr_off);
  }
  {
#line 145
  fflush(outfile);
  }
  }
#line 146
  if (state_saved) {
    {
    {
#line 146
    tmp = fileno(outfile);
    }
    {
#line 146
    restore_termstate(tmp, & oldstate);
    }
    }
  }
#line 148
  if (! quiet) {
    {
#line 152
    if (signum == 1) {
#line 152
      goto case_1;
    }
#line 153
    if (signum == 2) {
#line 153
      goto case_2;
    }
#line 154
    if (signum == 3) {
#line 154
      goto case_3;
    }
#line 155
    if (signum == 15) {
#line 155
      goto case_15;
    }
#line 156
    if (signum == 20) {
#line 156
      goto case_20;
    }
#line 157
    goto switch_default;
    case_1: /* CIL Label */ 
#line 152
    signame = (char *)"hangup";
#line 152
    goto switch_break;
    case_2: /* CIL Label */ 
#line 153
    signame = (char *)"interrupt";
#line 153
    goto switch_break;
    case_3: /* CIL Label */ 
#line 154
    signame = (char *)"quit";
#line 154
    goto switch_break;
    case_15: /* CIL Label */ 
#line 155
    signame = (char *)"terminate";
#line 155
    goto switch_break;
    case_20: /* CIL Label */ 
#line 156
    signame = (char *)"keyboard stop";
#line 156
    goto switch_break;
    switch_default: /* CIL Label */ 
#line 157
    signame = (char *)"unknown";
#line 157
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
    {
    {
#line 159
    fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)"\nCaught %s signal!  Exiting vtprint.\n",
            signame);
    }
    }
  }
  {
  {
#line 161
  exit(1);
  }
  }
}
}
#line 188
extern int ( /* missing proto */  getopt)() ;
#line 178 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int process_opts(arglist *args ) 
{ 
  int c ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;

  {
#line 182
  optind = 1;
#line 184
  *(args->argv + 0) = vtbasename;
  {
  {
#line 186
  while (1) {
    while_continue___0: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 188
    c = getopt(args->argc, args->argv, "hwlvdDbBcCeEfFnNqQT:tL:V:");
    }
    }
    {
#line 191
    if (c == 104) {
#line 191
      goto case_104;
    }
#line 192
    if (c == 119) {
#line 192
      goto case_119;
    }
#line 193
    if (c == 108) {
#line 193
      goto case_108;
    }
#line 194
    if (c == 118) {
#line 194
      goto case_118;
    }
#line 196
    if (c == 100) {
#line 196
      goto case_100;
    }
#line 197
    if (c == 68) {
#line 197
      goto case_68;
    }
#line 198
    if (c == 98) {
#line 198
      goto case_98;
    }
#line 199
    if (c == 66) {
#line 199
      goto case_66;
    }
#line 200
    if (c == 99) {
#line 200
      goto case_99;
    }
#line 201
    if (c == 67) {
#line 201
      goto case_67;
    }
#line 202
    if (c == 101) {
#line 202
      goto case_101;
    }
#line 203
    if (c == 69) {
#line 203
      goto case_69;
    }
#line 204
    if (c == 102) {
#line 204
      goto case_102;
    }
#line 205
    if (c == 70) {
#line 205
      goto case_70;
    }
#line 206
    if (c == 110) {
#line 206
      goto case_110;
    }
#line 207
    if (c == 78) {
#line 207
      goto case_78;
    }
#line 208
    if (c == 113) {
#line 208
      goto case_113;
    }
#line 209
    if (c == 81) {
#line 209
      goto case_81;
    }
#line 210
    if (c == 116) {
#line 210
      goto case_116;
    }
#line 215
    if (c == 84) {
#line 215
      goto case_84;
    }
#line 219
    if (c == 76) {
#line 219
      goto case_76;
    }
#line 223
    if (c == 86) {
#line 223
      goto case_86;
    }
#line 228
    if (c == 63) {
#line 228
      goto case_63;
    }
#line 189
    goto switch_break;
    case_104: /* CIL Label */ 
    {
    {
#line 191
    help();
    }
#line 191
    dowork = 0;
    }
#line 191
    goto switch_break;
    case_119: /* CIL Label */ 
    {
    {
#line 192
    warranty();
    }
#line 192
    dowork = 0;
    }
#line 192
    goto switch_break;
    case_108: /* CIL Label */ 
    {
    {
#line 193
    license();
    }
#line 193
    dowork = 0;
    }
#line 193
    goto switch_break;
    case_118: /* CIL Label */ 
    {
    {
#line 194
    intro();
    }
#line 194
    dowork = 0;
    }
#line 194
    goto switch_break;
    case_100: /* CIL Label */ 
#line 196
    device = 1;
#line 196
    goto switch_break;
    case_68: /* CIL Label */ 
#line 197
    device = 0;
#line 197
    goto switch_break;
    case_98: /* CIL Label */ 
#line 198
    binary = 1;
#line 198
    goto switch_break;
    case_66: /* CIL Label */ 
#line 199
    binary = 0;
#line 199
    goto switch_break;
    case_99: /* CIL Label */ 
#line 200
    stripcr = 0;
#line 200
    addcr = 1;
#line 200
    goto switch_break;
    case_67: /* CIL Label */ 
#line 201
    stripcr = 0;
#line 201
    addcr = 0;
#line 201
    goto switch_break;
    case_101: /* CIL Label */ 
#line 202
    builtin = 1;
#line 202
    forcenv = 0;
#line 202
    goto switch_break;
    case_69: /* CIL Label */ 
#line 203
    builtin = 0;
#line 203
    forcenv = 0;
#line 203
    goto switch_break;
    case_102: /* CIL Label */ 
#line 204
    ffeed = 0;
#line 204
    goto switch_break;
    case_70: /* CIL Label */ 
#line 205
    ffeed = 1;
#line 205
    goto switch_break;
    case_110: /* CIL Label */ 
#line 206
    addcr = 0;
#line 206
    stripcr = 1;
#line 206
    goto switch_break;
    case_78: /* CIL Label */ 
#line 207
    addcr = 0;
#line 207
    stripcr = 0;
#line 207
    goto switch_break;
    case_113: /* CIL Label */ 
#line 208
    quiet = 1;
#line 208
    goto switch_break;
    case_81: /* CIL Label */ 
#line 209
    quiet = 0;
#line 209
    goto switch_break;
    case_116: /* CIL Label */ 
    {
#line 211
    forcenv = 1;
    {
#line 212
    termname = getenv("TERM");
    }
    }
#line 213
    goto switch_break;
    case_84: /* CIL Label */ 
#line 216
    termname = optarg;
#line 217
    goto switch_break;
    case_76: /* CIL Label */ 
#line 220
    libtermname = optarg;
#line 221
    goto switch_break;
    case_86: /* CIL Label */ 
#line 224
    devname = optarg;
#line 225
    device = 1;
#line 226
    goto switch_break;
    case_63: /* CIL Label */ 
    {
    {
#line 228
    help();
    }
    {
#line 228
    exit(1);
    }
    }
    switch_break: /* CIL Label */ ;
    }
#line 186
    if (! (c != -1)) {
#line 186
      goto while_break;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 231
  return (optind);
}
}
#line 246 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
void help(void) 
{ 
  int tmp ;
  int tmp___0 ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;

  {
  {
  {
#line 248
  tmp = strcmp((char const   *)vtbasename, "vtprton");
  }
  }
#line 248
  if (tmp) {
    {
    {
#line 248
    tmp___0 = strcmp((char const   *)vtbasename, "vtprtoff");
    }
    }
#line 248
    if (tmp___0) {
      {
      {
#line 252
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Usage: %s [ -bBcCdDeEfFhlnNqQtvW ] [ -L vtprintcap ] [ -T termtype ] [ -V device ] [ filename... ]\n",
              vtbasename);
      }
      }
    } else {
      {
      {
#line 249
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Usage: %s [ -dDeEhlqQNtvw ] [ -L vtprintcap ] [ -T termtype ] [ -V device ]\n",
              vtbasename);
      }
      }
    }
  } else {
    {
    {
#line 249
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Usage: %s [ -dDeEhlqQNtvw ] [ -L vtprintcap ] [ -T termtype ] [ -V device ]\n",
            vtbasename);
    }
    }
  }
  {
  {
#line 256
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\nPlease see the %s(%s) manual page for more\n",
          vtbasename, "1");
  }
  {
#line 259
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"information about the meaning of these options.\n");
  }
  }
#line 260
  return;
}
}
#line 274 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
void intro(void) 
{ 
  char *__cil_tmp1 ;
  char *__cil_tmp2 ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;

  {
  {
  {
#line 276
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\n*** %s (v%s) ***\n\n",
          vtbasename, "2.0.2");
  }
  {
#line 277
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Copyright 1993-1994, Garrett D\'Amore\n");
  }
  {
#line 278
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Last revised %s.\n\n",
          "October-25-1994");
  }
  {
#line 279
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"NO WARRANTY!  Use \"%s -w\" for info.\n",
          vtbasename);
  }
  {
#line 281
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Freely redistributable.  Use \"%s -l\" for info.\n\n",
          vtbasename);
  }
  }
#line 284
  return;
}
}
#line 287 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
void warranty(void) 
{ 
  char *__cil_tmp1 ;
  char *__cil_tmp2 ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;

  {
  {
  {
#line 289
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: This program is provided entirely without\n",
          vtbasename);
  }
  {
#line 291
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: warranty!  The user agrees to indemnify the\n",
          vtbasename);
  }
  {
#line 293
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: author from any claim of damage or loss that\n",
          vtbasename);
  }
  {
#line 295
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: may result from the use of or inability to\n",
          vtbasename);
  }
  {
#line 297
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: use this program.\n\n",
          vtbasename);
  }
  }
#line 298
  return;
}
}
#line 300 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
void license(void) 
{ 
  char *__cil_tmp1 ;
  char *__cil_tmp2 ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;

  {
  {
  {
#line 302
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: This program is copyrighted material.  The user\n",
          vtbasename);
  }
  {
#line 304
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: is given the non-exclusive right to use, modify\n",
          vtbasename);
  }
  {
#line 306
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: and redistribute this program or any derived\n",
          vtbasename);
  }
  {
#line 308
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: work, subject to the following limitation:\n\n",
          vtbasename);
  }
  {
#line 310
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: All copyright notices and warranty disclaimers\n",
          vtbasename);
  }
  {
#line 312
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: must be left intact!  The user may not claim \n",
          vtbasename);
  }
  {
#line 314
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: credit for code written by the author.\n\n",
          vtbasename);
  }
  }
#line 316
  return;
}
}
#line 337 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
static char on[1025]  ;
#line 338 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
static char off[1025]  ;
#line 333 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int vtprintcap(void) 
{ 
  FILE *libfile ;
  char buffer[1025] ;
  char *temp ;
  int tmp ;
  char *tmp___0 ;
  char *tmp___1 ;
  char *tmp___2 ;
  size_t tmp___3 ;
  size_t tmp___4 ;
  size_t tmp___5 ;
  size_t tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  void *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;

  {
#line 339
  temp = (char *)((void *)0);
#line 341
  if (! termname) {
    {
    {
#line 341
    termname = getenv("TERM");
    }
    }
  } else
#line 341
  if (! *termname) {
    {
    {
#line 341
    termname = getenv("TERM");
    }
    }
  }
  {
  {
#line 343
  libfile = fopen((char const   */* __restrict  */)libtermname, (char const   */* __restrict  */)"r");
  }
  }
#line 344
  if (! libfile) {
#line 344
    return (-1);
  }
  {
  {
#line 346
  while (1) {
    while_continue___3: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 346
    tmp___0 = fgets((char */* __restrict  */)(buffer), 1024, (FILE */* __restrict  */)libfile);
    }
    }
#line 346
    if (! tmp___0) {
#line 346
      goto while_break;
    }
#line 348
    if ((int )buffer[0] == 35) {
#line 348
      buffer[0] = (char )'\000';
    }
    {
    {
#line 349
    temp = strchr((char const   *)(buffer), '\n');
    }
    }
#line 350
    if (temp) {
#line 350
      *temp = (char )'\000';
    }
    {
    {
#line 352
    temp = strtok((char */* __restrict  */)(buffer), (char const   */* __restrict  */)", \t");
    }
    }
    {
    {
#line 353
    while (1) {
      while_continue___4: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
#line 353
      if (! temp) {
#line 353
        goto while_break___0;
      }
      {
      {
#line 355
      tmp = strcmp((char const   *)temp, (char const   *)termname);
      }
      }
#line 355
      if (! tmp) {
#line 355
        goto while_break___0;
      }
      {
      {
#line 356
      temp = strtok((char */* __restrict  */)((void *)0), (char const   */* __restrict  */)", \t");
      }
      }
    }
    while_break___4: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
#line 358
    if (temp) {
#line 358
      goto while_break;
    }
  }
  while_break___3: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 360
  if (temp) {
    {
    {
#line 362
    tmp___1 = fgets((char */* __restrict  */)(on), 1025, (FILE */* __restrict  */)libfile);
    }
    }
#line 362
    if (! tmp___1) {
      {
      {
#line 364
      fclose(libfile);
      }
      }
#line 365
      return (-2);
    }
    {
    {
#line 367
    tmp___2 = fgets((char */* __restrict  */)(off), 1025, (FILE */* __restrict  */)libfile);
    }
    }
#line 367
    if (! tmp___2) {
      {
      {
#line 369
      fclose(libfile);
      }
      }
#line 370
      return (-2);
    }
    {
    {
#line 373
    fclose(libfile);
    }
    {
#line 377
    tmp___4 = strlen((char const   *)(on));
    }
    }
#line 377
    if ((int )on[tmp___4 - 1U] == 10) {
      {
      {
#line 377
      tmp___3 = strlen((char const   *)(on));
      }
#line 377
      on[tmp___3 - 1U] = (char )'\000';
      }
    }
    {
    {
#line 378
    tmp___6 = strlen((char const   *)(off));
    }
    }
#line 378
    if ((int )off[tmp___6 - 1U] == 10) {
      {
      {
#line 378
      tmp___5 = strlen((char const   *)(off));
      }
#line 378
      off[tmp___5 - 1U] = (char )'\000';
      }
    }
#line 380
    temp = on;
    {
    {
#line 381
    while (1) {
      while_continue___5: /* CIL Label */ ;
      while_continue___1: /* CIL Label */ ;
#line 381
      if (! temp) {
#line 381
        goto while_break___1;
      }
      {
      {
#line 383
      temp = strchr((char const   *)temp, '%');
      }
      }
#line 384
      if (temp) {
#line 386
        if ((int )*(temp + 1) != 37) {
#line 386
          return (-2);
        }
#line 387
        temp += 2;
      }
    }
    while_break___5: /* CIL Label */ ;
    }
    while_break___1: /* CIL Label */ ;
    }
#line 390
    temp = off;
    {
    {
#line 391
    while (1) {
      while_continue___6: /* CIL Label */ ;
      while_continue___2: /* CIL Label */ ;
#line 391
      if (! temp) {
#line 391
        goto while_break___2;
      }
      {
      {
#line 393
      temp = strchr((char const   *)temp, '%');
      }
      }
#line 394
      if (temp) {
#line 396
        if ((int )*(temp + 1) != 37) {
#line 396
          return (-2);
        }
#line 397
        temp += 2;
      }
    }
    while_break___6: /* CIL Label */ ;
    }
    while_break___2: /* CIL Label */ ;
    }
    {
    {
#line 401
    tmp___7 = (int )escape(on);
    }
    }
#line 401
    if (! tmp___7) {
#line 401
      return (-2);
    }
    {
    {
#line 402
    tmp___8 = (int )escape(off);
    }
    }
#line 402
    if (! tmp___8) {
#line 402
      return (-2);
    }
#line 404
    ptr_on = on;
#line 405
    ptr_off = off;
#line 406
    return (0);
  }
  {
  {
#line 408
  fclose(libfile);
  }
  }
#line 409
  return (1);
}
}
#line 414 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
int main(int argc , char **argv ) 
{ 
  char *tmp ;
  char *env ;
  int result ;
  int cnt ;
  int total ;
  arglist args ;
  size_t tmp___0 ;
  void *tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int ch ;
  int lastch ;
  FILE *infile ;
  int tmp___8 ;
  char const   *tmp___9 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;
  char *__cil_tmp28 ;
  char *__cil_tmp29 ;
  char *__cil_tmp30 ;
  char *__cil_tmp31 ;
  char *__cil_tmp32 ;
  char *__cil_tmp33 ;
  char *__cil_tmp34 ;
  char *__cil_tmp35 ;
  char *__cil_tmp36 ;
  char *__cil_tmp37 ;
  char *__cil_tmp38 ;
  char *__cil_tmp39 ;
  char *__cil_tmp40 ;
  char *__cil_tmp41 ;
  char *__cil_tmp42 ;
  char *__cil_tmp43 ;
  char *__cil_tmp44 ;
  char *__cil_tmp45 ;
  char *__cil_tmp46 ;
  char *__cil_tmp47 ;
  char *__cil_tmp48 ;
  char *__cil_tmp49 ;
  char *__cil_tmp50 ;
  char *__cil_tmp51 ;
  char *__cil_tmp52 ;

  {
  {
#line 419
  cnt = 0;
#line 423
  args.argv = (char **)((void *)0);
  {
#line 426
  vtbasename = strrchr((char const   *)*(argv + 0), '/');
  }
  }
#line 427
  if (vtbasename) {
#line 427
    vtbasename ++;
  } else {
#line 427
    vtbasename = *(argv + 0);
  }
  {
  {
#line 430
  tmp = getenv((char const   *)vtbasename);
  }
  }
#line 431
  if (! tmp) {
    {
    {
#line 431
    tmp = getenv("VTPRINT");
    }
    }
  }
#line 432
  if (! tmp) {
#line 432
    tmp = (char *)"";
  }
  {
  {
#line 434
  tmp___0 = strlen((char const   *)tmp);
  }
  {
#line 434
  tmp___1 = malloc(tmp___0 + 1U);
  }
#line 434
  env = (char *)tmp___1;
  }
#line 435
  if (! env) {
    {
    {
#line 437
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Out of memory!\n",
            vtbasename);
    }
    {
#line 438
    exit(1);
    }
    }
  }
  {
  {
#line 441
  strcpy((char */* __restrict  */)env, (char const   */* __restrict  */)tmp);
  }
  }
#line 447
  if (env) {
    {
    {
#line 449
    string2arglist(env, & args);
    }
    {
#line 450
    process_opts(& args);
    }
    }
  }
  {
  {
#line 454
  argv2arglist(argc, argv, & args);
  }
  {
#line 455
  process_opts(& args);
  }
  }
#line 457
  if (! dowork) {
    {
    {
#line 457
    exit(0);
    }
    }
  }
#line 460
  if (! quiet) {
    {
    {
#line 460
    intro();
    }
    }
  }
#line 463
  if (! builtin) {
    {
    {
#line 465
    result = vtprintcap();
    }
    }
    {
#line 468
    if (result == -2) {
#line 468
      goto case_neg_2;
    }
#line 483
    if (result == -1) {
#line 483
      goto case_neg_1;
    }
#line 498
    if (result == 0) {
#line 498
      goto case_0;
    }
#line 506
    if (result == 1) {
#line 506
      goto case_1;
    }
#line 521
    goto switch_default;
    case_neg_2: /* CIL Label */ 
#line 469
    if (! quiet) {
#line 469
      if (! forcenv) {
        {
        {
#line 471
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Parse error in %s, using builtin codes.\n",
                vtbasename, libtermname);
        }
        }
      } else {
#line 469
        goto _L;
      }
    } else
    _L: /* CIL Label */ 
#line 475
    if (forcenv) {
      {
      {
#line 477
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Parse error in %s!\n",
              vtbasename, libtermname);
      }
      {
#line 479
      exit(1);
      }
      }
    }
#line 481
    goto switch_break;
    case_neg_1: /* CIL Label */ 
#line 484
    if (! quiet) {
#line 484
      if (! forcenv) {
        {
        {
#line 486
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Can\'t open %s, using builtin codes.\n",
                vtbasename, libtermname);
        }
        }
      } else {
#line 484
        goto _L___0;
      }
    } else
    _L___0: /* CIL Label */ 
#line 490
    if (forcenv) {
      {
      {
#line 492
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Can\'t open %s!\n",
              vtbasename, libtermname);
      }
      {
#line 494
      exit(1);
      }
      }
    }
#line 496
    goto switch_break;
    case_0: /* CIL Label */ 
#line 499
    if (! quiet) {
      {
      {
#line 501
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Using %s control codes.\n",
              vtbasename, termname);
      }
      }
    }
#line 504
    goto switch_break;
    case_1: /* CIL Label */ 
#line 507
    if (! quiet) {
#line 507
      if (! forcenv) {
        {
        {
#line 509
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Terminal %s unknown, using builtin codes.\n",
                vtbasename, termname);
        }
        }
      } else {
#line 507
        goto _L___1;
      }
    } else
    _L___1: /* CIL Label */ 
#line 513
    if (forcenv) {
      {
      {
#line 515
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Terminal %s unknown!\n",
              vtbasename, termname);
      }
      {
#line 517
      exit(1);
      }
      }
    }
#line 519
    goto switch_break;
    switch_default: /* CIL Label */ 
    {
    {
#line 522
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: INTERNAL ERROR!!\n",
            vtbasename);
    }
    {
#line 523
    abort();
    }
    }
    switch_break: /* CIL Label */ ;
    }
  }
#line 529
  if (device) {
    {
    {
#line 531
    outfile = fopen((char const   */* __restrict  */)devname, (char const   */* __restrict  */)"w");
    }
    }
#line 532
    if (! outfile) {
      {
      {
#line 534
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Failed to open %s for writing!\n",
              vtbasename, devname);
      }
      {
#line 536
      exit(1);
      }
      }
    }
#line 538
    if (! quiet) {
      {
      {
#line 539
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Using %s for output.\n",
              vtbasename, devname);
      }
      }
    }
  } else {
#line 543
    outfile = stdout;
#line 544
    if (! quiet) {
      {
      {
#line 545
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Using <stdout> for output.\n",
              vtbasename);
      }
      }
    }
  }
  {
  {
#line 549
  tmp___2 = strcmp((char const   *)vtbasename, "vtprton");
  }
  }
#line 549
  if (! tmp___2) {
    {
    {
#line 551
    fflush(outfile);
    }
    {
#line 552
    fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)ptr_on);
    }
    {
#line 553
    fflush(outfile);
    }
    {
#line 554
    exit(0);
    }
    }
  }
  {
  {
#line 556
  tmp___3 = strcmp((char const   *)vtbasename, "vtprtoff");
  }
  }
#line 556
  if (! tmp___3) {
    {
    {
#line 558
    fflush(outfile);
    }
    {
#line 559
    fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)ptr_off);
    }
    {
#line 560
    fflush(outfile);
    }
    {
#line 561
    exit(0);
    }
    }
  }
  {
  {
#line 566
  tmp___6 = fileno(outfile);
  }
  {
#line 566
  tmp___7 = isatty(tmp___6);
  }
  }
#line 566
  if (tmp___7) {
    {
    {
#line 568
    tmp___4 = fileno(outfile);
    }
    {
#line 568
    save_termstate(tmp___4, & oldstate);
    }
#line 569
    state_saved = 1;
    {
#line 570
    memcpy((void */* __restrict  */)((char *)(& newstate)), (void const   */* __restrict  */)((char *)(& oldstate)),
           (size_t )sizeof(termstate ));
    }
    }
#line 571
    if (binary) {
      {
      {
#line 573
      raw_termstate(& newstate);
      }
      {
#line 574
      tmp___5 = fileno(outfile);
      }
      {
#line 574
      restore_termstate(tmp___5, & newstate);
      }
      }
    }
  } else {
#line 579
    binary = 0;
  }
#line 582
  if (! quiet) {
    {
    {
#line 584
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Output flags: ",
            vtbasename);
    }
    }
#line 585
    if (builtin) {
      {
      {
#line 585
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"builtin ");
      }
      }
    }
#line 586
    if (binary) {
      {
      {
#line 586
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"binary ");
      }
      }
    }
#line 587
    if (ffeed) {
      {
      {
#line 587
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"formfeed ");
      }
      }
    }
#line 588
    if (stripcr) {
      {
      {
#line 588
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"noCR ");
      }
      }
    }
#line 589
    if (addcr) {
      {
      {
#line 589
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"addCR ");
      }
      }
    }
    {
    {
#line 590
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\n");
    }
    {
#line 591
    fflush(stderr);
    }
    }
  }
  {
  {
#line 595
  signal(1, & sighandler);
  }
  {
#line 596
  signal(3, & sighandler);
  }
  {
#line 597
  signal(20, & sighandler);
  }
  {
#line 598
  signal(2, & sighandler);
  }
  {
#line 599
  signal(15, & sighandler);
  }
#line 601
  total = argc - optind;
  }
  {
  {
#line 604
  while (1) {
    while_continue___1: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
#line 607
    lastch = 0;
#line 610
    if (optind == argc) {
#line 611
      infile = stdin;
    } else {
      {
      {
#line 612
      infile = fopen((char const   */* __restrict  */)*(argv + optind), (char const   */* __restrict  */)"r");
      }
      }
    }
#line 614
    if (! infile) {
      {
      {
#line 616
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Couldn\'t open %s for reading.\n",
              vtbasename, *(argv + optind));
      }
#line 618
      optind ++;
      }
#line 619
      goto __Cont;
    }
    {
    {
#line 622
    fflush(outfile);
    }
    {
#line 623
    fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)ptr_on);
    }
    {
#line 624
    fflush(outfile);
    }
    }
    {
    {
#line 626
    while (1) {
      while_continue___2: /* CIL Label */ ;
      while_continue___0: /* CIL Label */ ;
      {
      {
#line 626
      ch = fgetc(infile);
      }
      }
#line 626
      if (! (ch != -1)) {
#line 626
        goto while_break___0;
      }
      {
#line 630
      if (ch == 13) {
#line 630
        goto case_13;
      }
#line 634
      if (ch == 10) {
#line 634
        goto case_10;
      }
#line 640
      goto switch_default___0;
      case_13: /* CIL Label */ 
#line 631
      if (! stripcr) {
        {
        {
#line 631
        fputc(ch, outfile);
        }
        }
      }
#line 632
      goto switch_break___0;
      case_10: /* CIL Label */ 
#line 635
      if (lastch != 13) {
#line 635
        if (addcr) {
          {
          {
#line 636
          fputc('\r', outfile);
          }
          }
        }
      }
      {
      {
#line 637
      fputc(ch, outfile);
      }
      }
#line 638
      goto switch_break___0;
      switch_default___0: /* CIL Label */ 
#line 641
      if (lastch == 13) {
#line 641
        if (stripcr) {
          {
          {
#line 642
          fputc('\r', outfile);
          }
          }
        }
      }
      {
      {
#line 643
      fputc(ch, outfile);
      }
      }
#line 644
      goto switch_break___0;
      switch_break___0: /* CIL Label */ ;
      }
#line 647
      lastch = ch;
    }
    while_break___2: /* CIL Label */ ;
    }
    while_break___0: /* CIL Label */ ;
    }
    {
    {
#line 650
    fclose(infile);
    }
    }
#line 651
    if (ffeed) {
      {
      {
#line 651
      fputc('\f', outfile);
      }
      }
    }
    {
    {
#line 652
    fprintf((FILE */* __restrict  */)outfile, (char const   */* __restrict  */)ptr_off);
    }
    {
#line 653
    fflush(outfile);
    }
#line 655
    cnt ++;
    }
#line 657
    if (! quiet) {
#line 659
      if (argc == optind) {
        {
        {
#line 660
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Printed <stdin>.\n",
                vtbasename);
        }
        }
      } else {
        {
        {
#line 662
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Printed %s.\n",
                vtbasename, *(argv + optind));
        }
        }
      }
    }
#line 665
    optind ++;
    __Cont: /* CIL Label */ 
#line 604
    if (! (optind < argc)) {
#line 604
      goto while_break;
    }
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
#line 669
  if (state_saved) {
    {
    {
#line 669
    tmp___8 = fileno(outfile);
    }
    {
#line 669
    restore_termstate(tmp___8, & oldstate);
    }
    }
  }
#line 671
  if (! quiet) {
#line 671
    if (cnt == 1) {
#line 671
      tmp___9 = "";
    } else {
#line 671
      tmp___9 = "s";
    }
    {
    {
#line 671
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: Successfully printed %d file%s (%d specified).\n",
            vtbasename, cnt, tmp___9, total);
    }
    }
  }
#line 675
  return (0);
}
}
#line 337 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
static char on___0[1025]  ;
#line 338 "/home/wslee/benchmarks/textformat/vtprint-2.0.2/vtprint.c"
static char off___0[1025]  ;
